//! Origin marker — distinguishes a skill GENERATED by the mustard scan (swept
//! and regenerated fresh on every run) from one written or adopted by hand
//! (never touched).
//!
//! The canonical signal is the frontmatter `source:` field:
//!   * `source: scan`             → mustard-generated; the sweep deletes it
//!                                   before each generation and it is authored
//!                                   again from scratch (no bias from the old
//!                                   text).
//!   * `source: manual` / absent  → human-owned; preserved forever.
//!
//! Adoption (stop regenerating): flip `source: scan` to `source: manual`. A
//! visible notice comment is injected at the top of the body for the human
//! reader — it is NOT the decision signal (only `source:` is), so adoption is
//! unambiguous in a single field.

/// Visible notice injected right after the frontmatter. Advisory only — never
/// consulted by [`is_mustard_generated`]. English by policy: generated skills
/// are English technical prose in EVERY project, whatever the chat locale.
const NOTICE: &str = "<!-- mustard:generated — regenerated by /scan on every run; hand edits are overwritten. To adopt this skill and stop regeneration, change `source: scan` to `source: manual` in the frontmatter. -->";

/// `true` when the skill was generated by the mustard scan — i.e. its leading
/// frontmatter carries `source: scan`. The only signal; the notice comment is
/// never consulted, so flipping `source:` to `manual` fully adopts the skill.
pub(crate) fn is_mustard_generated(text: &str) -> bool {
    frontmatter_source(text).is_some_and(|s| s.eq_ignore_ascii_case("scan"))
}

/// The `source:` value from the leading `---`…`---` frontmatter block, or
/// `None` when there is no frontmatter or no `source:` key in it.
fn frontmatter_source(text: &str) -> Option<String> {
    frontmatter_value(text, "source:")
}

/// The trimmed value of `key` (e.g. `"source:"`, `"name:"`) inside the leading
/// `---`…`---` frontmatter block, or `None` when there is no frontmatter or the
/// key is absent. Shared by [`is_mustard_generated`] and [`frontmatter_defects`]
/// so both read the block the exact same way.
fn frontmatter_value(text: &str, key: &str) -> Option<String> {
    let text = text.strip_prefix('\u{feff}').unwrap_or(text); // tolerate a BOM
    let mut lines = text.lines();
    if lines.next()?.trim() != "---" {
        return None; // not frontmatter-first → not a generated mold
    }
    for line in lines {
        let l = line.trim();
        if l == "---" {
            break; // end of the frontmatter block
        }
        if let Some(v) = l.strip_prefix(key) {
            return Some(v.trim().to_string());
        }
    }
    None
}

/// Whether the leading `---` frontmatter block is closed by a second `---`.
fn frontmatter_is_closed(text: &str) -> bool {
    let text = text.strip_prefix('\u{feff}').unwrap_or(text);
    let mut lines = text.lines();
    if lines.next().map(str::trim) != Some("---") {
        return false;
    }
    lines.any(|l| l.trim() == "---")
}

/// The reasons `body` is NOT a well-formed generated mold, in reading order —
/// empty when it is fine. This is the gate the apply runs BEFORE writing: a
/// mold that reaches disk without frontmatter-first, or without `source: scan`,
/// is never swept again ([`is_mustard_generated`] returns false) and
/// `mold_present` blocks its cluster forever — a silent orphan indistinguishable
/// from a hand-authored file. Refusing here turns "orphan discovered a scan or
/// two later" into "loud error, nothing written". `name`/`description` are the
/// minimum that makes the file a usable SKILL, so a truncated authoring is
/// caught too. Nothing beyond the canonical frontmatter is required — the body
/// prose is the agent's craft, not a schema.
pub(crate) fn frontmatter_defects(body: &str) -> Vec<&'static str> {
    let mut defects = Vec::new();
    if body.strip_prefix('\u{feff}').unwrap_or(body).lines().next().map(str::trim) != Some("---") {
        // Everything downstream reads the block from line 1; without it there is
        // nothing to check and the whole mold is malformed. One defect, stop.
        return vec!["missing frontmatter (line 1 must be `---`)"];
    }
    if !frontmatter_is_closed(body) {
        defects.push("frontmatter block is not closed by a second `---`");
    }
    if frontmatter_value(body, "name:").is_none_or(|v| v.is_empty()) {
        defects.push("missing `name:` in frontmatter");
    }
    if frontmatter_value(body, "description:").is_none_or(|v| v.is_empty()) {
        defects.push("missing `description:` in frontmatter");
    }
    if !frontmatter_source(body).is_some_and(|s| s.eq_ignore_ascii_case("scan")) {
        // The load-bearing one: without it the sweep can never reclaim the file.
        defects.push("missing `source: scan` (without it the mold is never swept — permanent orphan)");
    }
    defects
}

/// Stamp `body` for writing: normalise line endings + trailing newline, then
/// inject the [`NOTICE`] once, right after the frontmatter block (or at the top
/// when there is no frontmatter). Idempotent — a body already carrying a notice
/// is returned unchanged (modulo normalisation).
pub(crate) fn stamp(body: &str) -> String {
    let normalized = format!("{}\n", body.replace("\r\n", "\n").trim_end());
    if normalized.contains("<!-- mustard:generated") {
        return normalized; // already stamped — do not duplicate
    }
    let lines: Vec<&str> = normalized.lines().collect();
    let close = if lines.first().map(|l| l.trim()) == Some("---") {
        lines
            .iter()
            .enumerate()
            .skip(1)
            .find(|(_, l)| l.trim() == "---")
            .map(|(i, _)| i)
    } else {
        None
    };
    let Some(close) = close else {
        // No frontmatter: the notice goes on top.
        return format!("{NOTICE}\n\n{normalized}");
    };
    let mut out = String::with_capacity(normalized.len() + NOTICE.len() + 4);
    for (i, l) in lines.iter().enumerate() {
        out.push_str(l);
        out.push('\n');
        if i == close {
            out.push('\n');
            out.push_str(NOTICE);
            out.push('\n');
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const SCAN_FM: &str = "---\nname: api-service-pattern\nsource: scan\n---\n\n## Purpose\nbody";
    const MANUAL_FM: &str = "---\nname: hand\nsource: manual\n---\n\n## Purpose\nbody";

    #[test]
    fn source_scan_is_generated() {
        assert!(is_mustard_generated(SCAN_FM));
    }

    #[test]
    fn source_manual_is_not_generated() {
        assert!(!is_mustard_generated(MANUAL_FM));
    }

    #[test]
    fn no_frontmatter_is_not_generated() {
        assert!(!is_mustard_generated("# just a heading\n\nbody"));
        assert!(!is_mustard_generated(""));
    }

    #[test]
    fn frontmatter_without_source_is_not_generated() {
        assert!(!is_mustard_generated("---\nname: x\ntags: [a]\n---\nbody"));
    }

    #[test]
    fn body_source_line_outside_frontmatter_is_ignored() {
        // A `source:` in the body must not be mistaken for the frontmatter key.
        assert!(!is_mustard_generated("---\nname: x\n---\nExample: `source: scan`"));
    }

    #[test]
    fn stamp_injects_notice_after_frontmatter() {
        let out = stamp(SCAN_FM);
        let idx_close = out.find("---\n\n").expect("frontmatter close");
        let idx_notice = out.find("<!-- mustard:generated").expect("notice present");
        let idx_purpose = out.find("## Purpose").expect("body present");
        assert!(idx_close < idx_notice && idx_notice < idx_purpose, "notice sits between frontmatter and body: {out}");
        assert!(is_mustard_generated(&out), "stamped scan mold still reads as generated");
    }

    #[test]
    fn stamp_is_idempotent() {
        let once = stamp(SCAN_FM);
        let twice = stamp(&once);
        assert_eq!(once, twice, "a second stamp changes nothing");
        assert_eq!(once.matches("<!-- mustard:generated").count(), 1, "exactly one notice");
    }

    #[test]
    fn stamp_without_frontmatter_prepends_notice() {
        let out = stamp("# hand heading\n\nbody");
        assert!(out.starts_with("<!-- mustard:generated"), "notice on top: {out}");
    }

    #[test]
    fn adoption_flips_the_signal() {
        let generated = stamp(SCAN_FM);
        assert!(is_mustard_generated(&generated));
        let adopted = generated.replace("source: scan", "source: manual");
        assert!(!is_mustard_generated(&adopted), "flipping source: to manual adopts the skill even with the notice still present");
    }
}
