// Integration tests are separate binary targets and not exempt from
// `clippy::unwrap_used` etc. via `#[cfg(test)]`. Mirror the carve-out from
// `src/main.rs` so test panics on `.unwrap()` remain valid assertions.
#![allow(clippy::unwrap_used, clippy::expect_used)]

//! O gasto de cada dia pelo binário de verdade: o comando `run spend` e a barra
//! de status que lê o arquivo dele. A pasta do gasto e a de configuração do
//! Claude Code são de mentira, numa pasta temporária.

use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use mustard_core::domain::spend::previous_day;
use mustard_core::io::spend::today;
use serde_json::{json, Value};

/// O projeto `loja` num repositório git, com a pasta de configuração, a do
/// gasto e uma pasta pessoal falsa ao lado.
struct Scene {
    dir: tempfile::TempDir,
    project: PathBuf,
    config: PathBuf,
    spend: PathBuf,
    home: PathBuf,
}

impl Scene {
    fn new() -> Self {
        let dir = tempfile::tempdir().expect("tempdir");
        let (project, home, config) = (dir.path().join("loja"), dir.path().join("home"), dir.path().join("config"));
        for path in [&project, &home, &config] {
            std::fs::create_dir_all(path).unwrap();
        }
        assert!(Command::new("git").args(["init", "-q"]).current_dir(&project).status().unwrap().success());
        std::fs::write(project.join("mustard.json"), "{}").unwrap();
        Self { spend: dir.path().join("spend"), dir, project, config, home }
    }

    /// Roda `mustard-rt` no projeto e devolve a saída padrão.
    fn rt(&self, args: &[&str], stdin: &str) -> String {
        let mut child = Command::new(env!("CARGO_BIN_EXE_mustard-rt"))
            .args(args)
            .current_dir(&self.project)
            .env("CLAUDE_PROJECT_DIR", &self.project)
            .env("HOME", &self.home)
            .env("USERPROFILE", &self.home)
            .env("CLAUDE_CONFIG_DIR", &self.config)
            .env("MUSTARD_SPEND_DIR", &self.spend)
            .env("MUSTARD_CLAUDE_BIN", self.home.join("no-claude-here"))
            .env_remove("CLAUDE_PLUGIN_ROOT")
            .env_remove("MUSTARD_ACTIVE_SPEC")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("the binary runs");
        child.stdin.take().unwrap().write_all(stdin.as_bytes()).unwrap();
        String::from_utf8_lossy(&child.wait_with_output().unwrap().stdout).into_owned()
    }

    /// Publicação explicitamente solicitada; nenhum hook inicia o envio.
    fn spend(&self, args: &[&str]) -> Value {
        let publish = if args.contains(&"--url") { &[][..] } else { &["--publish"][..] };
        let out = self.rt(&[&["run", "spend"], publish, args].concat(), "");
        serde_json::from_str(out.trim()).unwrap_or_else(|e| panic!("not JSON ({e}): {out}"))
    }

    /// Grava a conversa `s1` do projeto com as linhas `lines`.
    fn conversation(&self, lines: &[String]) {
        let dir = self.config.join("projects/loja");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("s1.jsonl"), lines.join("\n") + "\n").unwrap();
    }

    fn ledger(&self) -> Value {
        serde_json::from_str(&std::fs::read_to_string(self.spend.join("ledger.json")).unwrap()).unwrap()
    }
}

/// Uma resposta do modelo no dia `day`, gravada em `cwd`, com os usos de
/// ferramenta `tools`.
fn reply(cwd: &Path, id: &str, day: &str, tokens: u64, tools: &[(&str, Value)]) -> String {
    let content: Vec<Value> = tools
        .iter()
        .enumerate()
        .map(|(n, (name, input))| json!({"type": "tool_use", "id": format!("{id}-{n}"), "name": name, "input": input}))
        .collect();
    json!({"timestamp": format!("{day}T15:00:00Z"), "cwd": cwd.to_string_lossy(), "message": {
        "id": id, "model": "m", "usage": {"input_tokens": tokens, "output_tokens": 0}, "content": content}})
    .to_string()
}

/// The static public database generated by the actual binary.
fn database(answer: &Value) -> Value {
    serde_json::from_slice(&std::fs::read(answer["database"].as_str().unwrap()).unwrap()).unwrap()
}

/// A mesma resposta repetida em várias linhas conta os tokens uma vez; `Bash`
/// com `grep` e `Grep` são procuras de código, o `map search` e o `Read` não;
/// o custo do Jev gravado na spec entra na linha do dia, o da busca por
/// palavra e o da montagem da onda juntos; e uma conversa aberta dentro da
/// pasta `.claude` conta no projeto.
#[test]
fn the_command_counts_tokens_once_and_the_code_searches_of_each_day_and_project() {
    let scene = Scene::new();
    let yesterday = previous_day(&today()).unwrap();
    let tools = [
        ("Read", json!({"file_path": "src/a.rs"})),
        ("Bash", json!({"command": "grep -rn frete src"})),
        ("Bash", json!({"command": "mustard-rt run map search \"frete\""})),
        ("Grep", json!({"pattern": "x"})),
    ];
    let spec = scene.project.join(".claude/spec/uma-spec");
    scene.conversation(&[
        reply(&scene.project, "m1", &yesterday, 100, &tools),
        reply(&scene.project, "m1", &yesterday, 250, &tools),
        reply(&scene.project.join(".claude/spec"), "m2", &yesterday, 60, &[("Grep", json!({"pattern": "y"}))]),
    ]);
    let call = |id: u64, command: &str, tokens: u64, cost: u64| {
        json!({"v": 1, "id": id, "code": format!("X-CALL-{id:04}"), "at": format!("{yesterday}T10:00:00-03:00"),
            "type": "call", "author": "binary", "command": command, "tokens": tokens, "cost_micro_usd": cost})
        .to_string()
    };
    std::fs::create_dir_all(&spec).unwrap();
    let calls = [call(1, "word search", 1000, 900), call(2, "word search", 500, 400), call(3, "wave assembly", 200, 100)];
    std::fs::write(spec.join("spec.ndjson"), calls.join("\n") + "\n").unwrap();

    let answer = scene.spend(&[]);
    assert_eq!(answer["counted"]["rows"], json!(1), "{answer}");
    let data=database(&answer);
    let row=&data["rows"][0];
    assert_eq!((row["project"].clone(), row["day"].clone()), (json!("loja"), json!(yesterday)));
    assert_eq!(row["tokens"], json!(310), "the repeated response counts once, with its last line");
    assert_eq!(row["actions"], json!(5), "four tools of the first response and the one inside .claude");
    assert_eq!(row["code_searches"], json!(3), "grep in Bash and the two Grep, not the map search, not the Read");
    assert_eq!((row["jev_tokens"].clone(), row["jev_cost_micro_usd"].clone()), (json!(1700), json!(1400)));
}

/// Dias fechados são contados uma vez; hoje permanece parcial. Exportar não
/// confirma publicação, versões ou envio: todas as linhas não confirmadas
/// ficam disponíveis no pedido seguinte e na preparação de republicação.
#[test]
fn a_closed_day_is_counted_once_today_stays_partial_and_republish_prepares_every_day() {
    let scene = Scene::new();
    let (today, yesterday) = (today(), previous_day(&today()).unwrap());
    let before = previous_day(&yesterday).unwrap();
    let said = |extra: &[String]| {
        let mut all = vec![
            reply(&scene.project, "m1", &yesterday, 100, &[]),
            reply(&scene.project, "m2", &before, 70, &[]),
            reply(&scene.project, "m3", &today, 30, &[("Grep", json!({"pattern": "x"}))]),
        ];
        all.extend_from_slice(extra);
        scene.conversation(&all);
    };
    said(&[]);

    let first = scene.spend(&[]);
    assert_eq!(first["prepared"], true);
    assert_eq!(first["published"], false);
    assert_eq!(first["transport_required"], true);
    assert!(first.get("order").is_none(), "mechanical uploads are not requested from a model");
    assert!(scene.ledger()["copied_through"].is_null());
    assert_eq!(scene.ledger()["versions"], json!({}));
    assert_eq!(first["counted"]["rows"], json!(2), "only the closed days are counted: {first}");
    let data=database(&first);
    let days=data["rows"].as_array().unwrap().iter().map(|row|(row["day"].clone(),row["partial"].clone())).collect::<Vec<_>>();
    assert_eq!(days, [(json!(before),json!(false)),(json!(yesterday),json!(false)),(json!(today),json!(true))]);
    let summary=&data["summary"];
    assert_eq!((summary["today"]["tokens"].clone(),summary["yesterday"]["tokens"].clone()),(json!(30),json!(100)));
    let html=std::fs::read_to_string(first["page"].as_str().unwrap()).unwrap();
    assert!(html.contains("status-grid") && html.contains("Jev") && !html.contains("@claude/artifact-runtime"));
    assert!(!scene.spend.join("copy").exists() && !scene.spend.join("page.html").exists());
    let ledger = scene.ledger();
    assert_eq!(ledger["rows"].as_array().unwrap().len(), 2, "today stays out of the closed file: {ledger}");
    assert_eq!(ledger["counted_through"], json!(yesterday));

    scene.spend(&["--url", "https://claude.ai/code/artifact/gasto"]);
    said(&[reply(&scene.project, "m4", &yesterday, 5000, &[]), reply(&scene.project, "m5", &today, 70, &[])]);
    let second = scene.spend(&[]);
    assert_eq!(second["counted"], Value::Null, "a closed day is not counted twice: {second}");
    let again=database(&second);
    assert_eq!(again["rows"].as_array().unwrap().len(),3);
    assert_eq!(again["rows"].as_array().unwrap().iter().find(|row|row["day"]==today).unwrap()["tokens"],100,"today is recounted");
    assert_eq!(second["published"], false);
    assert!(scene.ledger()["copied_through"].is_null());
    let kept: Vec<u64> = scene.ledger()["rows"].as_array().unwrap().iter().map(|r| r["tokens"].as_u64().unwrap()).collect();
    assert_eq!(kept, [70, 100], "the closed days keep their first count");

    let all = scene.spend(&["--republish"]);
    assert_eq!(database(&all)["rows"],again["rows"],"republish includes every closed/open row");
    assert_eq!(all["published"],false);
    assert!(all.get("copy").is_none() && all.get("order").is_none());
}

/// A barra de status mostra o consumo contra a média lido do arquivo dos dias
/// fechados: sete dias de 120 milhões de tokens e um último de 90 milhões dão
/// menos 25%, com o link do painel. Sem o arquivo, a barra não traz o
/// indicador, mesmo com conversas na máquina: ela só lê o arquivo.
#[test]
fn the_status_bar_shows_the_consumption_against_the_average_with_the_panel_link() {
    let scene = Scene::new();
    let panel = "https://claude.ai/code/artifact/painel-do-consumo";
    let payload = json!({"workspace": {"current_dir": scene.project.to_string_lossy()}, "model": {"display_name": "Opus 5"}})
        .to_string();
    let bar = |scene: &Scene| scene.rt(&["run", "statusline"], &payload);

    scene.conversation(&[reply(&scene.project, "m1", &previous_day(&today()).unwrap(), 90, &[])]);
    assert!(!bar(&scene).contains("consumo"), "no closed-days file, no indicator, however many conversations there are");
    assert!(!scene.spend.join("ledger.json").exists(), "the bar counts nothing and writes nothing");

    let row = |day: &str, tokens: u64| json!({"day": day, "project": "loja", "tokens": tokens, "actions": 300});
    let mut rows: Vec<Value> = (20..=26).map(|day| row(&format!("2026-09-{day}"), 120_000_000)).collect();
    rows.push(row("2026-09-27", 90_000_000));
    std::fs::create_dir_all(&scene.spend).unwrap();
    std::fs::write(scene.spend.join("ledger.json"), json!({"counted_through": "2026-09-27", "url": panel, "rows": rows}).to_string())
        .unwrap();

    let shown = bar(&scene);
    assert!(
        shown.contains(&format!("\u{1b}]8;;{panel}\u{1b}\\")) && shown.contains("consumo \u{2212}25% vs média de 7 dias"),
        "the label links the panel: {shown:?}"
    );
    std::fs::remove_file(scene.spend.join("ledger.json")).unwrap();
    assert!(!bar(&scene).contains("consumo"), "the file is gone, so is the indicator");
}

/// Medição local não prepara página, mesmo com URL histórica. Duas máquinas
/// temporárias executam em paralelo sem compartilhar consumo ou deixar estado.
#[test]
fn local_measurement_never_prepares_external_resources_and_keeps_parallel_machines_isolated() {
    let scenes = [Scene::new(), Scene::new()];
    let today = today();
    let yesterday = previous_day(&today).unwrap();
    for (i, scene) in scenes.iter().enumerate() {
        scene.conversation(&[
            reply(&scene.project, "closed", &yesterday, 100 * (i as u64 + 1), &[]),
            reply(&scene.project, "open", &today, 7 * (i as u64 + 1), &[]),
        ]);
    }
    let results = std::thread::scope(|scope| {
        let jobs = scenes.iter().map(|scene| scope.spawn(|| scene.rt(&["run", "spend"], ""))).collect::<Vec<_>>();
        jobs.into_iter().map(|job| serde_json::from_str::<Value>(&job.join().unwrap()).unwrap()).collect::<Vec<_>>()
    });
    let directories = scenes.iter().map(|s| s.dir.path().to_path_buf()).collect::<Vec<_>>();
    for (i, (scene, result)) in scenes.iter().zip(results).enumerate() {
        assert_eq!(result["ok"], true, "{result}");
        assert_eq!(result["summary"]["today"]["tokens"], 7 * (i as u64 + 1));
        assert_eq!(scene.ledger()["rows"][0]["tokens"], 100 * (i as u64 + 1));
        assert!(result.get("copy").is_none() && result.get("order").is_none(), "{result}");
        assert!(!scene.spend.join("page.html").exists() && !scene.spend.join("copy").exists());
        scene.spend(&["--url", "https://claude.ai/code/artifact/historical"]);
        let again: Value = serde_json::from_str(&scene.rt(&["run", "spend"], "")).unwrap();
        assert!(again.get("copy").is_none() && again.get("order").is_none());
        assert!(!scene.spend.join("page.html").exists() && !scene.spend.join("copy").exists());
    }
    drop(scenes);
    assert!(directories.iter().all(|p| !p.exists()), "all fixture ledgers and conversations are removed");
}
