//! `mustard-rt run verify-pipeline` — multi-stack pipeline verification.
//!
//! Runs build/test verification for the active pipeline: discovers the
//! subprojects from grain's repo model (`grain.model.json` `projects[]`, via
//! the scan tool), runs each subproject's
//! build + test command **sequentially** (see [`verify_targets`] for why), and reports per-subproject
//! status with the new JSON shape introduced in W10.T10.1:
//!
//! ```json
//! {
//!   "overall": "ok" | "fail",
//!   "per_subproject": [
//!     { "name": "...", "ok": true, "duration_ms": 1234, "output": "..." }
//!   ],
//!   "total_duration_ms": 4567,
//!   "timestamp": "2026-..."
//! }
//! ```
//!
//! W10.T10.2 — when a subproject has a `[scripts]` block in its
//! `.claude/commands/stack.md` (generated by W3.T3.1 scan-structural), the
//! declared scripts override the build/test defaults. Otherwise the historical
//! defaults probe applies (cargo/pnpm/python).
//!
//! Per-stack timeouts (W0/AC-0.3) come from env, defaulting to:
//! - Rust:    600 s (`MUSTARD_VERIFY_TIMEOUT_RUST`)
//! - TS/JS:   120 s (`MUSTARD_VERIFY_TIMEOUT_TS`)
//! - Python:  180 s (`MUSTARD_VERIFY_TIMEOUT_PYTHON`)
//!
//! Fail-open on discovery: a missing repo model degrades to the config/defaults
//! probe. Exit `1` when any verification command fails, `0` otherwise.
//!
//! `--format html` additionally writes a standalone HTML report and prints its
//! path on stderr.

use mustard_core::domain::model::event::ActorKind;
use mustard_core::domain::vocabulary::stacks::StackDetection;
use crate::shared::context;
use crate::shared::events::economy;
use crate::report::{table, Report};
use crate::util::platform;
use mustard_core::time::now_iso8601;
use mustard_core::io::fs;
use mustard_core::ClaudePaths;
use serde_json::{json, Value};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// Default per-command timeout (2 min) — the historical contract from
/// `verify-pipeline.js`. Used when the command prefix gives no stack hint.
const CMD_TIMEOUT_SECS: u64 = 120;

/// Per-stack default timeouts (W0/AC-0.3). Overridable by the matching
/// `MUSTARD_VERIFY_TIMEOUT_*` env var so CI/dev can tune without a rebuild.
const TIMEOUT_RUST_SECS: u64 = 600;
const TIMEOUT_TS_SECS: u64 = 120;
const TIMEOUT_PYTHON_SECS: u64 = 180;

/// Pick a timeout based on the verification command's leading token. Rust
/// workspaces routinely exceed the 120 s default; respect that without
/// punishing the TS/Python paths. Env override per stack:
///
/// - `MUSTARD_VERIFY_TIMEOUT_RUST`
/// - `MUSTARD_VERIFY_TIMEOUT_TS`
/// - `MUSTARD_VERIFY_TIMEOUT_PYTHON`
fn effective_timeout(command: &str) -> u64 {
    let head = command.split_whitespace().next().unwrap_or("");
    let (env_key, default) = match head {
        "cargo" | "rustc" => ("MUSTARD_VERIFY_TIMEOUT_RUST", TIMEOUT_RUST_SECS),
        "npm" | "pnpm" | "yarn" | "node" | "tsc" | "vitest" | "playwright" => {
            ("MUSTARD_VERIFY_TIMEOUT_TS", TIMEOUT_TS_SECS)
        }
        "python" | "python3" | "pytest" | "poetry" | "uv" => {
            ("MUSTARD_VERIFY_TIMEOUT_PYTHON", TIMEOUT_PYTHON_SECS)
        }
        _ => return CMD_TIMEOUT_SECS,
    };
    std::env::var(env_key)
        .ok()
        .and_then(|s| s.parse::<u64>().ok())
        .unwrap_or(default)
}

/// A discovered subproject's verification commands.
struct VerifyTarget {
    name: String,
    cwd: PathBuf,
    build: Option<String>,
    test: Option<String>,
}

/// Discover verification targets from grain's model
/// (`.claude/grain.model.json` `projects[]`, via the scan tool) — the
/// deterministic subproject list. Build/test commands come from `mustard.json`
/// (the project's own commands), run in each subproject's directory —
/// **stack-aware**: a subproject whose OWN detected stack differs from the
/// global command's stack runs its stack default instead of the global command
/// sprayed blindly over it (see [`stack_aware_commands`]). A monolingual repo is
/// byte-for-byte unchanged.
///
/// Under `cfg(test)` this is a no-op so unit tests drive verification with their
/// own targets rather than the real model.
fn discover_via_grain(cwd: &Path) -> Vec<VerifyTarget> {
    if cfg!(test) {
        return Vec::new();
    }
    let cmds = mustard_core::ProjectConfig::load(cwd).commands();
    if cmds.build.is_none() && cmds.test.is_none() {
        return Vec::new();
    }
    let model = cwd.join(".claude").join("grain.model.json");
    mustard_core::read_projects(&model)
        .into_iter()
        .map(|p| {
            let target_cwd = if p.dir.is_empty() { cwd.to_path_buf() } else { cwd.join(&p.dir) };
            // Stack-aware command selection for poliglot repos: a single global
            // `mustard.json` test command cannot cover, say, a C#/.NET backend
            // AND a TypeScript dashboard. Let a subproject whose own stack
            // differs from the global command's family run its stack default; a
            // monolingual repo keeps the global command verbatim (see helper).
            let (build, test) =
                stack_aware_commands(&target_cwd, &p.detected_stacks, &cmds.build, &cmds.test);
            VerifyTarget { name: p.name, cwd: target_cwd, build, test }
        })
        .collect()
}

/// Coarse stack family of a shell command, keyed on its leading tool token —
/// the label used to decide whether a subproject's detected stack is the SAME
/// stack the global command assumes. `None` for a blank command; an unknown
/// tool keys on its own leading token so two unknown-but-identical tools still
/// compare equal. Mirrors [`effective_timeout`]'s leading-token classification
/// (different output, same signal source).
fn command_family(command: &str) -> Option<&str> {
    let head = command.split_whitespace().next()?;
    Some(match head {
        "cargo" | "rustc" => "rust",
        "go" => "go",
        "python" | "python3" | "pytest" | "poetry" | "uv" => "python",
        "npm" | "pnpm" | "yarn" | "node" | "tsc" | "vitest" | "playwright" | "npx" => "js",
        "dotnet" => "dotnet",
        other => other,
    })
}

/// The stack family of a `(build, test)` command pair — the test command's
/// family when present, else the build command's. `None` when neither is set.
fn family_of<'a>(build: &'a Option<String>, test: &'a Option<String>) -> Option<&'a str> {
    test.as_deref().or(build.as_deref()).and_then(command_family)
}

/// Choose the build/test commands for ONE grain subproject, stack-aware.
///
/// The global `mustard.json` command set is a SINGLE test command; spraying it
/// over every subproject breaks a poliglot repo (a C#/.NET backend and a
/// TypeScript dashboard cannot both run `cargo test`). When this subproject's
/// OWN stack resolves to a default command whose family DIFFERS from the global
/// command's family, run the subproject's stack default; otherwise keep the
/// global command verbatim.
///
/// Conservative fall-through to the global command (never invents behavior):
/// - `detected_stacks` empty — the grain model inferred no stack for this
///   subproject (older model, or nothing matched). Overriding on a bare
///   directory guess could degrade a working monolingual repo, so we trust the
///   global command. This is what makes "absence of detection ⇒ global" hold.
/// - no default resolvable at `target_cwd` (no top-level manifest recognised by
///   [`discover_defaults`]) — nothing concrete to switch to, keep the global.
/// - same command family — a MONOLINGUAL repo stays BYTE-FOR-BYTE unchanged: we
///   return the global commands as-is, never the stack default's decorated
///   (`--workspace --quiet`) form.
///
/// Reuses [`discover_defaults`] as the single stack→command table rather than
/// duplicating a stack-name→command mapping here.
fn stack_aware_commands(
    target_cwd: &Path,
    detected_stacks: &[StackDetection],
    global_build: &Option<String>,
    global_test: &Option<String>,
) -> (Option<String>, Option<String>) {
    let global = || (global_build.clone(), global_test.clone());
    // No positive stack detection → keep the global command (conservative).
    if detected_stacks.is_empty() {
        return global();
    }
    // The subproject's own stack default, from the shared stack→command table.
    let Some(stack_default) = discover_defaults(target_cwd).into_iter().next() else {
        return global();
    };
    let global_family = family_of(global_build, global_test);
    let stack_family = family_of(&stack_default.build, &stack_default.test);
    // A different, resolvable family ⇒ genuinely different stack ⇒ adopt its
    // default. Same family (or indeterminate) ⇒ keep the global untouched.
    if stack_family.is_some() && stack_family != global_family {
        (stack_default.build, stack_default.test)
    } else {
        global()
    }
}

/// Fallback: scan `pipeline-config.md` for a Build Command column.
fn discover_via_config(cwd: &Path) -> Vec<VerifyTarget> {
    let Ok(paths) = ClaudePaths::for_project(cwd) else {
        return Vec::new();
    };
    let config_path = paths.pipeline_config_md_path();
    let Ok(config) = fs::read_to_string(&config_path) else {
        return Vec::new();
    };
    let lines: Vec<&str> = config.split('\n').collect();
    // Find the header row containing "Build".
    let mut header_idx = None;
    let mut build_col = None;
    for (i, line) in lines.iter().enumerate() {
        if line.contains('|') && line.to_lowercase().contains("build") {
            let cols: Vec<&str> = line.split('|').map(str::trim).collect();
            for (ci, col) in cols.iter().enumerate() {
                if col.to_lowercase().contains("build") {
                    build_col = Some(ci);
                    break;
                }
            }
            header_idx = Some(i);
            break;
        }
    }
    let (Some(hi), Some(bc)) = (header_idx, build_col) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    // Skip the header + separator row.
    for line in lines.iter().skip(hi + 2) {
        if !line.starts_with('|') {
            break;
        }
        let cols: Vec<&str> = line.split('|').map(str::trim).collect();
        let name = cols.get(1).copied().unwrap_or("").to_string();
        let build_cmd = cols.get(bc).copied().unwrap_or("");
        if !build_cmd.is_empty() && build_cmd != "-" && build_cmd != "N/A" {
            out.push(VerifyTarget {
                name,
                cwd: cwd.to_path_buf(),
                build: Some(build_cmd.replace('`', "")),
                test: None,
            });
        }
    }
    out
}

/// Last-resort defaults probe — stack-aware (W0/AC-0.3). Prefers Rust over
/// JS because a Rust monorepo with a root `package.json` (pnpm workspace +
/// Cargo workspace) used to fall through to `npm test` and time out.
fn discover_defaults(cwd: &Path) -> Vec<VerifyTarget> {
    let Ok(entries) = fs::read_dir(cwd) else {
        return Vec::new();
    };
    let names: Vec<String> = entries
        .into_iter()
        .map(|e| e.file_name)
        .collect();
    // Rust first: a workspace `Cargo.toml` is the strongest stack signal.
    if names.iter().any(|n| n == "Cargo.toml") {
        return vec![VerifyTarget {
            name: "default".to_string(),
            cwd: cwd.to_path_buf(),
            build: Some("cargo build --workspace --quiet".to_string()),
            test: Some("cargo test --workspace --quiet".to_string()),
        }];
    }
    if names.iter().any(|n| n == "go.mod") {
        return vec![VerifyTarget {
            name: "default".to_string(),
            cwd: cwd.to_path_buf(),
            build: Some("go build ./...".to_string()),
            test: Some("go test ./...".to_string()),
        }];
    }
    if names.iter().any(|n| n == "pyproject.toml" || n == "setup.py") {
        return vec![VerifyTarget {
            name: "default".to_string(),
            cwd: cwd.to_path_buf(),
            build: None,
            test: Some("python -m pytest -q".to_string()),
        }];
    }
    if names.iter().any(|n| n == "package.json") {
        return vec![VerifyTarget {
            name: "default".to_string(),
            cwd: cwd.to_path_buf(),
            build: Some("npm test".to_string()),
            test: None,
        }];
    }
    if names.iter().any(|n| n.ends_with(".csproj")) {
        return vec![VerifyTarget {
            name: "default".to_string(),
            cwd: cwd.to_path_buf(),
            build: Some("dotnet build".to_string()),
            test: None,
        }];
    }
    Vec::new()
}

/// The workspace crate that produces the orchestrator binary running this very
/// gate. `--exclude`d from the gate's `cargo (build|test) --workspace`: its own
/// shell-spawning tests deadlock when their process-tree root is the `cmd.exe`
/// running the gate, and the running crate can't meaningfully self-test from
/// the gate anyway. Its suite runs in CI / `cargo test -p mustard-rt`.
const ORCHESTRATOR_CRATE: &str = "mustard-rt";

/// Rewrite a whole-workspace `cargo (build|test)` so the in-process close gate
/// tests every OTHER member (core, cli, mcp, scan) and returns in seconds
/// instead of burning the 600 s timeout on the orchestrator crate's tests.
///
/// - A bare `cargo test` (this project's configured command) gets BOTH
///   `--workspace` and `--exclude mustard-rt` — `--exclude` is only valid
///   alongside `--workspace`, so it must be added too.
/// - A `--workspace` command just gets `--exclude mustard-rt`.
/// - A package-scoped command (`-p X` / `--package X`) already avoids the
///   workspace and is left untouched; so is any non-cargo command.
///
/// Idempotent. Excludes ONLY a real workspace member — `mustard-dashboard` is
/// not in the workspace, so excluding it would make cargo error. Tail-append is
/// safe: the gate's commands carry no post-`--` test-binary args.
fn exclude_orchestrator_crate(command: &str) -> String {
    let lower = command.to_ascii_lowercase();
    if !(lower.contains("cargo build") || lower.contains("cargo test")) {
        return command.to_string();
    }
    if lower.contains("-p ") || lower.contains("-p=") || lower.contains("--package") {
        return command.to_string();
    }
    if command.contains(&format!("--exclude {ORCHESTRATOR_CRATE}"))
        || command.contains(&format!("--exclude={ORCHESTRATOR_CRATE}"))
    {
        return command.to_string();
    }
    let mut out = command.to_string();
    if !lower.contains("--workspace") {
        out.push_str(" --workspace");
    }
    out.push_str(" --exclude ");
    out.push_str(ORCHESTRATOR_CRATE);
    out
}

/// Run one shell command in `cwd` with a stack-aware timeout. Returns `Ok` on
/// exit 0, `Err(excerpt)` otherwise. Timeout picked by [`effective_timeout`]
/// (Rust 600 s, TS/Python 120-180 s; env-overridable).
fn run_command(command: &str, cwd: &Path) -> std::result::Result<(), String> {
    // On Windows the gate shell is `cmd.exe`; `mustard-rt`'s own shell-spawning
    // tests deadlock when launched with that `cmd.exe` as their process-tree
    // root, so a `cargo test --workspace` here burns the whole 600 s timeout on
    // the orchestrator crate. Exclude it — the gate still tests every other
    // member. On Unix (the gate shell is `sh`) the suite runs clean, so keep
    // full workspace coverage.
    let rewritten = if cfg!(windows) {
        exclude_orchestrator_crate(command)
    } else {
        command.to_string()
    };
    let mut cmd = platform::build_shell_command(&rewritten);
    cmd.current_dir(cwd)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped());
    let mut child = cmd.spawn().map_err(|e| e.to_string())?;

    // Drain stdout/stderr on dedicated threads. A `cargo test --workspace` can
    // emit far more than the OS pipe buffer (~64 KB); reading only after the
    // child exits would let a full pipe block the writer forever — the child
    // never finishes, `try_wait` never returns `Some`, and the gate burns the
    // whole timeout on a process that already did its work. Concurrent readers
    // keep the pipes empty so the child always makes progress.
    let out_pipe = child.stdout.take();
    let err_pipe = child.stderr.take();
    let out_reader = std::thread::spawn(move || {
        let mut buf = Vec::new();
        if let Some(mut p) = out_pipe {
            let _ = std::io::Read::read_to_end(&mut p, &mut buf);
        }
        buf
    });
    let err_reader = std::thread::spawn(move || {
        let mut buf = Vec::new();
        if let Some(mut p) = err_pipe {
            let _ = std::io::Read::read_to_end(&mut p, &mut buf);
        }
        buf
    });

    let timeout_secs = effective_timeout(&rewritten);
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(timeout_secs);
    loop {
        match child.try_wait() {
            Ok(Some(status)) => {
                let stdout = out_reader.join().unwrap_or_default();
                let stderr = err_reader.join().unwrap_or_default();
                if status.success() {
                    return Ok(());
                }
                let s = String::from_utf8_lossy(&stderr).to_string();
                let combined = if s.trim().is_empty() {
                    String::from_utf8_lossy(&stdout).to_string()
                } else {
                    s
                };
                return Err(combined.chars().take(500).collect());
            }
            Ok(None) => {
                if std::time::Instant::now() >= deadline {
                    let _ = child.kill();
                    let _ = child.wait();
                    // Killing closes the pipes → the readers hit EOF and finish;
                    // join so the threads don't outlive this call.
                    let _ = out_reader.join();
                    let _ = err_reader.join();
                    return Err(format!("timeout after {}ms", timeout_secs * 1000));
                }
                std::thread::sleep(std::time::Duration::from_millis(50));
            }
            Err(e) => return Err(e.to_string()),
        }
    }
}

/// One subproject's verification outcome (W10.T10.1 shape).
#[derive(Debug, Clone)]
struct SubprojectResult {
    name: String,
    ok: bool,
    duration_ms: u128,
    /// Combined output excerpt — stderr preferred, stdout fallback. Empty on success.
    output: String,
    /// True when no build/test commands were declared (legacy `skipped`).
    skipped: bool,
}

/// Aggregated verify result (W10.T10.1 shape).
struct VerifyResult {
    per_subproject: Vec<SubprojectResult>,
    total_duration_ms: u128,
    timestamp: String,
}

impl VerifyResult {
    /// W10.T10.1 — `{ overall, per_subproject, total_duration_ms, timestamp }`.
    /// `overall` is `"ok"` when every non-skipped subproject passed.
    fn to_json(&self) -> Value {
        let any_fail = self.per_subproject.iter().any(|r| !r.skipped && !r.ok);
        let overall = if any_fail { "fail" } else { "ok" };
        let per: Vec<Value> = self
            .per_subproject
            .iter()
            .map(|r| {
                json!({
                    "name": r.name,
                    "ok": r.ok,
                    "duration_ms": u64::try_from(r.duration_ms).unwrap_or(u64::MAX),
                    "output": r.output,
                    "skipped": r.skipped,
                })
            })
            .collect();
        json!({
            "overall": overall,
            "per_subproject": per,
            "total_duration_ms": u64::try_from(self.total_duration_ms).unwrap_or(u64::MAX),
            "timestamp": self.timestamp,
        })
    }

    fn any_failure(&self) -> bool {
        self.per_subproject.iter().any(|r| !r.skipped && !r.ok)
    }
}

/// W10.T10.2 — read `<sub>/.claude/commands/stack.md` and pull declared scripts
/// out of a `[scripts]` block if present. Recognised keys: `build`, `test`,
/// `lint`. Returns `(build, test)` once collapsed; lint is appended to build
/// (the historical pairing). Returns `None` when the file is missing or the
/// block is absent.
fn scripts_from_stack_md(sub_cwd: &Path) -> Option<(Option<String>, Option<String>)> {
    let path = ClaudePaths::for_project(sub_cwd)
        .ok()?
        .commands_dir()
        .join("stack.md");
    let text = fs::read_to_string(&path).ok()?;
    // Locate a `[scripts]` line (markdown header or TOML-ish marker).
    let mut in_block = false;
    let mut build: Option<String> = None;
    let mut test: Option<String> = None;
    let mut lint: Option<String> = None;
    for raw in text.lines() {
        let line = raw.trim();
        // End the block on a blank line or a new section header.
        if in_block {
            if line.is_empty() || line.starts_with('#') || line.starts_with('[') {
                if line.eq_ignore_ascii_case("[scripts]") {
                    continue;
                }
                // Heading without [scripts] tail terminates the block.
                if !line.is_empty() {
                    break;
                }
                continue;
            }
            // Accept `key = "value"`, `key: value`, or `- key: value`.
            let cleaned = line.trim_start_matches('-').trim();
            let (key, value) = if let Some((k, v)) = cleaned.split_once('=') {
                (k.trim(), v.trim())
            } else if let Some((k, v)) = cleaned.split_once(':') {
                (k.trim(), v.trim())
            } else {
                continue;
            };
            let value = value
                .trim()
                .trim_matches(|c: char| c == '"' || c == '\'' || c == '`');
            if value.is_empty() {
                continue;
            }
            match key.to_ascii_lowercase().as_str() {
                "build" => build = Some(value.to_string()),
                "test" => test = Some(value.to_string()),
                "lint" => lint = Some(value.to_string()),
                _ => {}
            }
        }
        if line.eq_ignore_ascii_case("[scripts]") || line.eq_ignore_ascii_case("## scripts") {
            in_block = true;
        }
    }
    if build.is_none() && test.is_none() && lint.is_none() {
        return None;
    }
    let build = match (build, lint) {
        (Some(b), Some(l)) => Some(format!("{b} && {l}")),
        (Some(b), None) => Some(b),
        (None, Some(l)) => Some(l),
        (None, None) => None,
    };
    Some((build, test))
}

/// Discover verification targets — the grain model, then the `pipeline-config.md`
/// fallback, then the defaults probe. Kept separate from [`verify_targets`] so
/// tests can drive verification without spawning the scan tool.
///
/// W10.T10.2: after discovery, each target's commands are overridden when its
/// subproject ships a `[scripts]` block inside `.claude/commands/stack.md`.
fn discover_targets(cwd: &Path) -> Vec<VerifyTarget> {
    let mut targets = discover_via_grain(cwd);
    if targets.is_empty() {
        targets = discover_via_config(cwd);
    }
    if targets.is_empty() {
        targets = discover_defaults(cwd);
    }
    // W10.T10.2 — let stack.md scripts win over the discovered defaults.
    for t in &mut targets {
        if let Some((b, te)) = scripts_from_stack_md(&t.cwd) {
            if b.is_some() {
                t.build = b;
            }
            if te.is_some() {
                t.test = te;
            }
        }
    }
    targets
}

/// Walk `start` and its ancestors, returning the first directory whose
/// `Cargo.toml` declares a `[workspace]` table. `None` when no ancestor has one.
///
/// This is the cheap, spawn-free probe used to collapse cargo targets that share
/// a workspace: a plain `read_to_string` + substring test is enough here (no
/// need to parse TOML or spawn `cargo metadata`). Fail-open — an unreadable or
/// absent `Cargo.toml` simply skips that ancestor.
fn cargo_workspace_root(start: &Path) -> Option<PathBuf> {
    let mut dir = Some(start);
    while let Some(d) = dir {
        let manifest = d.join("Cargo.toml");
        if let Ok(text) = fs::read_to_string(&manifest) {
            if text.contains("[workspace]") {
                return Some(d.to_path_buf());
            }
        }
        dir = d.parent();
    }
    None
}

/// Collapse targets that resolve to the same cargo workspace into one run.
///
/// `discover_via_grain` emits one `VerifyTarget` per grain project, all carrying
/// the SAME global cargo build/test command — in a single Cargo workspace that
/// is ~N redundant full-workspace builds (one per member), which on a large
/// workspace times out. Key each target by its cargo workspace root (when either
/// command is a `cargo` invocation) and keep the FIRST per key.
///
/// Fail-open on the merge: a non-cargo command, or a cargo command whose
/// workspace root can't be resolved, keys on the target's own `cwd`, so distinct
/// subprojects are never wrongly merged.
fn dedup_targets(targets: Vec<VerifyTarget>) -> Vec<VerifyTarget> {
    let is_cargo = |cmd: &Option<String>| {
        cmd.as_deref()
            .and_then(|c| c.split_whitespace().next())
            .is_some_and(|head| head == "cargo")
    };
    let mut seen: std::collections::HashSet<PathBuf> = std::collections::HashSet::new();
    let mut out = Vec::with_capacity(targets.len());
    for target in targets {
        let key = if is_cargo(&target.build) || is_cargo(&target.test) {
            cargo_workspace_root(&target.cwd).unwrap_or_else(|| target.cwd.clone())
        } else {
            target.cwd.clone()
        };
        if seen.insert(key) {
            out.push(target);
        }
    }
    out
}

/// Run verification across all discovered targets.
fn verify(cwd: &Path) -> VerifyResult {
    verify_targets(&dedup_targets(discover_targets(cwd)))
}

/// W10.T10.1 — Run verification across the target list **sequentially**.
///
/// Subprojects run one at a time on purpose. In a single cargo workspace every
/// member (`apps/rt`, `packages/core`, …) resolves to the *same* `target/`
/// directory, so running their `cargo build`/`cargo test` concurrently makes
/// them contend on cargo's build-directory lock — on Windows that wedges
/// indefinitely (one process cannot relink an `.exe` another holds open), which
/// is exactly the deadlock this replaces. Serial execution sidesteps the lock
/// and is no slower for a shared workspace: the first build warms `target/` and
/// the rest are incremental. Build + test within a subproject already run in
/// order (test depends on a green build, by convention).
fn verify_targets(targets: &[VerifyTarget]) -> VerifyResult {
    let started = std::time::Instant::now();
    let timestamp = now_iso8601();

    let per_subproject: Vec<SubprojectResult> = targets
        .iter()
        .map(|target| {
            let sub_started = std::time::Instant::now();
            let cmds: Vec<&String> = [&target.build, &target.test]
                .into_iter()
                .filter_map(Option::as_ref)
                .collect();
            if cmds.is_empty() {
                return SubprojectResult {
                    name: target.name.clone(),
                    ok: true,
                    duration_ms: sub_started.elapsed().as_millis(),
                    output: String::new(),
                    skipped: true,
                };
            }
            let mut output = String::new();
            let mut ok = true;
            for cmd in cmds {
                if let Err(excerpt) = run_command(cmd, &target.cwd) {
                    ok = false;
                    if !output.is_empty() {
                        output.push('\n');
                    }
                    let _ = write!(output, "[{cmd}] {excerpt}");
                }
            }
            SubprojectResult {
                name: target.name.clone(),
                ok,
                duration_ms: sub_started.elapsed().as_millis(),
                output,
                skipped: false,
            }
        })
        .collect();

    VerifyResult {
        per_subproject,
        total_duration_ms: started.elapsed().as_millis(),
        timestamp,
    }
}

/// Write the standalone HTML report. Uses the W10.T10.1 shape.
///
/// `verify-pipeline` is workspace-wide (not per-spec); the W2 cache reorg
/// keeps the report under `<root>/.claude/.metrics/reports/`.
fn write_html_report(cwd: &Path, result: &VerifyResult) -> Option<PathBuf> {
    let paths = ClaudePaths::for_project(cwd).ok()?;
    let dir = paths.metrics_dir().join("reports");
    fs::create_dir_all(&dir).ok()?;
    let passed = result.per_subproject.iter().filter(|r| r.ok && !r.skipped).count();
    let failed = result.per_subproject.iter().filter(|r| !r.ok && !r.skipped).count();
    let skipped = result.per_subproject.iter().filter(|r| r.skipped).count();
    let mut report = Report::new(
        "Pipeline Verification",
        format!("{passed} passed · {failed} failed · {skipped} skipped"),
    );
    let mut rows: Vec<Vec<String>> = Vec::new();
    for r in &result.per_subproject {
        let status = if r.skipped {
            "SKIP"
        } else if r.ok {
            "PASS"
        } else {
            "FAIL"
        };
        let detail: String = if r.skipped || r.ok {
            String::new()
        } else {
            r.output.chars().take(120).collect()
        };
        rows.push(vec![r.name.clone(), status.to_string(), detail]);
    }
    report.section("Targets", &table(&["Target", "Status", "Detail"], &rows));
    let path = dir.join("verify-pipeline.html");
    fs::write_atomic(&path, report.render().as_bytes()).ok()?;
    Some(path)
}

/// Emit `pipeline.economy.operation.invoked` for one verify run.

/// Dispatch `mustard-rt run verify-pipeline`.
pub fn run(format: &str) {
    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let result = verify(&cwd);

    if format == "html" {
        match write_html_report(&cwd, &result) {
            Some(path) => eprintln!("[verify-pipeline] HTML report: {}", path.display()),
            None => eprintln!("[verify-pipeline] WARN: could not write HTML report"),
        }
    }

    println!(
        "{}",
        serde_json::to_string_pretty(&result.to_json()).unwrap_or_else(|_| "{}".to_string())
    );
    economy::emit_operation(&context::cwd(), ActorKind::Orchestrator, "verify-pipeline", result.total_duration_ms as u64, None, json!({"subprojects": result.per_subproject.len(), "ok": !result.any_failure()}));
    if result.any_failure() {
        std::process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn exclude_orchestrator_crate_appends_exclude_to_workspace_cargo() {
        assert_eq!(
            exclude_orchestrator_crate("cargo test --workspace --quiet"),
            "cargo test --workspace --quiet --exclude mustard-rt"
        );
        assert_eq!(
            exclude_orchestrator_crate("cargo build --workspace --quiet"),
            "cargo build --workspace --quiet --exclude mustard-rt"
        );
    }

    #[test]
    fn exclude_orchestrator_crate_adds_workspace_to_bare_cargo() {
        // The bare form (this project's configured `cargo test`) needs BOTH
        // `--workspace` (so `--exclude` is valid) and the exclude itself.
        assert_eq!(
            exclude_orchestrator_crate("cargo test"),
            "cargo test --workspace --exclude mustard-rt"
        );
        assert_eq!(
            exclude_orchestrator_crate("cargo build --quiet"),
            "cargo build --quiet --workspace --exclude mustard-rt"
        );
    }

    #[test]
    fn exclude_orchestrator_crate_skips_non_cargo_and_package_scoped() {
        // Not a cargo build/test → untouched.
        assert_eq!(exclude_orchestrator_crate("npm test"), "npm test");
        // Package-scoped → already avoids the workspace, leave it.
        assert_eq!(exclude_orchestrator_crate("cargo test -p mustard-core"), "cargo test -p mustard-core");
        assert_eq!(exclude_orchestrator_crate("cargo test --package mustard-core"), "cargo test --package mustard-core");
    }

    #[test]
    fn exclude_orchestrator_crate_is_idempotent() {
        let once = exclude_orchestrator_crate("cargo test");
        assert_eq!(once, "cargo test --workspace --exclude mustard-rt");
        assert_eq!(exclude_orchestrator_crate(&once), once);
    }

    #[test]
    fn config_fallback_parses_build_column() {
        let dir = tempdir().unwrap();
        let paths = ClaudePaths::for_project(dir.path()).unwrap();
        let claude = paths.claude_dir();
        std::fs::create_dir_all(&claude).unwrap();
        std::fs::write(
            paths.pipeline_config_md_path(),
            "| Agent | Build Command |\n|-------|---------------|\n| api | `cargo build` |\n",
        )
        .unwrap();
        let targets = discover_via_config(dir.path());
        assert_eq!(targets.len(), 1);
        assert_eq!(targets[0].name, "api");
        assert_eq!(targets[0].build.as_deref(), Some("cargo build"));
    }

    #[test]
    fn verify_targets_empty_yields_empty_result() {
        // `verify_targets` is exercised directly — `verify()` would discover
        // targets via the scan tool (`read_projects`), which a unit test avoids.
        let result = verify_targets(&[]);
        assert!(result.per_subproject.is_empty());
        assert!(!result.any_failure());
        assert_eq!(result.timestamp.len(), 24);
    }

    #[test]
    fn verify_targets_skips_command_less_target() {
        let result = verify_targets(&[VerifyTarget {
            name: "doc".to_string(),
            cwd: std::env::temp_dir(),
            build: None,
            test: None,
        }]);
        assert_eq!(result.per_subproject.len(), 1);
        assert!(result.per_subproject[0].skipped);
        assert!(result.per_subproject[0].ok);
        assert_eq!(result.per_subproject[0].name, "doc");
    }

    #[test]
    fn verify_targets_json_shape_has_required_keys() {
        // AC-W10.1 — output shape must carry `overall` + `per_subproject`.
        let result = verify_targets(&[VerifyTarget {
            name: "doc".to_string(),
            cwd: std::env::temp_dir(),
            build: None,
            test: None,
        }]);
        let j = result.to_json();
        assert!(j.get("overall").is_some());
        assert!(j.get("per_subproject").is_some());
        assert!(j.get("total_duration_ms").is_some());
        assert_eq!(j["overall"].as_str(), Some("ok"));
    }

    #[test]
    fn html_report_is_standalone() {
        let dir = tempdir().unwrap();
        let result = VerifyResult {
            per_subproject: vec![
                SubprojectResult {
                    name: "api".into(),
                    ok: true,
                    duration_ms: 10,
                    output: String::new(),
                    skipped: false,
                },
                SubprojectResult {
                    name: "ui".into(),
                    ok: false,
                    duration_ms: 12,
                    output: "boom".into(),
                    skipped: false,
                },
            ],
            total_duration_ms: 22,
            timestamp: now_iso8601(),
        };
        let path = write_html_report(dir.path(), &result).unwrap();
        let html = std::fs::read_to_string(path).unwrap();
        assert!(html.starts_with("<!doctype html>"));
        assert!(!html.contains("href=") && !html.contains("src="));
        assert!(html.contains("api"));
    }

    #[test]
    fn verify_pipeline_dedups_shared_cargo_workspace() {
        // AC-1 — two targets in the same cargo workspace (root + member) both
        // carrying `cargo build` collapse to ONE run. Drives `dedup_targets`
        // directly — `verify()` would spawn cargo.
        let dir = tempdir().unwrap();
        let root = dir.path();
        std::fs::write(
            root.join("Cargo.toml"),
            "[workspace]\nmembers = [\"crate-a\"]\n",
        )
        .unwrap();
        let member = root.join("crate-a");
        std::fs::create_dir_all(&member).unwrap();
        std::fs::write(member.join("Cargo.toml"), "[package]\nname = \"crate-a\"\n").unwrap();

        let targets = vec![
            VerifyTarget {
                name: "root".to_string(),
                cwd: root.to_path_buf(),
                build: Some("cargo build".to_string()),
                test: None,
            },
            VerifyTarget {
                name: "crate-a".to_string(),
                cwd: member,
                build: Some("cargo build".to_string()),
                test: None,
            },
        ];
        let deduped = dedup_targets(targets);
        assert_eq!(deduped.len(), 1, "shared-workspace cargo targets must collapse to one");
        // First target per key is kept.
        assert_eq!(deduped[0].name, "root");
    }

    #[test]
    fn dedup_keeps_distinct_subprojects() {
        // Fail-open: a target whose command is non-cargo, or whose workspace
        // can't be resolved, keys on its own cwd and is never merged away.
        let dir = tempdir().unwrap();
        let a = dir.path().join("a");
        let b = dir.path().join("b");
        std::fs::create_dir_all(&a).unwrap();
        std::fs::create_dir_all(&b).unwrap();
        let targets = vec![
            VerifyTarget {
                name: "a".to_string(),
                cwd: a,
                build: Some("pnpm build".to_string()),
                test: None,
            },
            VerifyTarget {
                name: "b".to_string(),
                cwd: b,
                build: Some("cargo build".to_string()),
                test: None,
            },
        ];
        assert_eq!(dedup_targets(targets).len(), 2);
    }

    #[test]
    fn stack_md_scripts_block_parsed() {
        let dir = tempdir().unwrap();
        let commands = ClaudePaths::for_project(dir.path()).unwrap().commands_dir();
        std::fs::create_dir_all(&commands).unwrap();
        std::fs::write(
            commands.join("stack.md"),
            "## Scripts\nbuild = \"cargo build\"\ntest = \"cargo test\"\n",
        )
        .unwrap();
        let (b, t) = scripts_from_stack_md(dir.path()).unwrap();
        assert_eq!(b.as_deref(), Some("cargo build"));
        assert_eq!(t.as_deref(), Some("cargo test"));
    }

    fn stack(name: &str) -> StackDetection {
        StackDetection { name: name.to_string(), confidence: 0.65, signals: Vec::new() }
    }

    #[test]
    fn stack_aware_monolingual_keeps_global_verbatim() {
        // INVARIANT: a monolingual repo is byte-for-byte unchanged. A subproject
        // whose stack default shares the global command's family returns the
        // GLOBAL command as-is — never the stack default's decorated
        // (`--workspace --quiet`) form.
        let dir = tempdir().unwrap();
        std::fs::write(dir.path().join("Cargo.toml"), "[workspace]\n").unwrap();
        let (build, test) = stack_aware_commands(
            dir.path(),
            &[stack("rust")],
            &Some("cargo build".to_string()),
            &Some("cargo test".to_string()),
        );
        assert_eq!(build.as_deref(), Some("cargo build"));
        assert_eq!(test.as_deref(), Some("cargo test"));
    }

    #[test]
    fn stack_aware_poliglot_uses_each_subprojects_stack_command() {
        // Two distinct stacks: a C#/.NET backend and a TypeScript dashboard
        // cannot both run the global `cargo test`. Each subproject whose family
        // differs from the global command gets ITS stack default.
        let global_build = Some("cargo build".to_string());
        let global_test = Some("cargo test".to_string());

        // .NET subproject (a top-level `.csproj`) → dotnet, not cargo.
        let dotnet_dir = tempdir().unwrap();
        std::fs::write(dotnet_dir.path().join("Api.csproj"), "<Project/>").unwrap();
        let (b, t) =
            stack_aware_commands(dotnet_dir.path(), &[stack("aspnet")], &global_build, &global_test);
        assert_eq!(b.as_deref(), Some("dotnet build"));
        assert_eq!(t, None);

        // TypeScript subproject (a `package.json`) → npm, not cargo.
        let ts_dir = tempdir().unwrap();
        std::fs::write(ts_dir.path().join("package.json"), "{}").unwrap();
        let (b, t) =
            stack_aware_commands(ts_dir.path(), &[stack("nextjs")], &global_build, &global_test);
        assert_eq!(b.as_deref(), Some("npm test"));
        assert_eq!(t, None);
    }

    #[test]
    fn stack_aware_falls_back_to_global_without_detection() {
        // Conservative gate: no detected stacks → keep the global command even
        // when the directory alone would resolve a different stack default.
        // Absence of detection must never silently switch a working repo.
        let dir = tempdir().unwrap();
        std::fs::write(dir.path().join("package.json"), "{}").unwrap();
        let (b, t) = stack_aware_commands(
            dir.path(),
            &[],
            &Some("cargo build".to_string()),
            &Some("cargo test".to_string()),
        );
        assert_eq!(b.as_deref(), Some("cargo build"));
        assert_eq!(t.as_deref(), Some("cargo test"));
    }
}
