//! Grounded wave conclusions: assertions supplied by an existing wave agent,
//! not generated by another model, and persisted only after accepted delivery.
use super::{Interpretation, Source, current};
use crate::domain::knowledge::resources::Registry;
use crate::io::sha256::Sha256;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::collections::BTreeMap;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Conclusion {
    pub title: String,
    pub text: String,
    pub sources: Vec<Source>,
}

pub fn validate(tree: &Path, value: &Value) -> Result<Vec<Conclusion>, String> {
    let notes: Vec<Conclusion> = serde_json::from_value(value.clone())
        .map_err(|e| format!("wave-knowledge-invalid: {e}"))?;
    if notes.len() > 16 {
        return Err("wave-knowledge-too-many-conclusions".into());
    }
    let registry = Registry::load()?;
    let mut hashes = BTreeMap::new();
    for note in &notes {
        if note.title.trim().is_empty()
            || note.title.len() > 400
            || note.text.trim().is_empty()
            || note.text.len() > 12000
            || note.sources.is_empty()
            || note.sources.len() > 32
        {
            return Err("wave-knowledge-invalid-conclusion".into());
        }
        if registry.sensitive(&note.text) || registry.sensitive(&note.title) {
            return Err("wave-knowledge-sensitive-text".into());
        }
        for source in &note.sources {
            if super::investigation::safe_read(tree, &source.file, &registry).is_none()
                || !current(tree, source, &mut hashes)
            {
                return Err("wave-knowledge-source-changed-or-excluded".into());
            }
        }
    }
    Ok(notes)
}

/// Accepted is an explicit conductor fact. Pending/rejected returns are not
/// promoted to searchable knowledge. Stable IDs make retries idempotent.
pub fn capture(
    root: &Path,
    tree: &Path,
    spec: &str,
    delivery: u64,
    accepted: bool,
    value: &Value,
) -> Result<Value, String> {
    if !accepted {
        return Ok(json!({"status":"pending-or-rejected","recorded":0}));
    }
    let notes = validate(tree, value)?;
    // Validate the entire batch before any write. Source changes during a
    // later write still refuse that individual note; capture can be retried.
    let mut recorded = Vec::new();
    for (position, note) in notes.into_iter().enumerate() {
        let mut hash = Sha256::new();
        hash.update(format!("{spec}:{delivery}:{position}").as_bytes());
        let note = Interpretation {
            id: format!("wave-{}", hash.hex_digest()),
            title: note.title,
            text: note.text,
            status: "hypothesis".into(),
            origin: format!("spec:{spec}/delivery:{delivery}"),
            sources: note.sources,
        };
        recorded.push(super::record_at(root, tree, &note).map_err(|e| format!("{e:?}"))?);
    }
    Ok(
        json!({"status":"accepted-wave-conclusions","recorded":recorded.len(),"notes":recorded,"semantic_status":"agent-assertion; verify before editing"}),
    )
}
