//! `mustard-rt run adapt-cursor` — generate `.cursorrules` from `CLAUDE.md`.
//!
//! Port of the legacy `templates/adapters/cursor/adapter.js`. Reads the
//! repo-root `CLAUDE.md` (and each `apps/*/CLAUDE.md` subproject guard when
//! present) and writes a Cursor-compatible `.cursorrules` file at the repo
//! root. The generated file flattens the orchestrator rules into a single
//! plain-text rules block — Cursor does not yet support per-subdirectory
//! rule files.
//!
//! ## Output shape
//!
//! ```json
//! {
//!   "output":   "/repo/.cursorrules",
//!   "sources":  ["CLAUDE.md", "apps/cli/CLAUDE.md", ...],
//!   "bytes":    1234,
//!   "dry_run":  false
//! }
//! ```
//!
//! Fail-open: a missing root `CLAUDE.md` writes a minimal placeholder file so
//! Cursor still has *some* rules to load instead of hitting an empty path.

use crate::shared::context::session_id;
use crate::util::now_iso8601;
use mustard_core::io::fs::{read_to_string, write_atomic};
use mustard_core::domain::model::event::{Actor, ActorKind, HarnessEvent, SCHEMA_VERSION};
use serde::Serialize;
use serde_json::json;
use std::path::{Path, PathBuf};

/// Options for `mustard-rt run adapt-cursor`.
#[derive(Debug, Clone)]
pub struct AdaptCursorOpts {
    /// Repo root override. Defaults to the current working directory.
    pub repo: Option<PathBuf>,
    /// Preview only — no filesystem mutation.
    pub dry_run: bool,
}

/// JSON report.
#[derive(Debug, Serialize)]
pub struct AdaptReport {
    pub output: String,
    pub sources: Vec<String>,
    pub bytes: usize,
    pub dry_run: bool,
}

/// Discover all `CLAUDE.md` source files under `repo`.
/// Returns absolute paths in deterministic order: root, then `apps/*`, then `packages/*`.
fn discover_sources(repo: &Path) -> Vec<PathBuf> {
    let mut out: Vec<PathBuf> = Vec::new();
    let root = repo.join("CLAUDE.md");
    if root.is_file() {
        out.push(root);
    }
    for subdir in ["apps", "packages"] {
        let parent = repo.join(subdir);
        let Ok(read) = std::fs::read_dir(&parent) else {
            continue;
        };
        let mut children: Vec<PathBuf> = read
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect();
        children.sort();
        for c in children {
            let candidate = c.join("CLAUDE.md");
            if candidate.is_file() {
                out.push(candidate);
            }
        }
    }
    out
}

/// Build the `.cursorrules` body from the discovered sources.
fn build_body(repo: &Path, sources: &[PathBuf]) -> String {
    use std::fmt::Write;
    let mut body = String::with_capacity(4096);
    body.push_str("# Generated by `mustard-rt run adapt-cursor` — do not edit by hand.\n");
    body.push_str("# Sources: CLAUDE.md files in the repo.\n\n");
    if sources.is_empty() {
        body.push_str("(No CLAUDE.md files discovered — add one at the repo root to seed Cursor rules.)\n");
        return body;
    }
    for src in sources {
        let rel = src.strip_prefix(repo).unwrap_or(src).display().to_string();
        let _ = writeln!(body, "# ── {rel} ──\n");
        match read_to_string(src) {
            Ok(text) => body.push_str(&text),
            Err(e) => {
                let _ = writeln!(body, "(read failed: {e})");
            }
        }
        if !body.ends_with("\n\n") {
            body.push('\n');
        }
        body.push('\n');
    }
    body
}

/// Pure adapt routine. Returns (report, body) so tests can assert both.
#[must_use]
pub fn adapt(repo: &Path, dry_run: bool) -> (AdaptReport, String) {
    let sources = discover_sources(repo);
    let body = build_body(repo, &sources);
    let out_path = repo.join(".cursorrules");
    let report = AdaptReport {
        output: out_path.display().to_string(),
        sources: sources
            .iter()
            .map(|p| p.strip_prefix(repo).unwrap_or(p).display().to_string())
            .collect(),
        bytes: body.len(),
        dry_run,
    };
    (report, body)
}

/// CLI entry.
pub fn run(opts: AdaptCursorOpts) {
    let started = std::time::Instant::now();
    let repo = opts.repo.clone().unwrap_or_else(|| {
        std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
    });
    let (report, body) = adapt(&repo, opts.dry_run);
    if !opts.dry_run {
        let out_path = repo.join(".cursorrules");
        if let Err(e) = write_atomic(&out_path, body.as_bytes()) {
            eprintln!("[adapt-cursor] WARN: could not write {} ({e})", out_path.display());
        }
    }
    let body = serde_json::to_string_pretty(&report).unwrap_or_else(|_| "{}".to_string());
    println!("{body}");
    emit_economy(started.elapsed().as_millis());
}

fn emit_economy(duration_ms: u128) {
    let cwd = std::env::current_dir()
        .ok()
        .and_then(|p| p.to_str().map(str::to_string))
        .unwrap_or_else(|| ".".to_string());
    let duration_capped = i64::try_from(duration_ms).unwrap_or(i64::MAX);
    let ev = HarnessEvent {
        v: SCHEMA_VERSION,
        ts: now_iso8601(),
        session_id: session_id(),
        wave: 0,
        actor: Actor {
            kind: ActorKind::Orchestrator,
            id: Some("adapt-cursor".to_string()),
            actor_type: None,
        },
        event: "pipeline.economy.operation.invoked".to_string(),
        payload: json!({
            "operation": "adapt-cursor",
            "duration_ms": duration_capped,
            "tokens_used": 0,
            "was_rust_only": true,
        }),
        spec: None,
    };
    let _ = crate::shared::events::route::emit(&cwd, &ev);
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn discover_picks_up_root_claude_md() {
        let dir = tempdir().unwrap();
        std::fs::write(dir.path().join("CLAUDE.md"), "rules").unwrap();
        let sources = discover_sources(dir.path());
        assert_eq!(sources.len(), 1);
        assert!(sources[0].ends_with("CLAUDE.md"));
    }

    #[test]
    fn discover_walks_apps_subdirs_alphabetically() {
        let dir = tempdir().unwrap();
        std::fs::write(dir.path().join("CLAUDE.md"), "root").unwrap();
        std::fs::create_dir_all(dir.path().join("apps/zeta")).unwrap();
        std::fs::create_dir_all(dir.path().join("apps/alpha")).unwrap();
        std::fs::write(dir.path().join("apps/alpha/CLAUDE.md"), "a").unwrap();
        std::fs::write(dir.path().join("apps/zeta/CLAUDE.md"), "z").unwrap();
        let sources = discover_sources(dir.path());
        assert_eq!(sources.len(), 3);
        // Root, then alpha, then zeta (alphabetical inside apps/).
        let names: Vec<String> = sources
            .iter()
            .map(|p| {
                p.parent()
                    .and_then(|x| x.file_name())
                    .and_then(|n| n.to_str())
                    .unwrap_or("")
                    .to_string()
            })
            .collect();
        assert_eq!(names[1], "alpha");
        assert_eq!(names[2], "zeta");
    }

    #[test]
    fn build_body_includes_each_source_header() {
        let dir = tempdir().unwrap();
        std::fs::write(dir.path().join("CLAUDE.md"), "ROOT_BODY").unwrap();
        let sources = discover_sources(dir.path());
        let body = build_body(dir.path(), &sources);
        assert!(body.contains("─ CLAUDE.md ─"));
        assert!(body.contains("ROOT_BODY"));
        assert!(body.contains("Generated by"));
    }

    #[test]
    fn dry_run_does_not_write_cursorrules() {
        let dir = tempdir().unwrap();
        std::fs::write(dir.path().join("CLAUDE.md"), "rules").unwrap();
        let (report, _) = adapt(dir.path(), /* dry_run = */ true);
        assert!(report.dry_run);
        // We do not call the file-writing CLI entry — just check the report.
        assert!(!dir.path().join(".cursorrules").exists());
    }

    #[test]
    fn empty_repo_produces_placeholder() {
        let dir = tempdir().unwrap();
        let (report, body) = adapt(dir.path(), true);
        assert_eq!(report.sources.len(), 0);
        assert!(body.contains("No CLAUDE.md"));
    }
}
