; ============================================================================
; mustard.nsi — the Windows installer, compiled by `makensis`.
;
; This replaces the Tauri NSIS bundler. Tauri is gone, and with it the only
; reason the installer had to be generated by a JavaScript toolchain: what it
; ships is a folder of executables, a folder of templates and the built React
; assets. `makensis` reads this file and produces the same kind of setup.exe.
;
; INSTALLED LAYOUT — the paths are load-bearing, do not rename them:
;
;   $INSTDIR\mustard-cli\        scan.exe, mustard*.exe, rtk.exe,
;                                mustard-dashboard.exe
;   $INSTDIR\mustard-cli\dist\   the built React assets
;   $INSTDIR\mustard-templates\  the payload `mustard init` copies
;
; WHY dist\ SITS INSIDE mustard-cli\: the dashboard server resolves its assets
; as `<dir of the exe>\dist` (see `resolve_dist` in apps/dashboard/server) after
; trying $MUSTARD_DASHBOARD_DIST. Putting the assets beside the binary means a
; fresh install serves the UI with no environment variable at all — one less
; thing that can go stale on a machine.
;
; WHY mustard-cli IS SPELLED EXACTLY LIKE THAT: hooks.nsh adds this folder to
; the user Path and, on both install and uninstall, strips every entry ending in
; `\mustard-cli`. That suffix match is what keeps upgrades idempotent and what
; clears the dead entries older releases wrote. Renaming the folder here without
; renaming it there leaves the Path pointing at nothing.
;
; PER-USER INSTALL: no UAC prompt, and it matches hooks.nsh, which edits the
; USER Path (HKCU) rather than the machine one.
;
; Build:
;   makensis /DVERSION=0.1.53 /DPAYLOAD=..\..\dist\_win-payload ^
;            /DOUTFILE=..\..\dist\Mustard_0.1.53_x64-setup.exe mustard.nsi
; ============================================================================

Unicode true

!ifndef VERSION
  !define VERSION "0.0.0"
!endif
; Staging directory holding the exact tree to install: bin\, dist\, templates\.
!ifndef PAYLOAD
  !define PAYLOAD "..\..\dist\_win-payload"
!endif
!ifndef OUTFILE
  !define OUTFILE "..\..\dist\Mustard_${VERSION}_x64-setup.exe"
!endif

!define PRODUCT "Mustard"
!define PUBLISHER "Atiz"
!define UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT}"

Name "${PRODUCT} ${VERSION}"
OutFile "${OUTFILE}"
InstallDir "$LOCALAPPDATA\${PRODUCT}"
InstallDirRegKey HKCU "Software\${PRODUCT}" "InstallDir"
RequestExecutionLevel user
SetCompressor /SOLID lzma

VIProductVersion "${VERSION}.0"
VIAddVersionKey "ProductName" "${PRODUCT}"
VIAddVersionKey "CompanyName" "${PUBLISHER}"
VIAddVersionKey "FileDescription" "${PRODUCT} installer"
VIAddVersionKey "FileVersion" "${VERSION}"
VIAddVersionKey "ProductVersion" "${VERSION}"
VIAddVersionKey "LegalCopyright" "${PUBLISHER}"

!include "MUI2.nsh"
!include "FileFunc.nsh"
; FileFunc's helpers only become callable as ${Name} after this declaration —
; including the header is not enough.
!insertmacro GetSize

!define MUI_ABORTWARNING
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "PortugueseBR"
!insertmacro MUI_LANGUAGE "English"

; The Path editing, the templates variable and the Start Menu shortcut all live
; in hooks.nsh — the file that already carries why each of them is done the way
; it is. This script only decides WHEN they run. The path is spelled out from
; ${__FILEDIR__} so the include does not depend on which directory makensis was
; invoked from.
!include "${__FILEDIR__}\hooks.nsh"

; `\*` and not `\*.*`: the second only matches names containing a dot, which
; would silently drop an extension-less file the React build or the templates
; payload happens to emit.
Section "Install"
  SetOutPath "$INSTDIR\mustard-cli"
  File /r "${PAYLOAD}\bin\*"

  ; The React build. `resolve_dist` looks for it right here.
  SetOutPath "$INSTDIR\mustard-cli\dist"
  File /r "${PAYLOAD}\dist\*"

  SetOutPath "$INSTDIR\mustard-templates"
  File /r "${PAYLOAD}\templates\*"

  SetOutPath "$INSTDIR"
  WriteUninstaller "$INSTDIR\uninstall.exe"

  WriteRegStr HKCU "Software\${PRODUCT}" "InstallDir" "$INSTDIR"
  WriteRegStr HKCU "${UNINST_KEY}" "DisplayName" "${PRODUCT}"
  WriteRegStr HKCU "${UNINST_KEY}" "DisplayVersion" "${VERSION}"
  WriteRegStr HKCU "${UNINST_KEY}" "Publisher" "${PUBLISHER}"
  WriteRegStr HKCU "${UNINST_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "${UNINST_KEY}" "DisplayIcon" "$INSTDIR\mustard-cli\mustard-dashboard.exe"
  WriteRegStr HKCU "${UNINST_KEY}" "UninstallString" "$\"$INSTDIR\uninstall.exe$\""
  WriteRegStr HKCU "${UNINST_KEY}" "QuietUninstallString" "$\"$INSTDIR\uninstall.exe$\" /S"
  WriteRegDWORD HKCU "${UNINST_KEY}" "NoModify" 1
  WriteRegDWORD HKCU "${UNINST_KEY}" "NoRepair" 1
  ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  IntFmt $0 "0x%08X" $0
  WriteRegDWORD HKCU "${UNINST_KEY}" "EstimatedSize" "$0"

  !insertmacro NSIS_HOOK_POSTINSTALL
SectionEnd

Section "Uninstall"
  !insertmacro NSIS_HOOK_POSTUNINSTALL

  RMDir /r "$INSTDIR\mustard-cli"
  RMDir /r "$INSTDIR\mustard-templates"
  Delete "$INSTDIR\uninstall.exe"
  RMDir "$INSTDIR"

  DeleteRegKey HKCU "${UNINST_KEY}"
  DeleteRegKey HKCU "Software\${PRODUCT}"
SectionEnd
