import type { ProjectInfo, Analysis } from '../types.js';
import { getRunCommand } from '../services/package-manager.js';

/**
 * Generate CLAUDE.md using templates (fallback when Ollama is unavailable)
 */
export function generateClaudeMd(projectInfo: ProjectInfo, analysis: Analysis): string {
  const sections = [
    generateHeader(projectInfo),
    generateQuickReference(projectInfo),
    generateProjectState(projectInfo),
    generateDelegation(),
    generateCommands(projectInfo),
    generatePipeline(),
    generateEntityRegistry(projectInfo),
    generateGrepai(),
    generateRules(projectInfo, analysis),
    generateLinks()
  ];

  return sections.join('\n\n---\n\n');
}

function generateHeader(projectInfo: ProjectInfo): string {
  return `# ${projectInfo.name} - Instructions for Claude

> Auto-generated by **Mustard CLI v2.0**

Type: **${projectInfo.type}**
Package Manager: **${projectInfo.packageManager ?? 'npm'}**`;
}

function generateQuickReference(projectInfo: ProjectInfo): string {
  const patterns = projectInfo.patterns;

  return `## 1. Quick Reference

\`\`\`
Entities:     PascalCase singular     → Contract, Person, Company
DB Tables:    snake_case plural       → contracts, people, companies
Endpoints:    /api/kebab-case         → /api/contracts, /api/people
Components:   PascalCase.tsx          → ContractForm.tsx
Hooks:        use + camelCase         → useContracts.ts
\`\`\`

### Detected Conventions

| Type | Pattern |
|------|---------|
| Classes | ${patterns?.classes ?? 'PascalCase'} |
| Files | ${typeof patterns?.files === 'object' ? JSON.stringify(patterns.files) : (patterns?.files ?? 'varies')} |
| Folders | ${patterns?.folders ?? 'plural'} |`;
}

function generateProjectState(projectInfo: ProjectInfo): string {
  const rows = projectInfo.stacks.map(s => {
    const tech = s.name + (s.version ? ` ${s.version}` : '');
    return `| ${s.path} | ${tech} | - | ✅ Detected |`;
  }).join('\n');

  return `## 2. Project State

| Project | Technology | Port | Status |
|---------|------------|------|--------|
${rows}`;
}

function generateDelegation(): string {
  return `## 3. DELEGATION VIA TASK TOOL

> 💡 **RECOMMENDED:** Use Task tool to delegate tasks to specialized agents.

### Available Agents

| Agent | Usage | Model |
|-------|-------|-------|
| \`Explore\` | Explore codebase, find files | haiku |
| \`Plan\` | Plan complex implementations | sonnet |
| \`general-purpose\` | Implement code, bug fixes | opus/sonnet |
| \`Bash\` | Execute terminal commands | - |

### Delegation Map

| Request | Agent | Model |
|---------|-------|-------|
| Bug fix | \`general-purpose\` | opus |
| New feature | \`Plan\` → \`general-purpose\` | sonnet/opus |
| Explore code | \`Explore\` | haiku |
| Backend/Frontend/DB | \`general-purpose\` | opus |`;
}

function generateCommands(projectInfo: ProjectInfo): string {
  // Detect appropriate commands based on stack
  const hasNode = projectInfo.stacks.some(s => ['react', 'nextjs', 'node'].includes(s.name));
  const hasDotnet = projectInfo.stacks.some(s => s.name === 'dotnet');
  const hasPython = projectInfo.stacks.some(s => s.name === 'python');

  let runCmd = getRunCommand(projectInfo.packageManager ?? 'npm', 'dev');
  if (hasNode) runCmd = getRunCommand(projectInfo.packageManager ?? 'npm', 'dev');
  if (hasDotnet) runCmd = 'dotnet run';
  if (hasPython) runCmd = 'python main.py';

  return `## 4. Available Commands

### Pipeline

| Command | Description |
|---------|-------------|
| \`/feature <name>\` | **Single entry point for features** - Starts full pipeline |
| \`/bugfix <error>\` | **Single entry point for bugs** - Diagnosis + fix |
| \`/approve\` | Approve spec and start implementation |
| \`/complete\` | Finalize pipeline |
| \`/resume\` | Resume active pipeline |

### Git

| Command | Description |
|---------|-------------|
| \`/commit\` | Simple commit |
| \`/commit-push\` | Commit and push |
| \`/merge-main\` | Merge to main |

### Validation

| Command | Description |
|---------|-------------|
| \`/validate\` | Build + type-check |
| \`/status\` | Consolidated status |

### Sync

| Command | Description |
|---------|-------------|
| \`/sync-registry\` | Update Entity Registry |
| \`/install-deps\` | Install dependencies |
| \`/sync-context\` | Load project context |

### Task Commands (L0 Universal Delegation)

| Command | Emoji | Description |
|---------|-------|-------------|
| \`/task-analyze <scope>\` | 🔍 | Code analysis via Task(Explore) |
| \`/task-review <scope>\` | 🔎 | Code review via Task(general-purpose) |
| \`/task-refactor <scope>\` | 📋⚙️ | Refactoring via Task(Plan) → Task(general-purpose) |
| \`/task-docs <scope>\` | 📊 | Documentation via Task(general-purpose) |

> **CRITICAL:** These commands ensure ALL code activities are delegated to a separate context (Task), keeping the parent context clean.`;
}

function generatePipeline(): string {
  return `## 5. Single Pipeline

\`\`\`
/feature or /bugfix
         │
         ▼
    EXPLORE (Task Explore)
         │
         ▼
      SPEC (spec/active/{name}/spec.md)
         │
    ┌────┴────┐
    ▼         ▼
[APPROVED]  [ITERATE]
    │         │
    ▼    (back)
IMPLEMENT (Task general-purpose)
    │
    ▼
  REVIEW
    │
    ▼
COMPLETED
\`\`\``;
}

function generateEntityRegistry(_projectInfo: ProjectInfo): string {
  // v3.1: Catalog format with patterns, enums, and relationships
  return `## 6. Entity Registry (REQUIRED)

**CRITICAL RULE**: Before searching for ANY entity files,
ALWAYS read \`.claude/entity-registry.json\` first.

### Format

\`\`\`json
{
  "_meta": { "version": "3.1" },
  "_patterns": { "simple": "Bank", "withSubItems": "SalesPlan" },
  "_enums": { "ContractStatus": ["DRAFT", "ACTIVE", "..."] },
  "e": {
    "Contract": { "sub": ["ContractItem"], "refs": ["Partner"] },
    "Bank": {}
  }
}
\`\`\`

### Sections

- \`_patterns\`: Reference entities for each pattern type (use as templates)
- \`_enums\`: Enum values catalog (check before hardcoding)
- \`e\`: Entities with \`sub\` (children) and \`refs\` (FK relationships)`;
}

function generateGrepai(): string {
  return `## 7. grepai - Semantic Search

Use grepai as the preferred tool for code search:

\`\`\`javascript
// Semantic search
grepai_search({ query: "authentication flow" })

// Call tracing
grepai_trace_callers({ symbol: "SaveContract" })
grepai_trace_callees({ symbol: "ValidatePayment" })
\`\`\`

### Search Rules

| Tool | Recommendation |
|------|----------------|
| \`grepai_search\` | ✅ Prefer for semantic search |
| \`grepai_trace_*\` | ✅ Use to understand dependencies |
| \`Grep\` | ⚠️ Use only if grepai is unavailable |
| \`Glob\` | ⚠️ Use for specific file patterns |`;
}

function generateRules(projectInfo: ProjectInfo, analysis: Analysis): string {
  const rules = analysis.rules ?? [];

  const rulesText = rules.length > 0
    ? rules.map(r => `- ${r}`).join('\n')
    : `- Follow project naming conventions
- Use dependency injection
- Keep code testable and modular
- Document public APIs`;

  return `## 8. Rules

### Enforcement Rules

| Level | Rule | Description |
|-------|------|-------------|
| L0 | Universal Delegation | ALL code activities MUST be delegated via Task (separate context) |
| L1 | grepai | Prefer grepai for semantic search |
| L2 | Pipeline | Pipeline required for features/bugs |
| L3 | Patterns | Follow naming conventions |

### Project Rules

${rulesText}`;
}

function generateLinks(): string {
  return `## 9. Links

### Core
- [Enforcement](./core/enforcement.md)
- [Naming Conventions](./core/naming-conventions.md)
- [Pipeline](./core/pipeline.md)

### Commands
- [Mustard Commands](./commands/mustard/) - Core commands (managed by Mustard)
- [User Commands](./commands/) - Custom commands (preserved on updates)

### Prompts
- [Prompts Index](./prompts/_index.md)

### Hooks
- [enforce-pipeline.js](./hooks/enforce-pipeline.js)`;
}
