//! End-to-end contract over machine-written-file classification
//! (classify.rs and generated-markers.toml), driven through the binary: the
//! committed `tests/fixtures/generated_mix` project — a generator banner, a
//! `.gitattributes` override in BOTH directions, and a hand-written control —
//! proves scan stamps `file_class`/`marker` additively on the model and that
//! overrides beat the catalog.
//!
//! Every tool/ecosystem marker name lives in the fixture and in the catalog
//! (generated-markers.toml); `src/` stays agnostic.

#[path = "support/manifest_dir.rs"]
mod manifest_dir;

use std::path::PathBuf;
use std::process::Command;

/// The committed fixture root, resolved from the crate manifest dir.
fn fixture() -> PathBuf {
    manifest_dir::manifest_dir().join("tests").join("fixtures").join("generated_mix")
}

/// Scan the fixture into a temp `grain.model.json` and return (temp dir,
/// parsed model). The `label` keeps each test's temp dir distinct — tests run
/// in parallel in one binary, so a pid-only path would collide.
fn scan_fixture(label: &str) -> (tempfile::TempDir, serde_json::Value) {
    let temp = tempfile::Builder::new().prefix(&format!("scan-generated-mix-{}-", label)).tempdir().unwrap();
    let dir = temp.path().to_path_buf();
    let model = dir.join("grain.model.json");
    let out = Command::new(env!("CARGO_BIN_EXE_scan"))
        .args(["scan", fixture().to_str().unwrap(), "--out", model.to_str().unwrap()])
        .output()
        .expect("run scan over fixture");
    assert!(out.status.success(), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    let v: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&model).expect("read model")).expect("valid model JSON");
    (temp, v)
}

fn find_module<'a>(model: &'a serde_json::Value, path: &str) -> &'a serde_json::Value {
    model["modules"].as_array().unwrap().iter().find(|m| m["path"] == path).unwrap_or_else(|| panic!("module {path} present"))
}

#[test]
fn fixture_modules_carry_class_and_provenance() {
    let (_dir, v) = scan_fixture("model");

    // Banner-marked file: classed generated, marker = the catalog literal.
    let banner = find_module(&v, "src/api_client.ts");
    assert_eq!(banner["file_class"], "generated", "banner file classed: {banner}");
    assert!(
        banner["marker"].as_str().unwrap().contains("generated"),
        "marker carries the catalog literal as provenance: {banner}"
    );

    // Same banner, but .gitattributes says `-linguist-generated`: the override
    // WINS over the catalog — no class at all (field absent, additive).
    let pinned = find_module(&v, "src/override_banner.ts");
    assert!(pinned.get("file_class").is_none(), "negative override pins hand-written: {pinned}");

    // No banner, but .gitattributes says `linguist-generated`: override classes
    // it, with the attribute file as marker.
    let marked = find_module(&v, "src/marked_by_attr.ts");
    assert_eq!(marked["file_class"], "generated", "positive override classes: {marked}");
    assert_eq!(marked["marker"], ".gitattributes:linguist-generated", "override provenance: {marked}");

    // Control: the plain file stays unclassed.
    let plain = find_module(&v, "src/handwritten.ts");
    assert!(plain.get("file_class").is_none(), "hand-written module carries no class: {plain}");

    // Timestamp-scaffolded migration: no banner at all — classed generated by
    // the 14-digit filename rule alone (EF Core / Rails scaffolding).
    let migration = find_module(&v, "src/migrations/20260422034143_add_widget.ts");
    assert_eq!(
        migration["file_class"], "generated",
        "timestamp-prefixed migration classed by path: {migration}"
    );
}
