//! End-to-end contract over machine-written-file classification
//! (classify.rs and generated-markers.toml), driven through the binary: the
//! committed `tests/fixtures/generated_mix` project — a generator banner, a
//! `.gitattributes` override in BOTH directions, and a hand-written control —
//! proves scan stamps `file_class`/`marker` additively on the model and that
//! overrides beat the catalog.
//!
//! Every tool/ecosystem marker name lives in the fixture and in the catalog
//! (generated-markers.toml); `src/` stays agnostic.

#[path = "support/manifest_dir.rs"]
mod manifest_dir;
#[path = "support/model.rs"]
mod model;

use std::path::PathBuf;

/// The committed fixture root, resolved from the crate manifest dir.
fn fixture() -> PathBuf {
    manifest_dir::manifest_dir().join("tests").join("fixtures").join("generated_mix")
}

/// Scan the fixture into a temp map and return (temp dir,
/// parsed model). The `label` keeps each test's temp dir distinct — tests run
/// in parallel in one binary, so a pid-only path would collide.
fn scan_fixture(label: &str) -> (tempfile::TempDir, serde_json::Value) {
    let temp = tempfile::Builder::new().prefix(&format!("scan-generated-mix-{}-", label)).tempdir().unwrap();
    let (v, _) = model::scan(&fixture(), temp.path(), &[]);
    (temp, v)
}

fn find_module<'a>(model: &'a serde_json::Value, path: &str) -> &'a serde_json::Value {
    model["modules"].as_array().unwrap().iter().find(|m| m["path"] == path).unwrap_or_else(|| panic!("module {path} present"))
}

#[test]
fn fixture_modules_carry_class_and_provenance() {
    let (_dir, v) = scan_fixture("model");

    // Banner-marked file: classed generated, marker = the catalog literal.
    let banner = find_module(&v, "src/api_client.ts");
    assert_eq!(banner["file_class"], "generated", "banner file classed: {banner}");
    assert!(
        banner["marker"].as_str().unwrap().contains("generated"),
        "marker carries the catalog literal as provenance: {banner}"
    );

    // Same banner, but .gitattributes says `-linguist-generated`: the override
    // WINS over the catalog — no class at all (field absent, additive).
    let pinned = find_module(&v, "src/override_banner.ts");
    assert!(pinned.get("file_class").is_none(), "negative override pins hand-written: {pinned}");

    // No banner, but .gitattributes says `linguist-generated`: override classes
    // it, with the attribute file as marker.
    let marked = find_module(&v, "src/marked_by_attr.ts");
    assert_eq!(marked["file_class"], "generated", "positive override classes: {marked}");
    assert_eq!(marked["marker"], ".gitattributes:linguist-generated", "override provenance: {marked}");

    // Control: the plain file stays unclassed.
    let plain = find_module(&v, "src/handwritten.ts");
    assert!(plain.get("file_class").is_none(), "hand-written module carries no class: {plain}");

    // Timestamp-scaffolded migration: no banner at all — classed generated by
    // the 14-digit filename rule alone (EF Core / Rails scaffolding).
    let migration = find_module(&v, "src/migrations/20260422034143_add_widget.ts");
    assert_eq!(
        migration["file_class"], "generated",
        "timestamp-prefixed migration classed by path: {migration}"
    );
}

/// A documentação longa da função dos dois arquivos: mais que o teto da
/// documentação curta, para a inteira ficar guardada à parte.
fn long_doc() -> String {
    (0..60).map(|n| format!("regra{n:03}")).collect::<Vec<_>>().join(" ")
}

/// O mesmo arquivo, escrito por máquina ou à mão pela primeira linha: com o
/// aviso de máquina ou sem ele, nas mesmas linhas. Cada um dos cinco campos do
/// texto de dentro das peças tem o que guardar: o comentário do começo, a
/// documentação longa, o comentário e os nomes de dentro da função e o
/// comentário depois dela.
fn cart(first_line: &str) -> String {
    format!(
        "{first_line}\n\nuse std::fmt;\n\n/// {}\npub fn somar(itens: &[u32]) -> u32 {{\n    // o total começa do zero\n    \
         itens.iter().sum()\n}}\n\n// fim do carrinho\n",
        long_doc()
    )
}

/// Um projeto no git com os arquivos, já no primeiro commit.
fn project_with(files: &[(&str, &str)]) -> tempfile::TempDir {
    let temp = tempfile::Builder::new().prefix("scan-generated-text-").tempdir().unwrap();
    let dir = temp.path();
    let git = |args: &[&str]| {
        let out = std::process::Command::new("git")
            .args(["-c", "user.email=scan@example.com", "-c", "user.name=scan", "-c", "commit.gpgsign=false"])
            .args(args)
            .current_dir(dir)
            .output()
            .expect("run git");
        assert!(out.status.success(), "git {args:?}: {}", String::from_utf8_lossy(&out.stderr));
    };
    git(&["init", "-q"]);
    for (rel, body) in files {
        let path = dir.join(rel);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, body).unwrap();
    }
    git(&["add", "-A"]);
    git(&["commit", "-q", "-m", "primeiro"]);
    temp
}

/// Os cinco campos do texto de dentro das peças de um arquivo do mapa: os
/// comentários do arquivo e, de cada declaração, a documentação inteira, os
/// comentários e os nomes.
fn inner_text(module: &serde_json::Value) -> Vec<String> {
    let field = |value: &serde_json::Value, key: &str| value.get(key).and_then(|v| v.as_str()).unwrap_or_default().to_string();
    let mut out = vec![field(module, "file_doc"), field(module, "file_comment")];
    for decl in module["declarations"].as_array().unwrap() {
        out.extend(["whole_doc", "body_comment", "body_names"].map(|key| field(decl, key)));
    }
    out
}

/// O arquivo escrito por máquina guarda as declarações e sai sem o texto de
/// dentro das peças; o arquivo de mão igual guarda os cinco campos.
#[test]
fn a_machine_written_file_keeps_its_declarations_and_none_of_their_inner_text() {
    let generated = cart("// <auto-generated> Soma os itens do carrinho.");
    let by_hand = cart("// Soma os itens do carrinho.");
    let temp = project_with(&[("src/gerado.rs", &generated), ("src/mao.rs", &by_hand)]);
    let (map, _) = model::scan(temp.path(), &temp.path().join(".claude"), &[]);
    let machine_module = find_module(&map, "src/gerado.rs");
    let hand_module = find_module(&map, "src/mao.rs");
    assert_eq!(machine_module["file_class"], "generated", "{machine_module}");

    let header = |module: &serde_json::Value| -> Vec<(String, String, u64, u64, String)> {
        module["declarations"]
            .as_array()
            .unwrap()
            .iter()
            .map(|d| {
                let text = |key: &str| d[key].as_str().unwrap_or_default().to_string();
                (text("kind"), text("name"), d["line"].as_u64().unwrap(), d["end_line"].as_u64().unwrap(), text("signature"))
            })
            .collect()
    };
    assert!(header(machine_module).iter().any(|(_, name, ..)| name == "somar"), "{machine_module}");
    assert_eq!(header(machine_module), header(hand_module), "the same declarations in both files");

    let kept = inner_text(hand_module);
    assert!(kept.iter().all(|text| !text.is_empty()), "the hand-written file keeps all five: {kept:?}");
    assert!(kept.iter().any(|text| text.contains("o total começa do zero")), "{kept:?}");
    let dropped = inner_text(machine_module);
    assert!(dropped.iter().all(String::is_empty), "the machine-written file keeps none: {dropped:?}");
}
