// AUTO-GENERATED by scripts/refactor-folder-per-component.mjs
// (Wave 4 of spec 2026-05-23-dashboard-design-system).
// Re-exports every component in this folder so callers can
// import either granular or aggregated.

export * from "./AcBreakdown";
export * from "./BaseRow";
export * from "./CodeBlock";
export * from "./CollapsibleGroup";
export * from "./DataCard";
export * from "./DiffViewer";
export * from "./EmptyState";
export * from "./EventChip";
export * from "./KPICard";
export * from "./Markdown";
export * from "./PageHeader";
export * from "./PageSurface";
export * from "./PhaseChip";
export * from "./SectionHeader";
export * from "./StatPill";
export * from "./StatusDot";
export * from "./TreeNode";
export * from "./WaveRowLabel";
