//! `mustard-rt run scan-md-validate` — validate generated `.md` artifacts under
//! `.claude/` for the deep-refactor W3 contract.
//!
//! Checks (warn-only when `--strict` is absent):
//!
//! - **Size cap.** Files declared "generated by scan" (`<!-- mustard:generated -->`
//!   sentinel) must not exceed the per-kind line budget (`stack.md` ≤60,
//!   `patterns.md` ≤150, `notes.md` ≤80, `SKILL.md` ≤60). Other files are
//!   capped at 200 lines as a soft default.
//! - **Fence presence.** Files in `commands/` and `skills/` must carry the
//!   `<!-- mustard:generated -->` fence (frontmatter may precede it for SKILLs).
//! - **Wirelinks.** `[[id]]` references are validated against the local
//!   `.claude/graph/index.md` lookup when present. Unresolved wirelinks are
//!   reported as warnings, never failures (the graph index is best-effort).
//! - **Path references.** Lines that look like `Ref: path/to/file.ext` must
//!   resolve to an existing path inside the subproject root.
//! - **Cross-file duplication.** Identical paragraphs (≥4 non-blank lines)
//!   that recur across two or more files in the same subproject are flagged.
//!
//! Output is byte-stable pretty JSON: `{ files, hits, ok }`. Exit code is
//! always `0` (fail-open) unless `--strict` is set and any hit is found.

use mustard_core::fs as mfs;
use serde_json::{json, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

/// Per-file line caps for the size check.
fn line_cap(rel: &str) -> usize {
    let name = rel
        .rsplit('/')
        .next()
        .unwrap_or(rel)
        .to_ascii_lowercase();
    match name.as_str() {
        "stack.md" => 60,
        "patterns.md" => 150,
        "notes.md" => 80,
        "skill.md" => 60,
        _ => 200,
    }
}

/// True when a `.md` body declares itself a generated scan artifact.
fn is_generated(body: &str) -> bool {
    body.contains("<!-- mustard:generated")
}

/// Walk `dir` recursively, yielding every `*.md` path. Fail-open.
fn collect_md(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = mfs::read_dir(dir) else { return };
    for entry in entries {
        if entry.is_dir {
            collect_md(&entry.path, out);
        } else if entry.file_name.to_ascii_lowercase().ends_with(".md") {
            out.push(entry.path);
        }
    }
}

/// Extract `[[id]]` wirelinks from a body.
fn wirelinks(body: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = body.as_bytes();
    let mut i = 0;
    while i + 4 <= bytes.len() {
        if bytes[i] == b'[' && bytes[i + 1] == b'[' {
            if let Some(rel_end) = body[i + 2..].find("]]") {
                let id = &body[i + 2..i + 2 + rel_end];
                if !id.is_empty() && !id.contains('\n') {
                    out.push(id.to_string());
                }
                i += 2 + rel_end + 2;
                continue;
            }
        }
        i += 1;
    }
    out
}

/// Canonical wirelink kinds — every `[[<sub>.<kind>.<slug>]]` reference
/// found under `.claude/graph/` and `.claude/recipes/` must use one of
/// these tokens for `<kind>`. Anything else is a violation.
const CANONICAL_WIRELINK_KINDS: &[&str] = &[
    "spec",
    "skill",
    "command",
    "ref",
    "recipe",
    "conv",
];

/// Validate that every wirelink in `body` follows the canonical
/// `<sub>.<kind>.<slug>` shape, where `<kind>` is one of
/// [`CANONICAL_WIRELINK_KINDS`].
///
/// Returns a vector of `(wirelink, reason)` tuples. Empty vector ⇒ all
/// wirelinks are canonical. Callers should wrap each tuple in a hit object
/// before surfacing to JSON output.
///
/// **Rules:**
/// - Wirelink must have exactly three dot-separated segments.
/// - The middle segment must be in [`CANONICAL_WIRELINK_KINDS`].
/// - First and third segments must be non-empty.
///
/// Fail-open: malformed input is reported as a violation, never a panic.
#[must_use]
pub fn validate_wirelinks_canonical(body: &str) -> Vec<(String, String)> {
    let mut violations: Vec<(String, String)> = Vec::new();
    for id in wirelinks(body) {
        let parts: Vec<&str> = id.split('.').collect();
        if parts.len() != 3 {
            violations.push((
                id.clone(),
                format!(
                    "expected `<sub>.<kind>.<slug>` (3 dot-separated segments), got {}",
                    parts.len()
                ),
            ));
            continue;
        }
        if parts[0].is_empty() || parts[2].is_empty() {
            violations.push((
                id.clone(),
                "sub or slug segment is empty".to_string(),
            ));
            continue;
        }
        if !CANONICAL_WIRELINK_KINDS.contains(&parts[1]) {
            violations.push((
                id.clone(),
                format!(
                    "kind `{}` not in canonical set {:?}",
                    parts[1], CANONICAL_WIRELINK_KINDS
                ),
            ));
        }
    }
    violations
}

/// Walk `dir` recursively and collect every wirelink violation found in
/// `.md` bodies. Used by [`validate`] to gate `.claude/graph/` and
/// `.claude/recipes/` (the two directories where the canonical contract
/// applies). Other directories are exempt — wikilinks elsewhere are
/// free-form by design.
fn canonical_wirelink_hits(repo_root: &Path, dir: &Path) -> Vec<Value> {
    let mut paths: Vec<PathBuf> = Vec::new();
    collect_md(dir, &mut paths);
    let mut hits: Vec<Value> = Vec::new();
    for path in paths {
        let Ok(body) = mfs::read_to_string(&path) else { continue };
        let rel = path
            .strip_prefix(repo_root)
            .unwrap_or(&path)
            .to_string_lossy()
            .replace('\\', "/");
        for (id, reason) in validate_wirelinks_canonical(&body) {
            hits.push(json!({
                "kind": "wirelink-non-canonical",
                "file": rel,
                "id": id,
                "reason": reason,
            }));
        }
    }
    hits
}

/// Extract `Ref: path/file.ext` and similar reference lines.
fn ref_paths(body: &str) -> Vec<String> {
    let mut out = Vec::new();
    for line in body.lines() {
        let trimmed = line.trim_start_matches(|c: char| c == '-' || c == '*' || c.is_whitespace());
        for prefix in &["Ref:", "Ref ", "ref:", "see:", "See:"] {
            if let Some(after) = trimmed.strip_prefix(prefix) {
                let token = after.split_whitespace().next().unwrap_or("");
                if !token.is_empty() && (token.contains('/') || token.contains('.')) {
                    out.push(token.trim_matches(|c: char| c == '`' || c == '"').to_string());
                }
            }
        }
    }
    out
}

/// Load the `.claude/graph/index.md` id → path map when present.
fn load_graph_ids(repo_root: &Path) -> BTreeSet<String> {
    let path = repo_root.join(".claude").join("graph").join("index.md");
    let Ok(body) = mfs::read_to_string(&path) else {
        return BTreeSet::new();
    };
    let mut ids = BTreeSet::new();
    for line in body.lines() {
        // Lines like `- [[sub.kind.slug]] — desc` or `[[id]]: path`.
        for id in wirelinks(line) {
            ids.insert(id);
        }
    }
    ids
}

/// Detect repeated paragraphs (≥4 non-blank lines) across the file set.
fn cross_file_duplicates(files: &BTreeMap<PathBuf, String>) -> Vec<Value> {
    let mut paragraphs: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (path, body) in files {
        let rel = path.to_string_lossy().to_string();
        for chunk in body.split("\n\n") {
            let non_blank: Vec<&str> = chunk
                .lines()
                .map(str::trim)
                .filter(|l| !l.is_empty())
                .collect();
            if non_blank.len() < 4 {
                continue;
            }
            let key = non_blank.join("\n");
            if key.len() < 80 {
                continue;
            }
            paragraphs.entry(key).or_default().push(rel.clone());
        }
    }
    let mut hits = Vec::new();
    for (key, files) in paragraphs {
        let unique: BTreeSet<&String> = files.iter().collect();
        if unique.len() >= 2 {
            let preview: String = key.lines().take(2).collect::<Vec<_>>().join(" / ");
            hits.push(json!({
                "kind": "cross-file-duplication",
                "files": unique.into_iter().cloned().collect::<Vec<_>>(),
                "preview": preview,
            }));
        }
    }
    hits
}

/// One validator pass. `from` narrows the scan to a single subproject path.
pub fn validate(repo_root: &Path, from: Option<&str>, strict: bool) -> (Value, bool) {
    let claude_dir = repo_root.join(".claude");
    let mut scan_dirs: Vec<PathBuf> = Vec::new();
    if let Some(sub) = from {
        scan_dirs.push(repo_root.join(sub).join(".claude"));
    } else {
        scan_dirs.push(claude_dir.clone());
        // Also walk known subproject `.claude/` trees when present.
        for top in ["apps", "packages"] {
            let parent = repo_root.join(top);
            if let Ok(entries) = mfs::read_dir(&parent) {
                for entry in entries {
                    if entry.is_dir {
                        let candidate = entry.path.join(".claude");
                        if candidate.is_dir() {
                            scan_dirs.push(candidate);
                        }
                    }
                }
            }
        }
    }

    let mut md_paths: Vec<PathBuf> = Vec::new();
    for dir in &scan_dirs {
        collect_md(dir, &mut md_paths);
    }
    md_paths.sort();
    md_paths.dedup();

    let mut bodies: BTreeMap<PathBuf, String> = BTreeMap::new();
    for p in &md_paths {
        if let Ok(body) = mfs::read_to_string(p) {
            bodies.insert(p.clone(), body);
        }
    }

    let graph_ids = load_graph_ids(repo_root);
    let mut hits: Vec<Value> = Vec::new();

    for (path, body) in &bodies {
        let rel = path.strip_prefix(repo_root).unwrap_or(path).to_string_lossy().replace('\\', "/");
        let line_count = body.lines().count();
        let cap = line_cap(&rel);
        if line_count > cap {
            hits.push(json!({
                "kind": "size",
                "file": rel,
                "lines": line_count,
                "cap": cap,
            }));
        }

        // Fence required under commands/ and skills/.
        if (rel.contains("/commands/") || rel.contains("/skills/")) && !is_generated(body) {
            hits.push(json!({
                "kind": "fence-missing",
                "file": rel,
            }));
        }

        // Wirelinks resolution (warn when index present and id missing).
        if !graph_ids.is_empty() {
            for id in wirelinks(body) {
                if !graph_ids.contains(&id) {
                    hits.push(json!({
                        "kind": "wirelink-unresolved",
                        "file": rel,
                        "id": id,
                    }));
                }
            }
        }

        // Ref: path/to/file.ext — best-effort existence check (relative to repo root).
        for refp in ref_paths(body) {
            let candidate = repo_root.join(&refp);
            if !candidate.exists() {
                hits.push(json!({
                    "kind": "ref-missing",
                    "file": rel,
                    "ref": refp,
                }));
            }
        }
    }

    hits.extend(cross_file_duplicates(&bodies));

    // Canonical wirelink audit — applies only to `.claude/graph/` and
    // `.claude/recipes/`. Other directories carry free-form wikilinks.
    let graph_dir = repo_root.join(".claude").join("graph");
    if graph_dir.is_dir() {
        hits.extend(canonical_wirelink_hits(repo_root, &graph_dir));
    }
    let recipes_dir = repo_root.join(".claude").join("recipes");
    if recipes_dir.is_dir() {
        hits.extend(canonical_wirelink_hits(repo_root, &recipes_dir));
    }

    let ok = hits.is_empty();
    let exit_fail = strict && !ok;
    (
        json!({
            "files": md_paths.len(),
            "hits": hits,
            "ok": ok,
            "strict": strict,
        }),
        exit_fail,
    )
}

/// Dispatch `mustard-rt run scan-md-validate`.
pub fn run(from: Option<&str>, strict: bool) {
    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let (report, exit_fail) = validate(&cwd, from, strict);
    println!(
        "{}",
        serde_json::to_string_pretty(&report).unwrap_or_else(|_| "{}".into())
    );
    if exit_fail {
        std::process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn line_caps_match_kinds() {
        assert_eq!(line_cap("apps/x/.claude/commands/stack.md"), 60);
        assert_eq!(line_cap("apps/x/.claude/commands/patterns.md"), 150);
        assert_eq!(line_cap("apps/x/.claude/skills/foo/SKILL.md"), 60);
        assert_eq!(line_cap("apps/x/.claude/commands/recipes.md"), 200);
    }

    #[test]
    fn wirelinks_extracted() {
        let body = "see [[rt.skill.x]] and [[cli.conv.y]] but not [single]";
        let links = wirelinks(body);
        assert_eq!(links, vec!["rt.skill.x".to_string(), "cli.conv.y".to_string()]);
    }

    #[test]
    fn ref_paths_extracted() {
        let body = "- Ref: apps/rt/src/main.rs\nsome prose\nSee: docs/x.md";
        let refs = ref_paths(body);
        assert!(refs.contains(&"apps/rt/src/main.rs".to_string()));
        assert!(refs.contains(&"docs/x.md".to_string()));
    }

    #[test]
    fn size_hit_emitted() {
        let dir = tempdir().unwrap();
        let cmd = dir.path().join(".claude").join("commands");
        std::fs::create_dir_all(&cmd).unwrap();
        let body = "<!-- mustard:generated -->\n".to_string() + &"line\n".repeat(80);
        std::fs::write(cmd.join("stack.md"), body).unwrap();
        let (report, _) = validate(dir.path(), None, false);
        let hits = report["hits"].as_array().unwrap();
        assert!(hits.iter().any(|h| h["kind"] == "size"));
    }

    #[test]
    fn canonical_wirelink_accepts_well_formed() {
        let body = "see [[rt.skill.hook-pattern]] and [[cli.conv.failopen]]";
        let v = validate_wirelinks_canonical(body);
        assert!(v.is_empty(), "{v:?}");
    }

    #[test]
    fn canonical_wirelink_rejects_unknown_kind() {
        let body = "[[rt.module.foo]]";
        let v = validate_wirelinks_canonical(body);
        assert_eq!(v.len(), 1);
        assert!(v[0].1.contains("not in canonical set"));
    }

    #[test]
    fn canonical_wirelink_rejects_wrong_segment_count() {
        let body = "[[rt.skill]] and [[a.b.c.d]]";
        let v = validate_wirelinks_canonical(body);
        assert_eq!(v.len(), 2);
    }

    #[test]
    fn canonical_wirelink_hits_under_graph_and_recipes() {
        let dir = tempdir().unwrap();
        let graph = dir.path().join(".claude").join("graph");
        std::fs::create_dir_all(&graph).unwrap();
        std::fs::write(graph.join("x.md"), "[[bad.module.foo]]\n").unwrap();
        let (report, _) = validate(dir.path(), None, false);
        let hits = report["hits"].as_array().unwrap();
        assert!(
            hits.iter().any(|h| h["kind"] == "wirelink-non-canonical"),
            "{report}"
        );
    }

    #[test]
    fn fence_missing_hit() {
        let dir = tempdir().unwrap();
        let cmd = dir.path().join(".claude").join("commands");
        std::fs::create_dir_all(&cmd).unwrap();
        std::fs::write(cmd.join("stack.md"), "no fence here\n").unwrap();
        let (report, _) = validate(dir.path(), None, false);
        let hits = report["hits"].as_array().unwrap();
        assert!(hits.iter().any(|h| h["kind"] == "fence-missing"));
    }
}
