//! `mustard-rt run verify-pipeline` — multi-stack pipeline verification.
//!
//! Runs build/test verification for the active pipeline: discovers the
//! subprojects (via `mustard-rt run sync-detect`), runs each subproject's
//! build + test command in **parallel** via `rayon`, and reports per-subproject
//! status with the new JSON shape introduced in W10.T10.1:
//!
//! ```json
//! {
//!   "overall": "ok" | "fail",
//!   "per_subproject": [
//!     { "name": "...", "ok": true, "duration_ms": 1234, "output": "..." }
//!   ],
//!   "total_duration_ms": 4567,
//!   "timestamp": "2026-..."
//! }
//! ```
//!
//! W10.T10.2 — when a subproject has a `[scripts]` block in its
//! `.claude/commands/stack.md` (generated by W3.T3.1 scan-structural), the
//! declared scripts override the build/test defaults. Otherwise the historical
//! defaults probe applies (cargo/pnpm/python).
//!
//! Per-stack timeouts (W0/AC-0.3) come from env, defaulting to:
//! - Rust:    600 s (`MUSTARD_VERIFY_TIMEOUT_RUST`)
//! - TS/JS:   120 s (`MUSTARD_VERIFY_TIMEOUT_TS`)
//! - Python:  180 s (`MUSTARD_VERIFY_TIMEOUT_PYTHON`)
//!
//! Fail-open on discovery: a missing `sync-detect` degrades to the defaults
//! probe. Exit `1` when any verification command fails, `0` otherwise.
//!
//! `--format html` additionally writes a standalone HTML report and prints its
//! path on stderr.

use crate::report::{table, Report};
use crate::run::env::{current_spec, session_id};
use crate::util::now_iso8601;
use mustard_core::fs;
use mustard_core::ClaudePaths;
use mustard_core::model::event::{Actor, ActorKind, HarnessEvent, SCHEMA_VERSION};
use rayon::prelude::*;
use serde_json::{json, Value};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Default per-command timeout (2 min) — the historical contract from
/// `verify-pipeline.js`. Used when the command prefix gives no stack hint.
const CMD_TIMEOUT_SECS: u64 = 120;

/// Per-stack default timeouts (W0/AC-0.3). Overridable by the matching
/// `MUSTARD_VERIFY_TIMEOUT_*` env var so CI/dev can tune without a rebuild.
const TIMEOUT_RUST_SECS: u64 = 600;
const TIMEOUT_TS_SECS: u64 = 120;
const TIMEOUT_PYTHON_SECS: u64 = 180;

/// Pick a timeout based on the verification command's leading token. Rust
/// workspaces routinely exceed the 120 s default; respect that without
/// punishing the TS/Python paths. Env override per stack:
///
/// - `MUSTARD_VERIFY_TIMEOUT_RUST`
/// - `MUSTARD_VERIFY_TIMEOUT_TS`
/// - `MUSTARD_VERIFY_TIMEOUT_PYTHON`
fn effective_timeout(command: &str) -> u64 {
    let head = command.split_whitespace().next().unwrap_or("");
    let (env_key, default) = match head {
        "cargo" | "rustc" => ("MUSTARD_VERIFY_TIMEOUT_RUST", TIMEOUT_RUST_SECS),
        "npm" | "pnpm" | "yarn" | "node" | "tsc" | "vitest" | "playwright" => {
            ("MUSTARD_VERIFY_TIMEOUT_TS", TIMEOUT_TS_SECS)
        }
        "python" | "python3" | "pytest" | "poetry" | "uv" => {
            ("MUSTARD_VERIFY_TIMEOUT_PYTHON", TIMEOUT_PYTHON_SECS)
        }
        _ => return CMD_TIMEOUT_SECS,
    };
    std::env::var(env_key)
        .ok()
        .and_then(|s| s.parse::<u64>().ok())
        .unwrap_or(default)
}

/// A discovered subproject's verification commands.
struct VerifyTarget {
    name: String,
    cwd: PathBuf,
    build: Option<String>,
    test: Option<String>,
}

/// Discover targets via `mustard-rt run sync-detect`.
///
/// Under `cfg(test)` this is a no-op: `current_exe()` would resolve to the
/// libtest binary, and spawning it with `run sync-detect` re-runs the whole
/// suite (a fork bomb). Production builds spawn the real `mustard-rt`.
fn discover_via_sync_detect(cwd: &Path) -> Vec<VerifyTarget> {
    if cfg!(test) {
        return Vec::new();
    }
    let Ok(exe) = std::env::current_exe() else {
        return Vec::new();
    };
    let output = Command::new(exe)
        .args(["run", "sync-detect"])
        .current_dir(cwd)
        .output();
    let Ok(out) = output else {
        return Vec::new();
    };
    let Ok(text) = String::from_utf8(out.stdout) else {
        return Vec::new();
    };
    let Ok(parsed) = serde_json::from_str::<Value>(&text) else {
        return Vec::new();
    };
    let subprojects = parsed
        .get("subprojects")
        .or_else(|| parsed.get("projects"))
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let mut out = Vec::new();
    for (i, sp) in subprojects.iter().enumerate() {
        let build = sp
            .get("buildCommand")
            .or_else(|| sp.get("validateCommand"))
            .and_then(Value::as_str)
            .filter(|s| !s.is_empty())
            .map(str::to_string);
        let test = sp
            .get("testCommand")
            .and_then(Value::as_str)
            .filter(|s| !s.is_empty())
            .map(str::to_string);
        if build.is_none() && test.is_none() {
            continue;
        }
        let name = sp
            .get("name")
            .or_else(|| sp.get("path"))
            .and_then(Value::as_str)
            .map_or_else(|| format!("subproject-{i}"), str::to_string);
        let sp_cwd = sp
            .get("path")
            .and_then(Value::as_str)
            .map_or_else(|| cwd.to_path_buf(), |p| cwd.join(p));
        out.push(VerifyTarget { name, cwd: sp_cwd, build, test });
    }
    out
}

/// Fallback: scan `pipeline-config.md` for a Build Command column.
fn discover_via_config(cwd: &Path) -> Vec<VerifyTarget> {
    let Ok(paths) = ClaudePaths::for_project(cwd) else {
        return Vec::new();
    };
    let config_path = paths.pipeline_config_md_path();
    let Ok(config) = fs::read_to_string(&config_path) else {
        return Vec::new();
    };
    let lines: Vec<&str> = config.split('\n').collect();
    // Find the header row containing "Build".
    let mut header_idx = None;
    let mut build_col = None;
    for (i, line) in lines.iter().enumerate() {
        if line.contains('|') && line.to_lowercase().contains("build") {
            let cols: Vec<&str> = line.split('|').map(str::trim).collect();
            for (ci, col) in cols.iter().enumerate() {
                if col.to_lowercase().contains("build") {
                    build_col = Some(ci);
                    break;
                }
            }
            header_idx = Some(i);
            break;
        }
    }
    let (Some(hi), Some(bc)) = (header_idx, build_col) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    // Skip the header + separator row.
    for line in lines.iter().skip(hi + 2) {
        if !line.starts_with('|') {
            break;
        }
        let cols: Vec<&str> = line.split('|').map(str::trim).collect();
        let name = cols.get(1).copied().unwrap_or("").to_string();
        let build_cmd = cols.get(bc).copied().unwrap_or("");
        if !build_cmd.is_empty() && build_cmd != "-" && build_cmd != "N/A" {
            out.push(VerifyTarget {
                name,
                cwd: cwd.to_path_buf(),
                build: Some(build_cmd.replace('`', "")),
                test: None,
            });
        }
    }
    out
}

/// Last-resort defaults probe — stack-aware (W0/AC-0.3). Prefers Rust over
/// JS because a Rust monorepo with a root `package.json` (pnpm workspace +
/// Cargo workspace) used to fall through to `npm test` and time out.
fn discover_defaults(cwd: &Path) -> Vec<VerifyTarget> {
    let Ok(entries) = fs::read_dir(cwd) else {
        return Vec::new();
    };
    let names: Vec<String> = entries
        .into_iter()
        .map(|e| e.file_name)
        .collect();
    // Rust first: a workspace `Cargo.toml` is the strongest stack signal.
    if names.iter().any(|n| n == "Cargo.toml") {
        return vec![VerifyTarget {
            name: "default".to_string(),
            cwd: cwd.to_path_buf(),
            build: Some("cargo build --workspace --quiet".to_string()),
            test: Some("cargo test --workspace --quiet".to_string()),
        }];
    }
    if names.iter().any(|n| n == "go.mod") {
        return vec![VerifyTarget {
            name: "default".to_string(),
            cwd: cwd.to_path_buf(),
            build: Some("go build ./...".to_string()),
            test: Some("go test ./...".to_string()),
        }];
    }
    if names.iter().any(|n| n == "pyproject.toml" || n == "setup.py") {
        return vec![VerifyTarget {
            name: "default".to_string(),
            cwd: cwd.to_path_buf(),
            build: None,
            test: Some("python -m pytest -q".to_string()),
        }];
    }
    if names.iter().any(|n| n == "package.json") {
        return vec![VerifyTarget {
            name: "default".to_string(),
            cwd: cwd.to_path_buf(),
            build: Some("npm test".to_string()),
            test: None,
        }];
    }
    if names.iter().any(|n| n.ends_with(".csproj")) {
        return vec![VerifyTarget {
            name: "default".to_string(),
            cwd: cwd.to_path_buf(),
            build: Some("dotnet build".to_string()),
            test: None,
        }];
    }
    Vec::new()
}

/// Build the platform shell invocation for a verification `command` string.
///
/// Verification commands come from `sync-detect`, the `pipeline-config.md`
/// table, or the defaults probe — arbitrary strings that may carry quotes or
/// shell operators. On Windows, `cmd.exe` does not parse its command line via
/// the `CommandLineToArgvW` rules that `std`'s `Command::arg` quoting assumes,
/// so the command is appended verbatim with `CommandExt::raw_arg` (a SAFE API)
/// and run as `cmd /S /C "<command>"`, mirroring `qa_run::build_shell_command`.
#[cfg(windows)]
fn build_shell_command(command: &str) -> Command {
    use std::os::windows::process::CommandExt;
    let mut c = Command::new("cmd");
    c.raw_arg(format!("/S /C \"{command}\""));
    c
}

/// See the `#[cfg(windows)]` variant for the rationale.
#[cfg(not(windows))]
fn build_shell_command(command: &str) -> Command {
    let mut c = Command::new("sh");
    c.arg("-c").arg(command);
    c
}

/// Run one shell command in `cwd` with a stack-aware timeout. Returns `Ok` on
/// exit 0, `Err(excerpt)` otherwise. Timeout picked by [`effective_timeout`]
/// (Rust 600 s, TS/Python 120-180 s; env-overridable).
fn run_command(command: &str, cwd: &Path) -> std::result::Result<(), String> {
    let mut cmd = build_shell_command(command);
    cmd.current_dir(cwd)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped());
    let mut child = cmd.spawn().map_err(|e| e.to_string())?;
    let timeout_secs = effective_timeout(command);
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(timeout_secs);
    loop {
        match child.try_wait() {
            Ok(Some(status)) => {
                let out = child.wait_with_output().ok();
                if status.success() {
                    return Ok(());
                }
                let excerpt: String = out
                    .map(|o| {
                        let s = String::from_utf8_lossy(&o.stderr).to_string();
                        if s.trim().is_empty() {
                            String::from_utf8_lossy(&o.stdout).to_string()
                        } else {
                            s
                        }
                    })
                    .unwrap_or_default()
                    .chars()
                    .take(500)
                    .collect();
                return Err(excerpt);
            }
            Ok(None) => {
                if std::time::Instant::now() >= deadline {
                    let _ = child.kill();
                    let _ = child.wait();
                    return Err(format!("timeout after {}ms", timeout_secs * 1000));
                }
                std::thread::sleep(std::time::Duration::from_millis(50));
            }
            Err(e) => return Err(e.to_string()),
        }
    }
}

/// One subproject's verification outcome (W10.T10.1 shape).
#[derive(Debug, Clone)]
struct SubprojectResult {
    name: String,
    ok: bool,
    duration_ms: u128,
    /// Combined output excerpt — stderr preferred, stdout fallback. Empty on success.
    output: String,
    /// True when no build/test commands were declared (legacy `skipped`).
    skipped: bool,
}

/// Aggregated verify result (W10.T10.1 shape).
struct VerifyResult {
    per_subproject: Vec<SubprojectResult>,
    total_duration_ms: u128,
    timestamp: String,
}

impl VerifyResult {
    /// W10.T10.1 — `{ overall, per_subproject, total_duration_ms, timestamp }`.
    /// `overall` is `"ok"` when every non-skipped subproject passed.
    fn to_json(&self) -> Value {
        let any_fail = self.per_subproject.iter().any(|r| !r.skipped && !r.ok);
        let overall = if any_fail { "fail" } else { "ok" };
        let per: Vec<Value> = self
            .per_subproject
            .iter()
            .map(|r| {
                json!({
                    "name": r.name,
                    "ok": r.ok,
                    "duration_ms": u64::try_from(r.duration_ms).unwrap_or(u64::MAX),
                    "output": r.output,
                    "skipped": r.skipped,
                })
            })
            .collect();
        json!({
            "overall": overall,
            "per_subproject": per,
            "total_duration_ms": u64::try_from(self.total_duration_ms).unwrap_or(u64::MAX),
            "timestamp": self.timestamp,
        })
    }

    fn any_failure(&self) -> bool {
        self.per_subproject.iter().any(|r| !r.skipped && !r.ok)
    }
}

/// W10.T10.2 — read `<sub>/.claude/commands/stack.md` and pull declared scripts
/// out of a `[scripts]` block if present. Recognised keys: `build`, `test`,
/// `lint`. Returns `(build, test)` once collapsed; lint is appended to build
/// (the historical pairing). Returns `None` when the file is missing or the
/// block is absent.
fn scripts_from_stack_md(sub_cwd: &Path) -> Option<(Option<String>, Option<String>)> {
    let path = ClaudePaths::for_project(sub_cwd)
        .ok()?
        .commands_dir()
        .join("stack.md");
    let text = fs::read_to_string(&path).ok()?;
    // Locate a `[scripts]` line (markdown header or TOML-ish marker).
    let mut in_block = false;
    let mut build: Option<String> = None;
    let mut test: Option<String> = None;
    let mut lint: Option<String> = None;
    for raw in text.lines() {
        let line = raw.trim();
        // End the block on a blank line or a new section header.
        if in_block {
            if line.is_empty() || line.starts_with('#') || line.starts_with('[') {
                if line.eq_ignore_ascii_case("[scripts]") {
                    continue;
                }
                // Heading without [scripts] tail terminates the block.
                if !line.is_empty() {
                    break;
                }
                continue;
            }
            // Accept `key = "value"`, `key: value`, or `- key: value`.
            let cleaned = line.trim_start_matches('-').trim();
            let (key, value) = if let Some((k, v)) = cleaned.split_once('=') {
                (k.trim(), v.trim())
            } else if let Some((k, v)) = cleaned.split_once(':') {
                (k.trim(), v.trim())
            } else {
                continue;
            };
            let value = value
                .trim()
                .trim_matches(|c: char| c == '"' || c == '\'' || c == '`');
            if value.is_empty() {
                continue;
            }
            match key.to_ascii_lowercase().as_str() {
                "build" => build = Some(value.to_string()),
                "test" => test = Some(value.to_string()),
                "lint" => lint = Some(value.to_string()),
                _ => {}
            }
        }
        if line.eq_ignore_ascii_case("[scripts]") || line.eq_ignore_ascii_case("## scripts") {
            in_block = true;
        }
    }
    if build.is_none() && test.is_none() && lint.is_none() {
        return None;
    }
    let build = match (build, lint) {
        (Some(b), Some(l)) => Some(format!("{b} && {l}")),
        (Some(b), None) => Some(b),
        (None, Some(l)) => Some(l),
        (None, None) => None,
    };
    Some((build, test))
}

/// Discover verification targets — sync-detect, then the `pipeline-config.md`
/// fallback, then the defaults probe. Kept separate from [`verify_targets`] so
/// tests can drive verification without the `sync-detect` subprocess spawn.
///
/// W10.T10.2: after discovery, each target's commands are overridden when its
/// subproject ships a `[scripts]` block inside `.claude/commands/stack.md`.
fn discover_targets(cwd: &Path) -> Vec<VerifyTarget> {
    let mut targets = discover_via_sync_detect(cwd);
    if targets.is_empty() {
        targets = discover_via_config(cwd);
    }
    if targets.is_empty() {
        targets = discover_defaults(cwd);
    }
    // W10.T10.2 — let stack.md scripts win over sync-detect defaults.
    for t in &mut targets {
        if let Some((b, te)) = scripts_from_stack_md(&t.cwd) {
            if b.is_some() {
                t.build = b;
            }
            if te.is_some() {
                t.test = te;
            }
        }
    }
    targets
}

/// Run verification across all discovered targets.
fn verify(cwd: &Path) -> VerifyResult {
    verify_targets(&discover_targets(cwd))
}

/// W10.T10.1 — Run verification across the target list **in parallel** via
/// rayon. Each subproject becomes one rayon task; build + test inside a
/// subproject still run sequentially (test depends on a green build, by
/// convention).
fn verify_targets(targets: &[VerifyTarget]) -> VerifyResult {
    let started = std::time::Instant::now();
    let timestamp = now_iso8601();

    let per_subproject: Vec<SubprojectResult> = targets
        .par_iter()
        .map(|target| {
            let sub_started = std::time::Instant::now();
            let cmds: Vec<&String> = [&target.build, &target.test]
                .into_iter()
                .filter_map(Option::as_ref)
                .collect();
            if cmds.is_empty() {
                return SubprojectResult {
                    name: target.name.clone(),
                    ok: true,
                    duration_ms: sub_started.elapsed().as_millis(),
                    output: String::new(),
                    skipped: true,
                };
            }
            let mut output = String::new();
            let mut ok = true;
            for cmd in cmds {
                if let Err(excerpt) = run_command(cmd, &target.cwd) {
                    ok = false;
                    if !output.is_empty() {
                        output.push('\n');
                    }
                    let _ = write!(output, "[{cmd}] {excerpt}");
                }
            }
            SubprojectResult {
                name: target.name.clone(),
                ok,
                duration_ms: sub_started.elapsed().as_millis(),
                output,
                skipped: false,
            }
        })
        .collect();

    VerifyResult {
        per_subproject,
        total_duration_ms: started.elapsed().as_millis(),
        timestamp,
    }
}

/// Write the standalone HTML report. Uses the W10.T10.1 shape.
///
/// `verify-pipeline` is workspace-wide (not per-spec); the W2 cache reorg
/// keeps the report under `<root>/.claude/.metrics/reports/`.
fn write_html_report(cwd: &Path, result: &VerifyResult) -> Option<PathBuf> {
    let paths = ClaudePaths::for_project(cwd).ok()?;
    let dir = paths.metrics_dir().join("reports");
    fs::create_dir_all(&dir).ok()?;
    let passed = result.per_subproject.iter().filter(|r| r.ok && !r.skipped).count();
    let failed = result.per_subproject.iter().filter(|r| !r.ok && !r.skipped).count();
    let skipped = result.per_subproject.iter().filter(|r| r.skipped).count();
    let mut report = Report::new(
        "Pipeline Verification",
        format!("{passed} passed · {failed} failed · {skipped} skipped"),
    );
    let mut rows: Vec<Vec<String>> = Vec::new();
    for r in &result.per_subproject {
        let status = if r.skipped {
            "SKIP"
        } else if r.ok {
            "PASS"
        } else {
            "FAIL"
        };
        let detail: String = if r.skipped || r.ok {
            String::new()
        } else {
            r.output.chars().take(120).collect()
        };
        rows.push(vec![r.name.clone(), status.to_string(), detail]);
    }
    report.section("Targets", &table(&["Target", "Status", "Detail"], &rows));
    let path = dir.join("verify-pipeline.html");
    fs::write_atomic(&path, report.render().as_bytes()).ok()?;
    Some(path)
}

/// Emit `pipeline.economy.operation.invoked` for one verify run.
fn emit_economy(duration_ms: u128, subproject_count: usize, any_failure: bool) {
    let cwd = std::env::current_dir()
        .ok()
        .and_then(|p| p.to_str().map(str::to_string))
        .unwrap_or_else(|| ".".to_string());
    let spec = current_spec(&cwd);
    let duration_capped = i64::try_from(duration_ms).unwrap_or(i64::MAX);
    let ev = HarnessEvent {
        v: SCHEMA_VERSION,
        ts: now_iso8601(),
        session_id: session_id(),
        wave: 0,
        actor: Actor {
            kind: ActorKind::Orchestrator,
            id: Some("verify-pipeline".to_string()),
            actor_type: None,
        },
        event: "pipeline.economy.operation.invoked".to_string(),
        payload: json!({
            "operation": "verify-pipeline",
            "duration_ms": duration_capped,
            "tokens_used": 0,
            "was_rust_only": true,
            "subprojects": subproject_count,
            "ok": !any_failure,
        }),
        spec,
    };
    let _ = crate::run::event_route::emit(&cwd, &ev);
}

/// Dispatch `mustard-rt run verify-pipeline`.
pub fn run(format: &str) {
    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let result = verify(&cwd);

    if format == "html" {
        match write_html_report(&cwd, &result) {
            Some(path) => eprintln!("[verify-pipeline] HTML report: {}", path.display()),
            None => eprintln!("[verify-pipeline] WARN: could not write HTML report"),
        }
    }

    println!(
        "{}",
        serde_json::to_string_pretty(&result.to_json()).unwrap_or_else(|_| "{}".to_string())
    );
    emit_economy(
        result.total_duration_ms,
        result.per_subproject.len(),
        result.any_failure(),
    );
    if result.any_failure() {
        std::process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn config_fallback_parses_build_column() {
        let dir = tempdir().unwrap();
        let paths = ClaudePaths::for_project(dir.path()).unwrap();
        let claude = paths.claude_dir();
        std::fs::create_dir_all(&claude).unwrap();
        std::fs::write(
            paths.pipeline_config_md_path(),
            "| Agent | Build Command |\n|-------|---------------|\n| api | `cargo build` |\n",
        )
        .unwrap();
        let targets = discover_via_config(dir.path());
        assert_eq!(targets.len(), 1);
        assert_eq!(targets[0].name, "api");
        assert_eq!(targets[0].build.as_deref(), Some("cargo build"));
    }

    #[test]
    fn verify_targets_empty_yields_empty_result() {
        // `verify_targets` is exercised directly — `verify()` would spawn
        // `current_exe() run sync-detect`, which under a test binary recurses.
        let result = verify_targets(&[]);
        assert!(result.per_subproject.is_empty());
        assert!(!result.any_failure());
        assert_eq!(result.timestamp.len(), 24);
    }

    #[test]
    fn verify_targets_skips_command_less_target() {
        let result = verify_targets(&[VerifyTarget {
            name: "doc".to_string(),
            cwd: std::env::temp_dir(),
            build: None,
            test: None,
        }]);
        assert_eq!(result.per_subproject.len(), 1);
        assert!(result.per_subproject[0].skipped);
        assert!(result.per_subproject[0].ok);
        assert_eq!(result.per_subproject[0].name, "doc");
    }

    #[test]
    fn verify_targets_json_shape_has_required_keys() {
        // AC-W10.1 — output shape must carry `overall` + `per_subproject`.
        let result = verify_targets(&[VerifyTarget {
            name: "doc".to_string(),
            cwd: std::env::temp_dir(),
            build: None,
            test: None,
        }]);
        let j = result.to_json();
        assert!(j.get("overall").is_some());
        assert!(j.get("per_subproject").is_some());
        assert!(j.get("total_duration_ms").is_some());
        assert_eq!(j["overall"].as_str(), Some("ok"));
    }

    #[test]
    fn html_report_is_standalone() {
        let dir = tempdir().unwrap();
        let result = VerifyResult {
            per_subproject: vec![
                SubprojectResult {
                    name: "api".into(),
                    ok: true,
                    duration_ms: 10,
                    output: String::new(),
                    skipped: false,
                },
                SubprojectResult {
                    name: "ui".into(),
                    ok: false,
                    duration_ms: 12,
                    output: "boom".into(),
                    skipped: false,
                },
            ],
            total_duration_ms: 22,
            timestamp: now_iso8601(),
        };
        let path = write_html_report(dir.path(), &result).unwrap();
        let html = std::fs::read_to_string(path).unwrap();
        assert!(html.starts_with("<!doctype html>"));
        assert!(!html.contains("href=") && !html.contains("src="));
        assert!(html.contains("api"));
    }

    #[test]
    fn stack_md_scripts_block_parsed() {
        let dir = tempdir().unwrap();
        let commands = ClaudePaths::for_project(dir.path()).unwrap().commands_dir();
        std::fs::create_dir_all(&commands).unwrap();
        std::fs::write(
            commands.join("stack.md"),
            "## Scripts\nbuild = \"cargo build\"\ntest = \"cargo test\"\n",
        )
        .unwrap();
        let (b, t) = scripts_from_stack_md(dir.path()).unwrap();
        assert_eq!(b.as_deref(), Some("cargo build"));
        assert_eq!(t.as_deref(), Some("cargo test"));
    }
}
