//! Build script — tell Cargo to recompile this crate when the release
//! workflow sets or changes `MUSTARD_RELEASE_VERSION`.
//!
//! `platform::harness::harness_version` reads that env via `option_env!`, which
//! the compiler evaluates at build time. Without this hint Cargo does not track
//! arbitrary env vars, so a cached artifact would keep a stale (or unset)
//! version even after the env changes. A clean release build is unaffected;
//! this makes incremental builds honest too.
//!
//! O script grava também a tabela das línguas da busca (`domain::normalize`),
//! lida da pasta dos arquivos de cada língua.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=MUSTARD_RELEASE_VERSION");
    languages();
}

/// A pasta das línguas da busca, a partir da raiz do pacote.
const LANGUAGES_DIR: &str = "src/domain/normalize/languages";

/// A tabela das línguas da busca, em `$OUT_DIR/languages.rs`: um par por
/// arquivo `<código>.txt` da pasta [`LANGUAGES_DIR`], em ordem de nome, com o
/// código da língua e o texto do arquivo embutido. A língua nova é um arquivo
/// a mais na pasta, sem linha de código.
fn languages() {
    let (Some(crate_root), Some(out_dir)) = (std::env::var_os("CARGO_MANIFEST_DIR"), std::env::var_os("OUT_DIR")) else {
        return;
    };
    println!("cargo:rerun-if-changed={LANGUAGES_DIR}");
    let dir = Path::new(&crate_root).join(LANGUAGES_DIR);
    let mut files: Vec<_> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("txt"))
        .collect();
    files.sort();
    let mut table =
        format!("// @generated by build.rs from {LANGUAGES_DIR}/*.txt — do not edit.\n&[\n");
    for file in files {
        let code = file.file_stem().and_then(|stem| stem.to_str()).expect("a language file has a name");
        writeln!(table, "    ({code:?}, include_str!({:?})),", file.display().to_string())
            .expect("writing to a String does not fail");
    }
    table.push_str("]\n");
    let out = Path::new(&out_dir).join("languages.rs");
    fs::write(&out, table).unwrap_or_else(|e| panic!("cannot write {}: {e}", out.display()));
}
