// AUTO-GENERATED by scripts/refactor-folder-per-component.mjs
// (Wave 4 of spec 2026-05-23-dashboard-design-system).
// Re-exports every component in this folder so callers can
// import either granular or aggregated.

export * from "./avatar";
export * from "./badge";
export * from "./button";
export * from "./card";
export * from "./command";
export * from "./dialog";
export * from "./dropdown-menu";
export * from "./input";
export * from "./input-group";
export * from "./scroll-area";
export * from "./separator";
export * from "./sheet";
export * from "./tabs";
export * from "./textarea";
export * from "./tooltip";
