// AUTO-GENERATED by scripts/refactor-folder-per-component.mjs
// (Wave 4 of spec 2026-05-23-dashboard-design-system).
// Re-exports every component in this folder so callers can
// import either granular or aggregated.

export * from "./KnowledgeBadge";
export * from "./KnowledgeCard";
