import type { ProjectInfo, Analysis, RegistryPatterns } from '../types.js';

/**
 * Generate CLAUDE.md using templates (fallback when Ollama is unavailable)
 */
export function generateClaudeMd(projectInfo: ProjectInfo, analysis: Analysis): string {
  const sections = [
    generateHeader(projectInfo),
    generateQuickReference(projectInfo),
    generateProjectState(projectInfo),
    generateDelegation(),
    generateCommands(projectInfo),
    generatePipeline(),
    generateEntityRegistry(projectInfo),
    generateGrepai(),
    generateRules(projectInfo, analysis),
    generateLinks()
  ];

  return sections.join('\n\n---\n\n');
}

function generateHeader(projectInfo: ProjectInfo): string {
  return `# ${projectInfo.name} - Instructions for Claude

> Auto-generated by **Mustard CLI v2.0**

Type: **${projectInfo.type}**
Package Manager: **${projectInfo.packageManager ?? 'npm'}**`;
}

function generateQuickReference(projectInfo: ProjectInfo): string {
  const patterns = projectInfo.patterns;

  return `## 1. Quick Reference

\`\`\`
Entities:     PascalCase singular     → Contract, Person, Company
DB Tables:    snake_case plural       → contracts, people, companies
Endpoints:    /api/kebab-case         → /api/contracts, /api/people
Components:   PascalCase.tsx          → ContractForm.tsx
Hooks:        use + camelCase         → useContracts.ts
\`\`\`

### Detected Conventions

| Type | Pattern |
|------|---------|
| Classes | ${patterns?.classes ?? 'PascalCase'} |
| Files | ${typeof patterns?.files === 'object' ? JSON.stringify(patterns.files) : (patterns?.files ?? 'varies')} |
| Folders | ${patterns?.folders ?? 'plural'} |`;
}

function generateProjectState(projectInfo: ProjectInfo): string {
  const rows = projectInfo.stacks.map(s => {
    const tech = s.name + (s.version ? ` ${s.version}` : '');
    return `| ${s.path} | ${tech} | - | ✅ Detected |`;
  }).join('\n');

  return `## 2. Project State

| Project | Technology | Port | Status |
|---------|------------|------|--------|
${rows}`;
}

function generateDelegation(): string {
  return `## 3. DELEGATION VIA TASK TOOL

> 💡 **RECOMMENDED:** Use Task tool to delegate tasks to specialized agents.

### Available Agents

| Agent | Usage | Model |
|-------|-------|-------|
| \`Explore\` | Explore codebase, find files | haiku |
| \`Plan\` | Plan complex implementations | sonnet |
| \`general-purpose\` | Implement code, bug fixes | opus/sonnet |
| \`Bash\` | Execute terminal commands | - |

### Delegation Map

| Request | Agent | Model |
|---------|-------|-------|
| Bug fix | \`general-purpose\` | opus |
| New feature | \`Plan\` → \`general-purpose\` | sonnet/opus |
| Explore code | \`Explore\` | haiku |
| Backend/Frontend/DB | \`general-purpose\` | opus |`;
}

function generateCommands(projectInfo: ProjectInfo): string {
  // Detect appropriate commands based on stack
  const hasNode = projectInfo.stacks.some(s => ['react', 'nextjs', 'node'].includes(s.name));
  const hasDotnet = projectInfo.stacks.some(s => s.name === 'dotnet');
  const hasPython = projectInfo.stacks.some(s => s.name === 'python');

  let runCmd = 'npm run dev';
  if (hasNode) runCmd = `${projectInfo.packageManager ?? 'npm'} run dev`;
  if (hasDotnet) runCmd = 'dotnet run';
  if (hasPython) runCmd = 'python main.py';

  return `## 4. Available Commands

> **Note:** Mustard commands use the \`mtd-{category}-{action}\` pattern.
> They are in \`commands/mustard/\`. Create your own in \`commands/\` - preserved on updates.

### Pipeline

| Command | Description |
|---------|-------------|
| \`/mtd-pipeline-feature <name>\` | **Single entry point for features** - Starts full pipeline |
| \`/mtd-pipeline-bugfix <error>\` | **Single entry point for bugs** - Diagnosis + fix |
| \`/mtd-pipeline-approve\` | Approve spec and start implementation |
| \`/mtd-pipeline-complete\` | Finalize pipeline |
| \`/mtd-pipeline-resume\` | Resume active pipeline |

### Git

| Command | Description |
|---------|-------------|
| \`/mtd-git-commit\` | Simple commit |
| \`/mtd-git-push\` | Commit and push |
| \`/mtd-git-merge\` | Merge to main |

### Validate

| Command | Description |
|---------|-------------|
| \`/mtd-validate-build\` | Build + type-check |
| \`/mtd-validate-status\` | Consolidated status |

### Sync

| Command | Description |
|---------|-------------|
| \`/mtd-sync-registry\` | Update Entity Registry |
| \`/mtd-sync-dependencies\` | Install dependencies |
| \`/mtd-sync-context\` | Load project context |

### Report

| Command | Description |
|---------|-------------|
| \`/mtd-report-daily\` | Daily progress report |
| \`/mtd-report-weekly\` | Weekly progress report |

### Scan

| Command | Description |
|---------|-------------|
| \`/mtd-scan-project\` | Scan project structure |`;
}

function generatePipeline(): string {
  return `## 5. Single Pipeline

\`\`\`
/mtd-pipeline-feature or /mtd-pipeline-bugfix
         │
         ▼
    EXPLORE (Task Explore)
         │
         ▼
      SPEC (spec/active/{name}/spec.md)
         │
    ┌────┴────┐
    ▼         ▼
[APPROVED]  [ITERATE]
    │         │
    ▼    (back)
IMPLEMENT (Task general-purpose)
    │
    ▼
  REVIEW
    │
    ▼
COMPLETED
\`\`\``;
}

function generateEntityRegistry(projectInfo: ProjectInfo): string {
  // Build patterns based on detected structure
  const patterns: RegistryPatterns = {};

  const hasDrizzle = projectInfo.stacks.some(s => s.name === 'drizzle');
  const hasDotnet = projectInfo.stacks.some(s => s.name === 'dotnet');
  const hasReact = projectInfo.stacks.some(s => ['react', 'nextjs'].includes(s.name));

  if (hasDrizzle) {
    const dbPath = projectInfo.stacks.find(s => s.name === 'drizzle')?.path ?? 'database';
    patterns.db = `${dbPath}/schema/{e}.ts`;
  }

  if (hasDotnet) {
    const bePath = projectInfo.stacks.find(s => s.name === 'dotnet')?.path ?? 'backend';
    patterns.be = `${bePath}/Modules/{E}/`;
  }

  if (hasReact) {
    const fePath = projectInfo.stacks.find(s => ['react', 'nextjs'].includes(s.name))?.path ?? 'frontend';
    patterns.fe = `${fePath}/src/features/{e}/`;
  }

  return `## 6. Entity Registry (REQUIRED)

**CRITICAL RULE**: Before searching for ANY entity files,
ALWAYS read \`.claude/entity-registry.json\` first.

### Format

\`\`\`json
{
  "_meta": { "version": "2.1" },
  "_p": ${JSON.stringify(patterns, null, 4)},
  "e": {
    "Entity1": 1,
    "Entity2": 1
  }
}
\`\`\`

Paths are derived from \`_p\` (patterns) + entity name.`;
}

function generateGrepai(): string {
  return `## 7. grepai - Semantic Search

Use grepai as the preferred tool for code search:

\`\`\`javascript
// Semantic search
grepai_search({ query: "authentication flow" })

// Call tracing
grepai_trace_callers({ symbol: "SaveContract" })
grepai_trace_callees({ symbol: "ValidatePayment" })
\`\`\`

### Search Rules

| Tool | Recommendation |
|------|----------------|
| \`grepai_search\` | ✅ Prefer for semantic search |
| \`grepai_trace_*\` | ✅ Use to understand dependencies |
| \`Grep\` | ⚠️ Use only if grepai is unavailable |
| \`Glob\` | ⚠️ Use for specific file patterns |`;
}

function generateRules(projectInfo: ProjectInfo, analysis: Analysis): string {
  const rules = analysis.rules ?? [];

  const rulesText = rules.length > 0
    ? rules.map(r => `- ${r}`).join('\n')
    : `- Follow project naming conventions
- Use dependency injection
- Keep code testable and modular
- Document public APIs`;

  return `## 8. Rules

### Enforcement Rules

| Level | Rule | Description |
|-------|------|-------------|
| L0 | Delegation | Main Claude does NOT implement code |
| L1 | grepai | Prefer grepai for semantic search |
| L2 | Pipeline | Pipeline required for features/bugs |
| L3 | Patterns | Follow naming conventions |

### Project Rules

${rulesText}`;
}

function generateLinks(): string {
  return `## 9. Links

### Core
- [Enforcement](./core/enforcement.md)
- [Naming Conventions](./core/naming-conventions.md)
- [Pipeline](./core/pipeline.md)

### Commands
- [Mustard Commands](./commands/mustard/) - Core commands (managed by Mustard)
- [User Commands](./commands/) - Custom commands (preserved on updates)

### Prompts
- [Prompts Index](./prompts/_index.md)

### Hooks
- [enforce-pipeline.js](./hooks/enforce-pipeline.js)`;
}
