import type { ProjectInfo, GeneratedCommands } from '../types.js';

/**
 * Mustard commands subfolder
 * Commands generated by Mustard go in commands/mustard/
 * User-created commands go directly in commands/
 */
export const MUSTARD_COMMANDS_FOLDER = 'mustard';

/**
 * Command prefix for Mustard commands
 */
export const MUSTARD_COMMAND_PREFIX = 'mtd';

/**
 * Generate command files
 * All generated commands go in the mustard/ subfolder
 * Pattern: mtd-{category}-{action}
 */
export function generateCommands(projectInfo: ProjectInfo): GeneratedCommands {
  const commands: GeneratedCommands = {
    // Pipeline commands
    'mtd-pipeline-feature': generatePipelineFeatureCommand(projectInfo),
    'mtd-pipeline-bugfix': generatePipelineBugfixCommand(projectInfo),
    'mtd-pipeline-approve': generatePipelineApproveCommand(),
    'mtd-pipeline-complete': generatePipelineCompleteCommand(),
    'mtd-pipeline-resume': generatePipelineResumeCommand(),

    // Git commands
    'mtd-git-commit': generateGitCommitCommand(),
    'mtd-git-push': generateGitPushCommand(),
    'mtd-git-merge': generateGitMergeCommand(),

    // Validate commands
    'mtd-validate-build': generateValidateBuildCommand(projectInfo),
    'mtd-validate-status': generateValidateStatusCommand(projectInfo),

    // Sync commands
    'mtd-sync-registry': generateSyncRegistryCommand(),
    'mtd-sync-dependencies': generateSyncDependenciesCommand(projectInfo),
    'mtd-sync-context': generateSyncContextCommand(),

    // Report commands
    'mtd-report-daily': generateReportDailyCommand(),
    'mtd-report-weekly': generateReportWeeklyCommand(),

    // Scan commands
    'mtd-scan-project': generateScanProjectCommand()
  };

  return commands;
}

// ============== Pipeline Commands ==============

function generatePipelineFeatureCommand(projectInfo: ProjectInfo): string {
  return `# /mtd-pipeline-feature - Feature Pipeline

## Trigger

\`/mtd-pipeline-feature <feature-name>\`

## Description

Starts the full pipeline to implement a new feature.

## Flow

1. **EXPLORE**
   - Use Task(Explore) to analyze requirements
   - Map related existing files
   - Identify patterns to follow

2. **SPEC**
   - Create spec at \`spec/active/{name}/spec.md\`
   - List files to create/modify
   - Define implementation checklist

3. **APPROVE**
   - Present spec to user
   - Wait for /mtd-pipeline-approve or feedback

4. **IMPLEMENT**
   - Delegate to specialized agents
   - Backend → Frontend → Database (order as needed)

5. **REVIEW**
   - Validate implementation
   - Verify checklist

6. **COMPLETE**
   - Update entity-registry if needed
   - Move spec to completed/

## Example

\`\`\`
User: /mtd-pipeline-feature add-partner-email-field

Claude:
1. Explores codebase to understand Partner
2. Creates spec with implementation plan
3. Presents spec for approval
4. (after /mtd-pipeline-approve) Implements Database → Backend → Frontend
5. Validates and completes
\`\`\`
`;
}

function generatePipelineBugfixCommand(projectInfo: ProjectInfo): string {
  return `# /mtd-pipeline-bugfix - Bug Fix Pipeline

## Trigger

\`/mtd-pipeline-bugfix <error-description>\`

## Description

Starts the pipeline to diagnose and fix a bug.

## Flow

1. **DIAGNOSE**
   - Use grepai to search related code
   - Identify root cause
   - Document findings

2. **SPEC**
   - Create spec at \`spec/active/{name}/spec.md\`
   - Describe root cause
   - Propose fix

3. **APPROVE**
   - Present diagnosis to user
   - Wait for /mtd-pipeline-approve

4. **FIX**
   - Apply minimal fix
   - Do not make unrelated changes

5. **VALIDATE**
   - Verify bug is fixed
   - Verify nothing broke

6. **COMPLETE**
   - Document solution
   - Move spec to completed/

## Example

\`\`\`
User: /mtd-pipeline-bugfix error saving contract

Claude:
1. Uses grepai to find save code
2. Identifies root cause
3. Presents diagnosis
4. (after /mtd-pipeline-approve) Fixes
5. Validates and completes
\`\`\`
`;
}

function generatePipelineApproveCommand(): string {
  return `# /mtd-pipeline-approve - Approve Spec

## Trigger

\`/mtd-pipeline-approve\`

## Description

Approves the current spec and enables the implementation phase.

## Prerequisites

- Active pipeline (created via /mtd-pipeline-feature or /mtd-pipeline-bugfix)
- Spec presented awaiting approval

## Action

1. Marks pipeline as "approved"
2. Enables implementation start
3. Claude proceeds automatically

## Alternative Flow

If the spec is not satisfactory, the user can:
- Give text feedback for adjustments
- Use /mtd-pipeline-complete to cancel

\`\`\`
User: /mtd-pipeline-approve

Claude: ✅ Spec approved! Starting implementation...
\`\`\`
`;
}

function generatePipelineCompleteCommand(): string {
  return `# /mtd-pipeline-complete - Finalize Pipeline

## Trigger

\`/mtd-pipeline-complete\`

## Description

Finalizes the current pipeline, either completing or canceling.

## Action

1. Moves spec from \`spec/active/\` to \`spec/completed/\`
2. Updates entity-registry if needed
3. Clears pipeline state

## When to Use

- After successful implementation and review
- To cancel an ongoing pipeline
- To force close if something went wrong

\`\`\`
User: /mtd-pipeline-complete

Claude: ✅ Pipeline finalized!
        Spec moved to spec/completed/{name}/
        Entity registry updated.
\`\`\`
`;
}

function generatePipelineResumeCommand(): string {
  return `# /mtd-pipeline-resume - Resume Pipeline

## Trigger

\`/mtd-pipeline-resume\`

## Description

Resumes a pipeline that was interrupted.

## Action

1. Finds active pipeline
2. Identifies last completed phase
3. Continues from where it stopped

## When to Use

- After restarting Claude session
- After accidental interruption
- To continue work from another session

\`\`\`
User: /mtd-pipeline-resume

Claude: 🔄 Resuming pipeline "add-email-partner"
        Last phase: IMPLEMENT
        Continuing with Backend...
\`\`\`
`;
}

// ============== Git Commands ==============

function generateGitCommitCommand(): string {
  return `# /mtd-git-commit - Simple Commit

## Trigger

\`/mtd-git-commit\`

## Description

Creates a commit with current changes.

## Action

1. Runs \`git status\` to see changes
2. Runs \`git diff\` to analyze content
3. Generates commit message based on changes
4. Runs \`git add\` + \`git commit\`

## Message Format

\`\`\`
<type>: <short description>

<detailed description if needed>

Co-Authored-By: Claude <noreply@anthropic.com>
\`\`\`

Types: feat, fix, refactor, docs, chore, test
`;
}

function generateGitPushCommand(): string {
  return `# /mtd-git-push - Commit and Push

## Trigger

\`/mtd-git-push\`

## Description

Creates commit and pushes to remote.

## Action

1. Same process as /mtd-git-commit
2. Adds \`git push\` at the end

## Cautions

- Checks if branch has remote configured
- Uses \`git push -u origin <branch>\` if needed
`;
}

function generateGitMergeCommand(): string {
  return `# /mtd-git-merge - Merge to Main

## Trigger

\`/mtd-git-merge\`

## Description

Merges current branch to main/master.

## Action

1. Checks for uncommitted changes
2. Switches to main branch
3. Pulls latest changes
4. Merges feature branch
5. Pushes to remote

## Cautions

- Will abort if there are merge conflicts
- Requires clean working directory
`;
}

// ============== Validate Commands ==============

function generateValidateBuildCommand(projectInfo: ProjectInfo): string {
  const hasNode = projectInfo.stacks.some(s => ['react', 'nextjs', 'node'].includes(s.name));
  const hasDotnet = projectInfo.stacks.some(s => s.name === 'dotnet');
  const pm = projectInfo.packageManager ?? 'npm';

  const steps: string[] = [];

  if (hasDotnet) {
    steps.push('- `dotnet build` - Verifies .NET compiles');
  }

  if (hasNode) {
    steps.push(`- \`${pm} run typecheck\` - Verifies TypeScript types`);
    steps.push(`- \`${pm} run lint\` - Verifies linting (if available)`);
  }

  return `# /mtd-validate-build - Build Validation

## Trigger

\`/mtd-validate-build\`

## Description

Runs build and type-check validations.

## Actions

${steps.join('\n') || '- Verify project compilation'}

## Result

- ✅ **Success** - Project compiles and passes type-check
- ❌ **Failure** - Lists errors found
`;
}

function generateValidateStatusCommand(projectInfo: ProjectInfo): string {
  return `# /mtd-validate-status - Consolidated Status

## Trigger

\`/mtd-validate-status\`

## Description

Shows consolidated project status.

## Information

1. **Git Status**
   - Current branch
   - Modified files
   - Commits pending push

2. **Pipeline**
   - Active pipeline (if any)
   - Current phase

3. **Build**
   - Last validation result

4. **Entity Registry**
   - Number of entities
   - Last update
`;
}

// ============== Sync Commands ==============

function generateSyncRegistryCommand(): string {
  return `# /mtd-sync-registry - Update Entity Registry

## Trigger

\`/mtd-sync-registry\`

## Description

Scans the project and updates entity-registry.json.

## Action

1. Searches database schemas (Drizzle, Prisma, etc)
2. Searches backend entities (.NET, Node, etc)
3. Updates \`.claude/entity-registry.json\`

## When to Use

- After creating new entity
- After importing existing code
- To sync after manual changes
`;
}

function generateSyncDependenciesCommand(projectInfo: ProjectInfo): string {
  const pm = projectInfo.packageManager ?? 'npm';
  const hasDotnet = projectInfo.stacks.some(s => s.name === 'dotnet');

  return `# /mtd-sync-dependencies - Install Dependencies

## Trigger

\`/mtd-sync-dependencies\`

## Description

Installs dependencies for all projects.

## Actions

${hasDotnet ? '- `dotnet restore` - Restores NuGet packages\n' : ''}- \`${pm} install\` - Installs Node dependencies

## Subprojects

If monorepo, runs in all configured subprojects.
`;
}

function generateSyncContextCommand(): string {
  return `# /mtd-sync-context - Load Project Context

## Trigger

\`/mtd-sync-context\`
\`/mtd-sync-context --refresh\`

## Description

Discovers and caches project context for faster implementations.

## What It Does

1. Reads \`.claude/context/*.md\` for user-provided context
2. Reads \`.claude/CLAUDE.md\` for project rules and conventions
3. Reads \`.claude/entity-registry.json\` for entity mappings
4. Uses grepai to discover code patterns (services, repos, components)
5. Stores all in memory MCP as entities

## When It Runs

- **Automatically** at the start of /mtd-pipeline-feature or /mtd-pipeline-bugfix (if context is missing or stale)
- **Manually** when you run /mtd-sync-context
- **Force refresh** with /mtd-sync-context --refresh

## Context Sources

| Source | Entity Type | Content |
|--------|-------------|---------|
| \`.claude/context/*.md\` | \`UserContext:*\` | User-provided specs, tips, examples |
| \`.claude/CLAUDE.md\` | \`ProjectContext\` | Stacks, naming, conventions |
| \`.claude/entity-registry.json\` | \`EntityRegistry\` | Entity mappings |
| \`.claude/core/enforcement.md\` | \`EnforcementRules\` | L0-L9 rules |
| grepai discovery | \`CodePattern:*\` | Services, repos, components |

## Output

\`\`\`
✅ Context loaded successfully

Project Context:
- Type: monorepo
- Stacks: dotnet:9.0, react:19.x

User Context (3 files):
- architecture.md
- business-rules.md
- tips.md

Code Patterns:
- service (Backend/Services/ContractService.cs)
- repository (Backend/Repositories/ContractRepository.cs)
\`\`\`

## Context Refresh Strategy

| Trigger | Action |
|---------|--------|
| Context > 24h old | Auto-refresh on /mtd-pipeline-feature or /mtd-pipeline-bugfix |
| \`/mtd-sync-context --refresh\` | Force full refresh |
| \`/mtd-sync-registry\` | Refresh only EntityRegistry |

## See Also

- [context/README.md](../context/README.md) - How to create context files
- [/mtd-pipeline-feature](./mtd-pipeline-feature.md) - Feature pipeline (auto-loads context)
- [/mtd-pipeline-bugfix](./mtd-pipeline-bugfix.md) - Bugfix pipeline (auto-loads context)
`;
}

// ============== Report Commands ==============

function generateReportDailyCommand(): string {
  return `# /mtd-report-daily - Daily Report

## Trigger

\`/mtd-report-daily\`

## Description

Generates a daily progress report.

## Content

1. **Commits Today**
   - List of commits made
   - Files changed

2. **Pipeline Activity**
   - Features started/completed
   - Bugs fixed

3. **Pending Items**
   - Open pipelines
   - Uncommitted changes

## Output Format

Markdown report suitable for sharing or documentation.
`;
}

function generateReportWeeklyCommand(): string {
  return `# /mtd-report-weekly - Weekly Report

## Trigger

\`/mtd-report-weekly\`

## Description

Generates a weekly progress report.

## Content

1. **Week Summary**
   - Total commits
   - Features completed
   - Bugs fixed

2. **Entity Changes**
   - New entities created
   - Entities modified

3. **Code Metrics**
   - Lines added/removed
   - Files changed

## Output Format

Markdown report suitable for team updates.
`;
}

// ============== Scan Commands ==============

function generateScanProjectCommand(): string {
  return `# /mtd-scan-project - Scan Project

## Trigger

\`/mtd-scan-project\`

## Description

Scans the project structure and updates detection.

## Action

1. Detects technology stacks
2. Maps folder structure
3. Identifies naming conventions
4. Updates project state

## When to Use

- After major structural changes
- When adding new technology
- To refresh project detection
`;
}
