//! Build script: turn the external language registry (languages.toml) and the
//! external query files (queries/<dir>/*.scm) into one generated Rust file in
//! OUT_DIR. This is where — and the ONLY where — grammar crate symbols and
//! language names are referenced. The crate's own `src/` therefore contains no
//! language identifier, extension, or grammar node name: adding a language is a
//! data change (a languages.toml row + .scm files), never a logic change.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let registry_path = Path::new(&manifest).join("languages.toml");
    let queries_root = Path::new(&manifest).join("queries");

    println!("cargo:rerun-if-changed=languages.toml");
    println!("cargo:rerun-if-changed=queries");
    println!("cargo:rerun-if-changed=src");

    // The map format: a digest of everything that decides what the scan
    // yields from a file — the engine (src), the queries, and the data tables
    // at the crate root. A map written by a scan built from other sources is
    // read again in full, so no change to the scan can leave a stale map
    // behind, and nobody has to remember to bump a number by hand.
    println!("cargo:rustc-env=SCAN_MAP_DIGEST={}", source_digest(Path::new(&manifest)));

    let registry_src = fs::read_to_string(&registry_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", registry_path.display()));
    // toml 1.x: `str::parse::<Value>` parses a lone TOML *value*, not a
    // document — document parsing goes through the serde path (`from_str`).
    let registry: toml::Value = toml::from_str(&registry_src)
        .unwrap_or_else(|e| panic!("languages.toml is not valid TOML: {e}"));

    let languages = registry
        .get("language")
        .and_then(|v| v.as_array())
        .expect("languages.toml must contain a [[language]] array");

    let mut body = String::new();
    body.push_str("// @generated by build.rs from languages.toml + queries/*.scm — do not edit.\n");
    body.push_str("pub(crate) fn raw_langs() -> Vec<RawLang> {\n    vec![\n");

    // A lightweight (name, extensions) table for detection — built without
    // constructing any grammar, so per-file language detection stays cheap.
    let mut ext_table = String::new();
    ext_table.push_str("pub(crate) static LANG_EXTENSIONS: &[(&str, &[&str])] = &[\n");

    // (name, root_aliases) table — the OPTIONAL per-language import segments
    // that alias the package root (e.g. Rust's `crate`/`self`). The
    // graph's root-alias resolution branch only runs for imports whose first
    // segment is declared here; a language without the field gets an empty
    // slice and never takes that branch.
    let mut alias_table = String::new();
    alias_table.push_str("pub(crate) static LANG_ROOT_ALIASES: &[(&str, &[&str])] = &[\n");

    // (name, namespace_scope) table — the OPTIONAL rule for how a declared
    // namespace is seen by the other files of the language ("folder" or
    // "nested"). A language without the field gets an empty string: a
    // namespace is seen only by the files that declare the same one.
    let mut scope_table = String::new();
    scope_table.push_str("pub(crate) static LANG_NAMESPACE_SCOPE: &[(&str, &str)] = &[\n");

    // (name, import_extensions) — as extensões OPCIONAIS que o import da
    // língua escreve no lugar da do próprio arquivo. Sem o campo, lista vazia:
    // o caminho importado só perde a extensão quando ela é da própria língua.
    let mut import_ext_table = String::new();
    import_ext_table.push_str("pub(crate) static LANG_IMPORT_EXTENSIONS: &[(&str, &[&str])] = &[\n");

    // (name, alias_config), (name, alias_base), (name, alias_paths) e
    // (name, alias_extends) — o arquivo de configuração OPCIONAL dos apelidos
    // de pasta e as três chaves lidas nele. Sem o campo, texto vazio: a
    // língua não tem apelido de pasta e a leitura nem começa.
    // (name, separator, package_file) — o import relativo OPCIONAL que a
    // língua escreve com um separador no lugar da barra, e o arquivo que
    // responde pela pasta. Sem o campo, dois textos vazios: o import da
    // língua nunca é lido assim.
    let mut relative_table = String::new();
    relative_table.push_str("pub(crate) static LANG_RELATIVE_IMPORT: &[(&str, &str, &str)] = &[\n");

    // (name, qualified_separators) — os textos OPCIONAIS que juntam as partes
    // de um nome qualificado na língua. Sem o campo, lista vazia: o motor usa
    // os separadores de sempre.
    let mut separators_table = String::new();
    separators_table.push_str("pub(crate) static LANG_QUALIFIED_SEPARATORS: &[(&str, &[&str])] = &[\n");

    // (name, parent_alias) — o nome OPCIONAL que, no começo de um caminho
    // qualificado, sobe um módulo. Sem o campo, texto vazio: nenhum caminho
    // da língua é lido assim.
    let mut parent_table = String::new();
    parent_table.push_str("pub(crate) static LANG_PARENT_ALIAS: &[(&str, &str)] = &[\n");

    // (name, member_separators) e (name, self_receivers) — os textos
    // OPCIONAIS que ligam o método ao valor antes dele sem juntar caminho, e
    // os nomes que são o próprio objeto. Sem o campo, lista vazia.
    let mut member_table = String::new();
    member_table.push_str("pub(crate) static LANG_MEMBER_SEPARATORS: &[(&str, &[&str])] = &[\n");
    let mut self_table = String::new();
    self_table.push_str("pub(crate) static LANG_SELF_RECEIVERS: &[(&str, &[&str])] = &[\n");

    // (name, implicit_self) — se o nome sozinho alcança um membro do próprio
    // objeto. OPCIONAL: sem o campo, `false`.
    let mut implicit_table = String::new();
    implicit_table.push_str("pub(crate) static LANG_IMPLICIT_SELF: &[(&str, bool)] = &[\n");

    // (name, import_self) — o nome OPCIONAL que, trazido por um import, traz
    // o último nome escrito antes da lista que o contém. Sem o campo, texto
    // vazio: todo nome trazido é ele mesmo.
    let mut import_self_table = String::new();
    import_self_table.push_str("pub(crate) static LANG_IMPORT_SELF: &[(&str, &str)] = &[\n");

    // (name, prelude), (name, log_calls) e (name, error_forms) — os nomes
    // OPCIONAIS que todo arquivo vê sem import, as chamadas que escrevem log
    // e as formas que lançam ou devolvem erro. Sem o campo, lista vazia.
    let list_fields = ["prelude", "log_calls", "error_forms"];
    let mut list_field_tables: Vec<String> = list_fields
        .iter()
        .map(|field| format!("pub(crate) static LANG_{}: &[(&str, &[&str])] = &[\n", field.to_ascii_uppercase()))
        .collect();

    // (name, dir) — a família da língua: as que leem as mesmas consultas
    // (`dir`) são a mesma língua escrita em arquivos diferentes, e uma chamada
    // alcança as declarações da família inteira.
    let mut family_table = String::new();
    family_table.push_str("pub(crate) static LANG_FAMILY: &[(&str, &str)] = &[\n");

    let alias_fields = ["alias_config", "alias_base", "alias_paths", "alias_extends"];
    let mut alias_field_tables: Vec<String> = alias_fields
        .iter()
        .map(|field| format!("pub(crate) static LANG_{}: &[(&str, &str)] = &[\n", field.to_ascii_uppercase()))
        .collect();

    for lang in languages {
        let tbl = lang.as_table().expect("each [[language]] must be a table");
        let name = str_field(tbl, "name");
        let dir = str_field(tbl, "dir");
        let grammar = str_field(tbl, "grammar");
        let extensions: Vec<String> = tbl
            .get("extensions")
            .and_then(|v| v.as_array())
            .expect("language.extensions must be an array")
            .iter()
            .map(|e| e.as_str().expect("extension must be a string").to_string())
            .collect();
        let root_aliases: Vec<String> = tbl
            .get("root_aliases")
            .map(|v| {
                v.as_array()
                    .expect("language.root_aliases must be an array")
                    .iter()
                    .map(|e| e.as_str().expect("root alias must be a string").to_string())
                    .collect()
            })
            .unwrap_or_default();
        // The OPTIONAL markup tags the language writes its documentation
        // comments with: the engine drops them and keeps the text.
        let doc_tags: Vec<String> = tbl
            .get("doc_tags")
            .map(|v| {
                v.as_array()
                    .expect("language.doc_tags must be an array")
                    .iter()
                    .map(|e| e.as_str().expect("doc tag must be a string").to_string())
                    .collect()
            })
            .unwrap_or_default();
        let import_extensions: Vec<String> = tbl
            .get("import_extensions")
            .map(|v| {
                v.as_array()
                    .expect("language.import_extensions must be an array")
                    .iter()
                    .map(|e| e.as_str().expect("import extension must be a string").to_string())
                    .collect()
            })
            .unwrap_or_default();
        let alias_values: Vec<String> = alias_fields
            .iter()
            .map(|field| {
                tbl.get(*field)
                    .map(|v| v.as_str().unwrap_or_else(|| panic!("language.{field} must be a string")).to_string())
                    .unwrap_or_default()
            })
            .collect();
        let (separator, package_file) = tbl.get("relative_import").map_or((String::new(), String::new()), |v| {
            let rule = v.as_table().expect("language.relative_import must be a table");
            let text = |key: &str| {
                rule.get(key)
                    .map(|v| v.as_str().unwrap_or_else(|| panic!("language.relative_import.{key} must be a string")).to_string())
                    .unwrap_or_default()
            };
            let separator = text("separator");
            assert!(!separator.is_empty(), "language.relative_import of `{name}` must declare a non-empty separator");
            (separator, text("package_file"))
        });
        let qualified_separators: Vec<String> = tbl
            .get("qualified_separators")
            .map(|v| {
                v.as_array()
                    .expect("language.qualified_separators must be an array")
                    .iter()
                    .map(|e| e.as_str().expect("qualified separator must be a string").to_string())
                    .collect()
            })
            .unwrap_or_default();
        // A lista vazia na tabela quer dizer "sem o campo": declarada, ela
        // precisa de ao menos um separador, e nenhum deles vazio.
        assert!(
            tbl.get("qualified_separators").is_none()
                || (!qualified_separators.is_empty() && qualified_separators.iter().all(|s| !s.is_empty())),
            "language.qualified_separators of `{name}` must list at least one non-empty separator"
        );
        let member_separators = str_list(tbl, "member_separators");
        let self_receivers = str_list(tbl, "self_receivers");
        let implicit_self = tbl
            .get("implicit_self")
            .map(|v| v.as_bool().expect("language.implicit_self must be true or false"))
            .unwrap_or(false);
        let parent_alias = tbl
            .get("parent_alias")
            .map(|v| v.as_str().expect("language.parent_alias must be a string").to_string())
            .unwrap_or_default();
        // O texto vazio na tabela quer dizer "sem o campo": declarado, ele
        // não pode ser vazio.
        assert!(
            tbl.get("parent_alias").is_none() || !parent_alias.is_empty(),
            "language.parent_alias of `{name}` must not be empty"
        );
        let import_self = tbl
            .get("import_self")
            .map(|v| v.as_str().expect("language.import_self must be a string").to_string())
            .unwrap_or_default();
        assert!(
            tbl.get("import_self").is_none() || !import_self.is_empty(),
            "language.import_self of `{name}` must not be empty"
        );
        let list_values: Vec<Vec<String>> = list_fields.iter().map(|field| str_list(tbl, field)).collect();
        let namespace_scope = tbl
            .get("namespace_scope")
            .map(|v| v.as_str().expect("language.namespace_scope must be a string").to_string())
            .unwrap_or_default();
        assert!(
            matches!(namespace_scope.as_str(), "" | "folder" | "nested"),
            "language.namespace_scope of `{name}` must be \"folder\" or \"nested\", not {namespace_scope:?}"
        );

        // Concatenate every .scm under queries/<dir>/, in stable filename order.
        let query = read_queries(Path::new(&manifest), &queries_root, &dir);

        let exts = extensions
            .iter()
            .map(|e| format!("{e:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        let aliases = root_aliases
            .iter()
            .map(|a| format!("{a:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        let tags = doc_tags.iter().map(|t| format!("{t:?}")).collect::<Vec<_>>().join(", ");
        let import_exts = import_extensions.iter().map(|e| format!("{e:?}")).collect::<Vec<_>>().join(", ");
        let separators = qualified_separators.iter().map(|s| format!("{s:?}")).collect::<Vec<_>>().join(", ");

        writeln!(
            body,
            "        RawLang {{ name: {name:?}, query: {query:?}, language: {grammar}.into(), doc_tags: &[{tags}] }},"
        )
        .expect("the generated body is a String, which never fails to write");
        writeln!(ext_table, "    ({name:?}, &[{exts}]),").expect("the generated table is a String, which never fails to write");
        writeln!(alias_table, "    ({name:?}, &[{aliases}]),").expect("the generated table is a String, which never fails to write");
        writeln!(scope_table, "    ({name:?}, {namespace_scope:?}),").expect("the generated table is a String, which never fails to write");
        writeln!(import_ext_table, "    ({name:?}, &[{import_exts}]),")
            .expect("the generated table is a String, which never fails to write");
        writeln!(relative_table, "    ({name:?}, {separator:?}, {package_file:?}),")
            .expect("the generated table is a String, which never fails to write");
        writeln!(separators_table, "    ({name:?}, &[{separators}]),")
            .expect("the generated table is a String, which never fails to write");
        writeln!(parent_table, "    ({name:?}, {parent_alias:?}),")
            .expect("the generated table is a String, which never fails to write");
        writeln!(member_table, "    ({name:?}, &[{}]),", quoted_list(&member_separators))
            .expect("the generated table is a String, which never fails to write");
        writeln!(self_table, "    ({name:?}, &[{}]),", quoted_list(&self_receivers))
            .expect("the generated table is a String, which never fails to write");
        writeln!(implicit_table, "    ({name:?}, {implicit_self}),")
            .expect("the generated table is a String, which never fails to write");
        writeln!(import_self_table, "    ({name:?}, {import_self:?}),")
            .expect("the generated table is a String, which never fails to write");
        for (table, values) in list_field_tables.iter_mut().zip(&list_values) {
            writeln!(table, "    ({name:?}, &[{}]),", quoted_list(values))
                .expect("the generated table is a String, which never fails to write");
        }
        writeln!(family_table, "    ({name:?}, {dir:?}),").expect("the generated table is a String, which never fails to write");
        for (table, value) in alias_field_tables.iter_mut().zip(&alias_values) {
            writeln!(table, "    ({name:?}, {value:?}),").expect("the generated table is a String, which never fails to write");
        }
    }

    body.push_str("    ]\n}\n");
    ext_table.push_str("];\n");
    body.push_str(&ext_table);
    alias_table.push_str("];\n");
    body.push_str(&alias_table);
    scope_table.push_str("];\n");
    body.push_str(&scope_table);
    import_ext_table.push_str("];\n");
    body.push_str(&import_ext_table);
    relative_table.push_str("];\n");
    body.push_str(&relative_table);
    separators_table.push_str("];\n");
    body.push_str(&separators_table);
    parent_table.push_str("];\n");
    body.push_str(&parent_table);
    for table in
        [&mut member_table, &mut self_table, &mut implicit_table, &mut family_table, &mut import_self_table]
            .into_iter()
            .chain(list_field_tables.iter_mut())
    {
        table.push_str("];\n");
        body.push_str(table);
    }
    for table in &mut alias_field_tables {
        table.push_str("];\n");
        body.push_str(table);
    }

    let out_path = Path::new(&out_dir).join("langs_generated.rs");
    fs::write(&out_path, body).expect("write langs_generated.rs");
}

/// A lista OPCIONAL de textos do campo `key`: vazia sem o campo. Declarada,
/// ela precisa de ao menos um texto, e nenhum deles vazio.
fn str_list(tbl: &toml::value::Table, key: &str) -> Vec<String> {
    let Some(value) = tbl.get(key) else { return Vec::new() };
    let list: Vec<String> = value
        .as_array()
        .unwrap_or_else(|| panic!("language.{key} must be an array"))
        .iter()
        .map(|e| e.as_str().unwrap_or_else(|| panic!("each language.{key} must be a string")).to_string())
        .collect();
    assert!(
        !list.is_empty() && list.iter().all(|s| !s.is_empty()),
        "language.{key} must list at least one non-empty text"
    );
    list
}

/// Os textos como literais de Rust, separados por vírgula.
fn quoted_list(list: &[String]) -> String {
    list.iter().map(|s| format!("{s:?}")).collect::<Vec<_>>().join(", ")
}

fn str_field(tbl: &toml::value::Table, key: &str) -> String {
    tbl.get(key)
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("language entry missing string field `{key}`"))
        .to_string()
}

/// Read and concatenate every `.scm` file under `queries/<dir>/`, sorted by name
/// so `tags.scm` and `supertypes.scm` combine deterministically.
fn read_queries(crate_root: &Path, root: &Path, dir: &str) -> String {
    let langdir = root.join(dir);
    let mut files: Vec<_> = fs::read_dir(&langdir)
        .unwrap_or_else(|e| panic!("cannot read query dir {}: {e}", langdir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("scm"))
        .collect();
    files.sort();

    let mut combined = String::new();
    for f in files {
        println!("cargo:rerun-if-changed={}", relative_to(crate_root, &f));
        let part = fs::read_to_string(&f)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", f.display()));
        combined.push_str(&part);
        combined.push('\n');
    }
    combined
}

/// A digest of the scan's own sources: every file under `src/` and `queries/`,
/// and every data `.toml` at the crate root (the package manifest apart, whose
/// version already enters the format). Paths are relative and sorted, so the
/// digest depends on the content only, never on where the crate is checked
/// out. FNV-1a over 64 bits: stable across builds and toolchains, with no
/// dependency to add.
fn source_digest(crate_root: &Path) -> String {
    let mut files: Vec<std::path::PathBuf> = Vec::new();
    collect_files(&crate_root.join("src"), &mut files);
    collect_files(&crate_root.join("queries"), &mut files);
    for entry in fs::read_dir(crate_root).expect("read the crate root").flatten() {
        let path = entry.path();
        let is_data_toml = path.extension().and_then(|e| e.to_str()) == Some("toml")
            && path.file_name().and_then(|n| n.to_str()) != Some("Cargo.toml");
        if is_data_toml && path.is_file() {
            println!("cargo:rerun-if-changed={}", relative_to(crate_root, &path));
            files.push(path);
        }
    }
    let mut named: Vec<(String, std::path::PathBuf)> =
        files.into_iter().map(|p| (relative_to(crate_root, &p), p)).collect();
    named.sort();

    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    let mut feed = |bytes: &[u8]| {
        for b in bytes {
            hash ^= u64::from(*b);
            hash = hash.wrapping_mul(0x0100_0000_01b3);
        }
    };
    for (rel, path) in named {
        let body = fs::read(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        feed(rel.as_bytes());
        feed(&[0]);
        feed(&(body.len() as u64).to_le_bytes());
        feed(&body);
    }
    format!("{hash:016x}")
}

/// `path` as cargo should record a watched file: relative to the crate root.
///
/// Cargo keeps a watched path as it is printed. An absolute one names the copy
/// of the project that ran this script; the build folder is shared between
/// copies, so the next copy sees another path, or a missing file once that
/// copy is gone, and runs this script again — which recompiles the crate and
/// everything above it. A relative path is read from the crate root of the copy
/// being built.
fn relative_to(crate_root: &Path, path: &Path) -> String {
    path.strip_prefix(crate_root).unwrap_or(path).to_string_lossy().replace('\\', "/")
}

/// Every file under `dir`, at any depth.
fn collect_files(dir: &Path, out: &mut Vec<std::path::PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, out);
        } else {
            out.push(path);
        }
    }
}
