//! Build script: turn the external language registry (languages.toml) and the
//! external query files (queries/<dir>/*.scm) into one generated Rust file in
//! OUT_DIR. This is where — and the ONLY where — grammar crate symbols and
//! language names are referenced. The crate's own `src/` therefore contains no
//! language identifier, extension, or grammar node name: adding a language is a
//! data change (a languages.toml row + .scm files), never a logic change.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let registry_path = Path::new(&manifest).join("languages.toml");
    let queries_root = Path::new(&manifest).join("queries");

    println!("cargo:rerun-if-changed=languages.toml");
    println!("cargo:rerun-if-changed=queries");

    let registry_src = fs::read_to_string(&registry_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", registry_path.display()));
    let registry: toml::Value = registry_src
        .parse()
        .unwrap_or_else(|e| panic!("languages.toml is not valid TOML: {e}"));

    let languages = registry
        .get("language")
        .and_then(|v| v.as_array())
        .expect("languages.toml must contain a [[language]] array");

    let mut body = String::new();
    body.push_str("// @generated by build.rs from languages.toml + queries/*.scm — do not edit.\n");
    body.push_str("pub(crate) fn raw_langs() -> Vec<RawLang> {\n    vec![\n");

    // A lightweight (name, extensions) table for detection — built without
    // constructing any grammar, so per-file language detection stays cheap.
    let mut ext_table = String::new();
    ext_table.push_str("pub(crate) static LANG_EXTENSIONS: &[(&str, &[&str])] = &[\n");

    // (name, root_aliases) table — the OPTIONAL per-language import segments
    // that alias the package root (e.g. Rust's `crate`/`self`/`super`). The
    // graph's root-alias resolution branch only runs for imports whose first
    // segment is declared here; a language without the field gets an empty
    // slice and never takes that branch.
    let mut alias_table = String::new();
    alias_table.push_str("pub(crate) static LANG_ROOT_ALIASES: &[(&str, &[&str])] = &[\n");

    for lang in languages {
        let tbl = lang.as_table().expect("each [[language]] must be a table");
        let name = str_field(tbl, "name");
        let dir = str_field(tbl, "dir");
        let grammar = str_field(tbl, "grammar");
        let extensions: Vec<String> = tbl
            .get("extensions")
            .and_then(|v| v.as_array())
            .expect("language.extensions must be an array")
            .iter()
            .map(|e| e.as_str().expect("extension must be a string").to_string())
            .collect();
        let root_aliases: Vec<String> = tbl
            .get("root_aliases")
            .map(|v| {
                v.as_array()
                    .expect("language.root_aliases must be an array")
                    .iter()
                    .map(|e| e.as_str().expect("root alias must be a string").to_string())
                    .collect()
            })
            .unwrap_or_default();

        // Concatenate every .scm under queries/<dir>/, in stable filename order.
        let query = read_queries(&queries_root, &dir);

        let exts = extensions
            .iter()
            .map(|e| format!("{e:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        let aliases = root_aliases
            .iter()
            .map(|a| format!("{a:?}"))
            .collect::<Vec<_>>()
            .join(", ");

        writeln!(
            body,
            "        RawLang {{ name: {name:?}, query: {query:?}, language: {grammar}.into() }},"
        )
        .unwrap();
        writeln!(ext_table, "    ({name:?}, &[{exts}]),").unwrap();
        writeln!(alias_table, "    ({name:?}, &[{aliases}]),").unwrap();
    }

    body.push_str("    ]\n}\n");
    ext_table.push_str("];\n");
    body.push_str(&ext_table);
    alias_table.push_str("];\n");
    body.push_str(&alias_table);

    let out_path = Path::new(&out_dir).join("langs_generated.rs");
    fs::write(&out_path, body).expect("write langs_generated.rs");
}

fn str_field(tbl: &toml::value::Table, key: &str) -> String {
    tbl.get(key)
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("language entry missing string field `{key}`"))
        .to_string()
}

/// Read and concatenate every `.scm` file under `queries/<dir>/`, sorted by name
/// so `tags.scm` and `supertypes.scm` combine deterministically.
fn read_queries(root: &Path, dir: &str) -> String {
    let langdir = root.join(dir);
    let mut files: Vec<_> = fs::read_dir(&langdir)
        .unwrap_or_else(|e| panic!("cannot read query dir {}: {e}", langdir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("scm"))
        .collect();
    files.sort();

    let mut combined = String::new();
    for f in files {
        println!("cargo:rerun-if-changed={}", f.display());
        let part = fs::read_to_string(&f)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", f.display()));
        combined.push_str(&part);
        combined.push('\n');
    }
    combined
}
