//! Build script: turn the external language registry (languages.toml) and the
//! external query files (queries/<dir>/*.scm) into one generated Rust file in
//! OUT_DIR, and the route rules of each framework (routes/<framework>.toml and
//! routes/<framework>/*.scm) into another. This is where — and the ONLY where — grammar crate symbols and
//! language names are referenced. The crate's own `src/` therefore contains no
//! language identifier, extension, or grammar node name: adding a language is a
//! data change (a languages.toml row + .scm files), never a logic change.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let registry_path = Path::new(&manifest).join("languages.toml");
    let queries_root = Path::new(&manifest).join("queries");

    println!("cargo:rerun-if-changed=languages.toml");
    println!("cargo:rerun-if-changed=queries");
    println!("cargo:rerun-if-changed=routes");
    println!("cargo:rerun-if-changed=src");

    // The map format: a digest of everything that decides what the scan
    // yields from a file — the engine (src), the queries, the route rules, and
    // the data tables at the crate root. A map written by a scan built from other sources is
    // read again in full, so no change to the scan can leave a stale map
    // behind, and nobody has to remember to bump a number by hand.
    println!("cargo:rustc-env=SCAN_MAP_DIGEST={}", source_digest(Path::new(&manifest)));

    let registry_src = fs::read_to_string(&registry_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", registry_path.display()));
    // toml 1.x: `str::parse::<Value>` parses a lone TOML *value*, not a
    // document — document parsing goes through the serde path (`from_str`).
    let registry: toml::Value = toml::from_str(&registry_src)
        .unwrap_or_else(|e| panic!("languages.toml is not valid TOML: {e}"));

    let languages = registry
        .get("language")
        .and_then(|v| v.as_array())
        .expect("languages.toml must contain a [[language]] array");

    let mut body = String::new();
    body.push_str("// @generated by build.rs from languages.toml + queries/*.scm — do not edit.\n");
    body.push_str("pub(crate) fn raw_langs() -> Vec<RawLang> {\n    vec![\n");

    // A lightweight (name, extensions) table for detection — built without
    // constructing any grammar, so per-file language detection stays cheap.
    let mut ext_table = String::new();
    ext_table.push_str("pub(crate) static LANG_EXTENSIONS: &[(&str, &[&str])] = &[\n");

    // (name, root_aliases) table — the OPTIONAL per-language import segments
    // that alias the package root (e.g. Rust's `crate`/`self`). The
    // graph's root-alias resolution branch only runs for imports whose first
    // segment is declared here; a language without the field gets an empty
    // slice and never takes that branch.
    let mut alias_table = String::new();
    alias_table.push_str("pub(crate) static LANG_ROOT_ALIASES: &[(&str, &[&str])] = &[\n");

    // (name, namespace_scope) table — the OPTIONAL rule for how a declared
    // namespace is seen by the other files of the language ("folder" or
    // "nested"). A language without the field gets an empty string: a
    // namespace is seen only by the files that declare the same one.
    let mut scope_table = String::new();
    scope_table.push_str("pub(crate) static LANG_NAMESPACE_SCOPE: &[(&str, &str)] = &[\n");

    // (name, import_extensions) — as extensões OPCIONAIS que o import da
    // língua escreve no lugar da do próprio arquivo. Sem o campo, lista vazia:
    // o caminho importado só perde a extensão quando ela é da própria língua.
    let mut import_ext_table = String::new();
    import_ext_table.push_str("pub(crate) static LANG_IMPORT_EXTENSIONS: &[(&str, &[&str])] = &[\n");

    // (name, alias_config), (name, alias_base), (name, alias_paths) e
    // (name, alias_extends) — o arquivo de configuração OPCIONAL dos apelidos
    // de pasta e as três chaves lidas nele. Sem o campo, texto vazio: a
    // língua não tem apelido de pasta e a leitura nem começa.
    // (name, separator) — o import relativo OPCIONAL que a língua escreve com
    // um separador no lugar da barra. Sem o campo, texto vazio: o import da
    // língua nunca é lido assim. O arquivo que responde pela pasta vem da
    // lista do núcleo (`CORE_ENTRY_FILES`), pelo nome da língua.
    let mut relative_table = String::new();
    relative_table.push_str("pub(crate) static LANG_RELATIVE_IMPORT: &[(&str, &str)] = &[\n");

    // (name, qualified_separators) — os textos OPCIONAIS que juntam as partes
    // de um nome qualificado na língua. Sem o campo, lista vazia: o motor usa
    // os separadores de sempre.
    let mut separators_table = String::new();
    separators_table.push_str("pub(crate) static LANG_QUALIFIED_SEPARATORS: &[(&str, &[&str])] = &[\n");

    // (name, parent_alias) — o nome OPCIONAL que, no começo de um caminho
    // qualificado, sobe um módulo. Sem o campo, texto vazio: nenhum caminho
    // da língua é lido assim.
    let mut parent_table = String::new();
    parent_table.push_str("pub(crate) static LANG_PARENT_ALIAS: &[(&str, &str)] = &[\n");

    // (name, module_alias) — o nome OPCIONAL que, no começo de um caminho
    // qualificado, nomeia o próprio módulo de quem escreve. Sem o campo,
    // texto vazio: nenhum caminho da língua é lido assim.
    let mut module_table = String::new();
    module_table.push_str("pub(crate) static LANG_MODULE_ALIAS: &[(&str, &str)] = &[\n");

    // (name, member_separators) e (name, self_receivers) — os textos
    // OPCIONAIS que ligam o método ao valor antes dele sem juntar caminho, e
    // os nomes que são o próprio objeto. Sem o campo, lista vazia.
    let mut member_table = String::new();
    member_table.push_str("pub(crate) static LANG_MEMBER_SEPARATORS: &[(&str, &[&str])] = &[\n");
    let mut self_table = String::new();
    self_table.push_str("pub(crate) static LANG_SELF_RECEIVERS: &[(&str, &[&str])] = &[\n");

    // (name, implicit_self) — se o nome sozinho alcança um membro do próprio
    // objeto. OPCIONAL: sem o campo, `false`.
    let mut implicit_table = String::new();
    implicit_table.push_str("pub(crate) static LANG_IMPLICIT_SELF: &[(&str, bool)] = &[\n");

    // (name, import_self) — o nome OPCIONAL que, trazido por um import, traz
    // o último nome escrito antes da lista que o contém. Sem o campo, texto
    // vazio: todo nome trazido é ele mesmo.
    let mut import_self_table = String::new();
    import_self_table.push_str("pub(crate) static LANG_IMPORT_SELF: &[(&str, &str)] = &[\n");

    // (name, prelude), (name, log_calls), (name, error_forms), (name,
    // parent_receivers) e (name, package_entry) — os nomes OPCIONAIS que todo
    // arquivo vê sem import, as chamadas que escrevem log, as formas que
    // lançam ou devolvem erro, os nomes do próprio objeto visto pelo tipo de
    // cima e os arquivos raiz de um pacote. Sem o campo, lista vazia.
    let list_fields = ["prelude", "log_calls", "error_forms", "parent_receivers", "package_entry"];
    let mut list_field_tables: Vec<String> = list_fields
        .iter()
        .map(|field| format!("pub(crate) static LANG_{}: &[(&str, &[&str])] = &[\n", field.to_ascii_uppercase()))
        .collect();

    // (name, dir) — a família da língua: as que leem as mesmas consultas
    // (`dir`) são a mesma língua escrita em arquivos diferentes, e uma chamada
    // alcança as declarações da família inteira.
    let mut family_table = String::new();
    family_table.push_str("pub(crate) static LANG_FAMILY: &[(&str, &str)] = &[\n");

    let alias_fields = ["alias_config", "alias_base", "alias_paths", "alias_extends"];
    let mut alias_field_tables: Vec<String> = alias_fields
        .iter()
        .map(|field| format!("pub(crate) static LANG_{}: &[(&str, &str)] = &[\n", field.to_ascii_uppercase()))
        .collect();

    for lang in languages {
        let tbl = lang.as_table().expect("each [[language]] must be a table");
        let name = str_field(tbl, "name");
        let dir = str_field(tbl, "dir");
        let grammar = str_field(tbl, "grammar");
        let extensions: Vec<String> = tbl
            .get("extensions")
            .and_then(|v| v.as_array())
            .expect("language.extensions must be an array")
            .iter()
            .map(|e| e.as_str().expect("extension must be a string").to_string())
            .collect();
        let root_aliases: Vec<String> = tbl
            .get("root_aliases")
            .map(|v| {
                v.as_array()
                    .expect("language.root_aliases must be an array")
                    .iter()
                    .map(|e| e.as_str().expect("root alias must be a string").to_string())
                    .collect()
            })
            .unwrap_or_default();
        // The OPTIONAL markup tags the language writes its documentation
        // comments with: the engine drops them and keeps the text.
        let doc_tags: Vec<String> = tbl
            .get("doc_tags")
            .map(|v| {
                v.as_array()
                    .expect("language.doc_tags must be an array")
                    .iter()
                    .map(|e| e.as_str().expect("doc tag must be a string").to_string())
                    .collect()
            })
            .unwrap_or_default();
        let import_extensions: Vec<String> = tbl
            .get("import_extensions")
            .map(|v| {
                v.as_array()
                    .expect("language.import_extensions must be an array")
                    .iter()
                    .map(|e| e.as_str().expect("import extension must be a string").to_string())
                    .collect()
            })
            .unwrap_or_default();
        let alias_values: Vec<String> = alias_fields
            .iter()
            .map(|field| {
                tbl.get(*field)
                    .map(|v| v.as_str().unwrap_or_else(|| panic!("language.{field} must be a string")).to_string())
                    .unwrap_or_default()
            })
            .collect();
        let separator = tbl.get("relative_import").map_or_else(String::new, |v| {
            let rule = v.as_table().expect("language.relative_import must be a table");
            let separator = rule
                .get("separator")
                .map(|v| v.as_str().expect("language.relative_import.separator must be a string").to_string())
                .unwrap_or_default();
            assert!(!separator.is_empty(), "language.relative_import of `{name}` must declare a non-empty separator");
            separator
        });
        let qualified_separators: Vec<String> = tbl
            .get("qualified_separators")
            .map(|v| {
                v.as_array()
                    .expect("language.qualified_separators must be an array")
                    .iter()
                    .map(|e| e.as_str().expect("qualified separator must be a string").to_string())
                    .collect()
            })
            .unwrap_or_default();
        // A lista vazia na tabela quer dizer "sem o campo": declarada, ela
        // precisa de ao menos um separador, e nenhum deles vazio.
        assert!(
            tbl.get("qualified_separators").is_none()
                || (!qualified_separators.is_empty() && qualified_separators.iter().all(|s| !s.is_empty())),
            "language.qualified_separators of `{name}` must list at least one non-empty separator"
        );
        let member_separators = str_list(tbl, "member_separators");
        let self_receivers = str_list(tbl, "self_receivers");
        let implicit_self = tbl
            .get("implicit_self")
            .map(|v| v.as_bool().expect("language.implicit_self must be true or false"))
            .unwrap_or(false);
        let parent_alias = tbl
            .get("parent_alias")
            .map(|v| v.as_str().expect("language.parent_alias must be a string").to_string())
            .unwrap_or_default();
        // O texto vazio na tabela quer dizer "sem o campo": declarado, ele
        // não pode ser vazio.
        assert!(
            tbl.get("parent_alias").is_none() || !parent_alias.is_empty(),
            "language.parent_alias of `{name}` must not be empty"
        );
        let module_alias = tbl
            .get("module_alias")
            .map(|v| v.as_str().expect("language.module_alias must be a string").to_string())
            .unwrap_or_default();
        assert!(
            tbl.get("module_alias").is_none() || !module_alias.is_empty(),
            "language.module_alias of `{name}` must not be empty"
        );
        let import_self = tbl
            .get("import_self")
            .map(|v| v.as_str().expect("language.import_self must be a string").to_string())
            .unwrap_or_default();
        assert!(
            tbl.get("import_self").is_none() || !import_self.is_empty(),
            "language.import_self of `{name}` must not be empty"
        );
        let list_values: Vec<Vec<String>> = list_fields.iter().map(|field| str_list(tbl, field)).collect();
        let namespace_scope = tbl
            .get("namespace_scope")
            .map(|v| v.as_str().expect("language.namespace_scope must be a string").to_string())
            .unwrap_or_default();
        assert!(
            matches!(namespace_scope.as_str(), "" | "folder" | "nested"),
            "language.namespace_scope of `{name}` must be \"folder\" or \"nested\", not {namespace_scope:?}"
        );

        // Concatenate every .scm under queries/<dir>/, in stable filename order.
        let mut query = read_queries(Path::new(&manifest), &queries_root, &dir);
        // A pasta a mais da entrada: os `.scm` dela entram só nesta consulta,
        // depois dos de `dir`, que segue sendo a família da língua.
        if let Some(extra) = tbl.get("extra_queries") {
            let extra = extra.as_str().expect("language.extra_queries must be a string");
            assert!(
                !extra.is_empty() && queries_root.join(extra).is_dir(),
                "language.extra_queries of `{name}` names `{extra}`, but queries/{extra}/ is not a folder"
            );
            query.push_str(&read_queries(Path::new(&manifest), &queries_root, extra));
        }

        let exts = extensions
            .iter()
            .map(|e| format!("{e:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        let aliases = root_aliases
            .iter()
            .map(|a| format!("{a:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        let tags = doc_tags.iter().map(|t| format!("{t:?}")).collect::<Vec<_>>().join(", ");
        let import_exts = import_extensions.iter().map(|e| format!("{e:?}")).collect::<Vec<_>>().join(", ");
        let separators = qualified_separators.iter().map(|s| format!("{s:?}")).collect::<Vec<_>>().join(", ");

        writeln!(
            body,
            "        RawLang {{ name: {name:?}, query: {query:?}, language: {grammar}.into(), doc_tags: &[{tags}] }},"
        )
        .expect("the generated body is a String, which never fails to write");
        writeln!(ext_table, "    ({name:?}, &[{exts}]),").expect("the generated table is a String, which never fails to write");
        writeln!(alias_table, "    ({name:?}, &[{aliases}]),").expect("the generated table is a String, which never fails to write");
        writeln!(scope_table, "    ({name:?}, {namespace_scope:?}),").expect("the generated table is a String, which never fails to write");
        writeln!(import_ext_table, "    ({name:?}, &[{import_exts}]),")
            .expect("the generated table is a String, which never fails to write");
        writeln!(relative_table, "    ({name:?}, {separator:?}),")
            .expect("the generated table is a String, which never fails to write");
        writeln!(separators_table, "    ({name:?}, &[{separators}]),")
            .expect("the generated table is a String, which never fails to write");
        writeln!(parent_table, "    ({name:?}, {parent_alias:?}),")
            .expect("the generated table is a String, which never fails to write");
        writeln!(module_table, "    ({name:?}, {module_alias:?}),")
            .expect("the generated table is a String, which never fails to write");
        writeln!(member_table, "    ({name:?}, &[{}]),", quoted_list(&member_separators))
            .expect("the generated table is a String, which never fails to write");
        writeln!(self_table, "    ({name:?}, &[{}]),", quoted_list(&self_receivers))
            .expect("the generated table is a String, which never fails to write");
        writeln!(implicit_table, "    ({name:?}, {implicit_self}),")
            .expect("the generated table is a String, which never fails to write");
        writeln!(import_self_table, "    ({name:?}, {import_self:?}),")
            .expect("the generated table is a String, which never fails to write");
        for (table, values) in list_field_tables.iter_mut().zip(&list_values) {
            writeln!(table, "    ({name:?}, &[{}]),", quoted_list(values))
                .expect("the generated table is a String, which never fails to write");
        }
        writeln!(family_table, "    ({name:?}, {dir:?}),").expect("the generated table is a String, which never fails to write");
        for (table, value) in alias_field_tables.iter_mut().zip(&alias_values) {
            writeln!(table, "    ({name:?}, {value:?}),").expect("the generated table is a String, which never fails to write");
        }
    }

    body.push_str("    ]\n}\n");
    ext_table.push_str("];\n");
    body.push_str(&ext_table);
    alias_table.push_str("];\n");
    body.push_str(&alias_table);
    scope_table.push_str("];\n");
    body.push_str(&scope_table);
    import_ext_table.push_str("];\n");
    body.push_str(&import_ext_table);
    relative_table.push_str("];\n");
    body.push_str(&relative_table);
    separators_table.push_str("];\n");
    body.push_str(&separators_table);
    parent_table.push_str("];\n");
    body.push_str(&parent_table);
    module_table.push_str("];\n");
    body.push_str(&module_table);
    for table in
        [&mut member_table, &mut self_table, &mut implicit_table, &mut family_table, &mut import_self_table]
            .into_iter()
            .chain(list_field_tables.iter_mut())
    {
        table.push_str("];\n");
        body.push_str(table);
    }
    for table in &mut alias_field_tables {
        table.push_str("];\n");
        body.push_str(table);
    }

    let out_path = Path::new(&out_dir).join("langs_generated.rs");
    fs::write(&out_path, body).expect("write langs_generated.rs");

    let names: Vec<&str> = languages.iter().filter_map(|entry| entry.get("name").and_then(|v| v.as_str())).collect();
    check_entry_file_languages(Path::new(&manifest), &names);
    let routes = route_rules(Path::new(&manifest), &names);
    fs::write(Path::new(&out_dir).join("routes_generated.rs"), routes).expect("write routes_generated.rs");
}

/// Cada língua da lista do arquivo de entrada do núcleo (`CORE_ENTRY_FILES`)
/// é uma do registro (`languages`): a chave que ele não declara nunca seria
/// lida, e o erro para a compilação.
fn check_entry_file_languages(crate_root: &Path, languages: &[&str]) {
    let path = crate_root.join(CORE_ENTRY_FILES);
    let src = fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let table: toml::value::Table =
        toml::from_str(&src).unwrap_or_else(|e| panic!("{CORE_ENTRY_FILES} is not valid TOML: {e}"));
    for lang in table.keys() {
        assert!(
            languages.contains(&lang.as_str()),
            "{CORE_ENTRY_FILES} names the language `{lang}`, which languages.toml does not declare"
        );
    }
}

/// A tabela das regras de rota: uma por `routes/<framework>.toml`, em ordem de
/// nome, com a consulta dos `.scm` de `routes/<framework>/`. O nome do
/// arquivo é o do framework. Cada língua da regra é uma do registro
/// (`languages`), e cada método da tabela é um nome HTTP em maiúsculas ou `*`,
/// que vale qualquer um; o erro para a compilação.
fn route_rules(crate_root: &Path, languages: &[&str]) -> String {
    let root = crate_root.join("routes");
    let mut files: Vec<_> = fs::read_dir(&root)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", root.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("toml"))
        .collect();
    files.sort();

    let mut table = String::from(
        "// @generated by build.rs from routes/*.toml + routes/<framework>/*.scm — do not edit.\n\
         pub(crate) static ROUTE_RULES: &[RawRouteRule] = &[\n",
    );
    for file in files {
        println!("cargo:rerun-if-changed={}", relative_to(crate_root, &file));
        let framework = file.file_stem().and_then(|s| s.to_str()).expect("a route file has a name").to_string();
        let src = fs::read_to_string(&file).unwrap_or_else(|e| panic!("cannot read {}: {e}", file.display()));
        let tbl: toml::value::Table =
            toml::from_str(&src).unwrap_or_else(|e| panic!("routes/{framework}.toml is not valid TOML: {e}"));
        let list = |key: &str, required: bool| -> Vec<String> {
            let Some(value) = tbl.get(key) else {
                assert!(!required, "routes/{framework}.toml must declare `{key}`");
                return Vec::new();
            };
            let list: Vec<String> = value
                .as_array()
                .unwrap_or_else(|| panic!("routes/{framework}.toml: `{key}` must be an array"))
                .iter()
                .map(|e| e.as_str().unwrap_or_else(|| panic!("routes/{framework}.toml: each `{key}` is a string")).to_string())
                .collect();
            assert!(
                !list.is_empty() && list.iter().all(|s| !s.is_empty()),
                "routes/{framework}.toml: `{key}` must list at least one non-empty text"
            );
            list
        };
        let text = |key: &str| -> String {
            tbl.get(key).map_or_else(String::new, |v| {
                v.as_str().unwrap_or_else(|| panic!("routes/{framework}.toml: `{key}` must be a string")).to_string()
            })
        };
        let rule_languages = list("language", true);
        for lang in &rule_languages {
            assert!(
                languages.contains(&lang.as_str()),
                "routes/{framework}.toml names the language `{lang}`, which languages.toml does not declare"
            );
        }
        // A regra global liga em todo arquivo das línguas dela e não tem
        // import; a outra liga pelo import, e precisa dele.
        let global = match tbl.get("global") {
            None => false,
            Some(value) => value.as_bool().unwrap_or_else(|| panic!("routes/{framework}.toml: `global` must be true or false")),
        };
        let imports = list("imports", !global);
        assert!(!global || imports.is_empty(), "routes/{framework}.toml: a `global` rule has no `imports`");
        let methods: Vec<(String, String)> = tbl
            .get("methods")
            .and_then(|v| v.as_table())
            .unwrap_or_else(|| panic!("routes/{framework}.toml must declare a [methods] table"))
            .iter()
            .map(|(written, method)| {
                let method = method.as_str().unwrap_or_else(|| panic!("routes/{framework}.toml: method `{written}` is a string"));
                assert!(
                    method == "*" || (!method.is_empty() && method.chars().all(|c| c.is_ascii_uppercase())),
                    "routes/{framework}.toml: method `{written}` must be an uppercase HTTP name or `*`, not `{method}`"
                );
                (written.clone(), method.to_string())
            })
            .collect();
        assert!(!methods.is_empty(), "routes/{framework}.toml: [methods] must name at least one method");
        let wrappers: Vec<(String, String)> = tbl.get("param_wrappers").map_or_else(Vec::new, |v| {
            v.as_array()
                .unwrap_or_else(|| panic!("routes/{framework}.toml: `param_wrappers` must be an array"))
                .iter()
                .map(|pair| match pair.as_array().map(|p| p.iter().filter_map(|s| s.as_str()).collect::<Vec<_>>()) {
                    Some(p) if p.len() == 2 && p.iter().all(|s| !s.is_empty()) => (p[0].to_string(), p[1].to_string()),
                    _ => panic!("routes/{framework}.toml: each `param_wrappers` entry is [open, close]"),
                })
                .collect()
        });
        let (class_marker, class_suffix) = (text("class_marker"), text("class_suffix"));
        assert!(
            class_suffix.is_empty() || !class_marker.is_empty(),
            "routes/{framework}.toml: `class_suffix` needs a `class_marker`"
        );
        let query = read_queries(crate_root, &root, &framework);
        // A regra é do servidor, que acha rotas, ou da tela, que acha as
        // chamadas a elas: a consulta usa as capturas de um lado só.
        assert!(
            !(query.contains("@route.") && query.contains("@client.")),
            "routes/{framework}: a query captures either `@route.` or `@client.`, never both"
        );
        let pairs = |list: &[(String, String)]| list.iter().map(|(a, b)| format!("({a:?}, {b:?})")).collect::<Vec<_>>().join(", ");
        writeln!(
            table,
            "    RawRouteRule {{ framework: {framework:?}, languages: &[{}], global: {global}, imports: &[{}], \
             manifest_dependencies: &[{}], query: {query:?}, \
             methods: &[{}], param_prefixes: &[{}], param_wrappers: &[{}], reset_marks: &[{}], \
             path_starts: &[{}], exclude_wildcards: &[{}], class_marker: {class_marker:?}, \
             class_suffix: {class_suffix:?} }},",
            quoted_list(&rule_languages),
            quoted_list(&imports),
            quoted_list(&list("manifest_dependencies", false)),
            pairs(&methods),
            quoted_list(&list("param_prefixes", false)),
            pairs(&wrappers),
            quoted_list(&list("reset_marks", false)),
            quoted_list(&list("path_starts", false)),
            quoted_list(&list("exclude_wildcards", false)),
        )
        .expect("the generated table is a String, which never fails to write");
    }
    table.push_str("];\n");
    table
}

/// A lista OPCIONAL de textos do campo `key`: vazia sem o campo. Declarada,
/// ela precisa de ao menos um texto, e nenhum deles vazio.
fn str_list(tbl: &toml::value::Table, key: &str) -> Vec<String> {
    let Some(value) = tbl.get(key) else { return Vec::new() };
    let list: Vec<String> = value
        .as_array()
        .unwrap_or_else(|| panic!("language.{key} must be an array"))
        .iter()
        .map(|e| e.as_str().unwrap_or_else(|| panic!("each language.{key} must be a string")).to_string())
        .collect();
    assert!(
        !list.is_empty() && list.iter().all(|s| !s.is_empty()),
        "language.{key} must list at least one non-empty text"
    );
    list
}

/// Os textos como literais de Rust, separados por vírgula.
fn quoted_list(list: &[String]) -> String {
    list.iter().map(|s| format!("{s:?}")).collect::<Vec<_>>().join(", ")
}

fn str_field(tbl: &toml::value::Table, key: &str) -> String {
    tbl.get(key)
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("language entry missing string field `{key}`"))
        .to_string()
}

/// Read and concatenate every `.scm` file under `<root>/<dir>/` —
/// `queries/<dir>/` or `routes/<framework>/` —, sorted by name so `tags.scm`
/// and `supertypes.scm` combine deterministically.
fn read_queries(crate_root: &Path, root: &Path, dir: &str) -> String {
    let langdir = root.join(dir);
    let mut files: Vec<_> = fs::read_dir(&langdir)
        .unwrap_or_else(|e| panic!("cannot read query dir {}: {e}", langdir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("scm"))
        .collect();
    files.sort();

    let mut combined = String::new();
    for f in files {
        println!("cargo:rerun-if-changed={}", relative_to(crate_root, &f));
        let part = fs::read_to_string(&f)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", f.display()));
        combined.push_str(&part);
        combined.push('\n');
    }
    combined
}

/// A digest of the scan's own sources: every file under `src/`, `queries/` and
/// `routes/`, every data `.toml` at the crate root (the package manifest apart, whose
/// version already enters the format), the core's test-file data, which
/// decides what the scan keeps from each file it reads, and the core's entry-file
/// data, which decides where an import of a folder lands. Paths are relative and sorted, so the
/// digest depends on the content only, never on where the crate is checked
/// out. FNV-1a over 64 bits: stable across builds and toolchains, with no
/// dependency to add.
fn source_digest(crate_root: &Path) -> String {
    let mut files: Vec<std::path::PathBuf> = Vec::new();
    collect_files(&crate_root.join("src"), &mut files);
    collect_files(&crate_root.join("queries"), &mut files);
    collect_files(&crate_root.join("routes"), &mut files);
    for core_data in [CORE_TEST_FILES, CORE_ENTRY_FILES] {
        let core_data = crate_root.join(core_data);
        println!("cargo:rerun-if-changed={}", relative_to(crate_root, &core_data));
        files.push(core_data);
    }
    for entry in fs::read_dir(crate_root).expect("read the crate root").flatten() {
        let path = entry.path();
        let is_data_toml = path.extension().and_then(|e| e.to_str()) == Some("toml")
            && path.file_name().and_then(|n| n.to_str()) != Some("Cargo.toml");
        if is_data_toml && path.is_file() {
            println!("cargo:rerun-if-changed={}", relative_to(crate_root, &path));
            files.push(path);
        }
    }
    let mut named: Vec<(String, std::path::PathBuf)> =
        files.into_iter().map(|p| (relative_to(crate_root, &p), p)).collect();
    named.sort();

    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    let mut feed = |bytes: &[u8]| {
        for b in bytes {
            hash ^= u64::from(*b);
            hash = hash.wrapping_mul(0x0100_0000_01b3);
        }
    };
    for (rel, path) in named {
        let body = fs::read(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        feed(rel.as_bytes());
        feed(&[0]);
        feed(&(body.len() as u64).to_le_bytes());
        feed(&body);
    }
    format!("{hash:016x}")
}

/// The core's test-file data, from the crate root: which files are tests and
/// which content marks a file that holds its own tests.
const CORE_TEST_FILES: &str = "../../packages/core/src/domain/ast/test-files.toml";

/// The core's entry-file data, from the crate root: for each language of the
/// registry, the names of the file that answers for its folder.
const CORE_ENTRY_FILES: &str = "../../packages/core/src/domain/ast/entry-files.toml";

/// `path` as cargo should record a watched file: relative to the crate root.
///
/// Cargo keeps a watched path as it is printed. An absolute one names the copy
/// of the project that ran this script; the build folder is shared between
/// copies, so the next copy sees another path, or a missing file once that
/// copy is gone, and runs this script again — which recompiles the crate and
/// everything above it. A relative path is read from the crate root of the copy
/// being built.
fn relative_to(crate_root: &Path, path: &Path) -> String {
    path.strip_prefix(crate_root).unwrap_or(path).to_string_lossy().replace('\\', "/")
}

/// Every file under `dir`, at any depth.
fn collect_files(dir: &Path, out: &mut Vec<std::path::PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, out);
        } else {
            out.push(path);
        }
    }
}
